import { CategoryInfo, FeedSource, SponsorshipPackage } from "./types";

export const CATEGORIES: CategoryInfo[] = [
  {
    id: "financial",
    name: "Royalties & Catalogues",
    slug: "financial",
    icon: "BadgeDollarSign",
    color: "#10B981",
    description: "Publishing rights, catalogue sales benchmarks, streaming payouts, sync licenses, and artist equity.",
  },
  {
    id: "streaming",
    name: "Streaming & Playlists",
    slug: "streaming",
    icon: "Radio",
    color: "#3B82F6",
    description: "Spotify algorithm updates, Apple Music discovery, editorial playlist strategies, and DSP threshold policy.",
  },
  {
    id: "tech-ai",
    name: "AI & Music Tech",
    slug: "tech-ai",
    icon: "Cpu",
    color: "#8B5CF6",
    description: "Generative audio tools, stem separation, AI mastering, blockchain metadata, and creator software.",
  },
  {
    id: "marketing",
    name: "TikTok & Viral Growth",
    slug: "marketing",
    icon: "TrendingUp",
    color: "#EC4899",
    description: "Short-form video strategies, influencer sound seeding, pre-save campaigns, and grassroots fan engagement.",
  },
  {
    id: "legal",
    name: "Legal & Copyright",
    slug: "legal",
    icon: "Scale",
    color: "#F59E0B",
    description: "Sampling rights, 360 deals vs distribution splits, copyright enforcement, and trademark defense.",
  },
  {
    id: "podcasts",
    name: "Podcasts & Interviews",
    slug: "podcasts",
    icon: "Headphones",
    color: "#06B6D4",
    description: "Deep conversations with A&Rs, music attorneys, independent moguls, and chart-topping producers.",
  },
  {
    id: "tutorials",
    name: "DIY Masterclasses",
    slug: "tutorials",
    icon: "GraduationCap",
    color: "#14B8A6",
    description: "Step-by-step guides on release schedules, Meta ad funnels, pitch decks, and home studio acoustics.",
  },
  {
    id: "opportunities",
    name: "Press Passes & Grants",
    slug: "opportunities",
    icon: "Ticket",
    color: "#D4FF00",
    description: "Open artist grants, festival showcase submissions, media accreditation, and sync licensing briefs.",
  },
  {
    id: "social",
    name: "Social & Community",
    slug: "social",
    icon: "Users",
    color: "#FF6B6B",
    description: "Artist features, community spotlights, trending conversations, and social media highlights from the music industry.",
  },
];

// Three main content pillars for homepage display
export const PILLARS = {
  business: {
    name: "Business",
    color: "#047857",
    description: "Royalties, deals, streaming economics, and industry finance",
    categories: ["financial", "legal", "streaming"],
  },
  culture: {
    name: "Culture",
    color: "#C1121F",
    description: "Releases, tours, reviews, and music news",
    categories: ["marketing", "podcasts"],
  },
  social: {
    name: "Social",
    color: "#7C3AED",
    description: "Artist features, community stories, and trending conversations",
    categories: ["social", "tutorials", "opportunities", "tech-ai"],
  },
};

// ============================================================================
// 100+ MUSIC INDUSTRY RSS FEEDS
// Organized by tier and category
// ============================================================================

export const INITIAL_FEEDS: FeedSource[] = [
  // ============================================================================
  // TIER 1: PRIMARY AUTHORITY SOURCES (20 feeds)
  // These are the most trusted, high-quality sources
  // ============================================================================

  // #1 PRIORITY - Music Business Worldwide
  {
    id: "feed-mbw-main",
    name: "Music Business Worldwide",
    url: "https://www.musicbusinessworldwide.com/feed/",
    category: "financial",
    website: "https://musicbusinessworldwide.com",
    tier: "tier1",
    enabled: true,
    status: "healthy",
    priority: 1,
  },
  {
    id: "feed-billboard-biz",
    name: "Billboard Pro",
    url: "https://www.billboard.com/c/business/feed/",
    category: "financial",
    website: "https://billboard.com/business",
    tier: "tier1",
    enabled: true,
    status: "healthy",
    priority: 2,
  },
  {
    id: "feed-billboard-main",
    name: "Billboard News",
    url: "https://www.billboard.com/feed/",
    category: "streaming",
    website: "https://billboard.com",
    tier: "tier1",
    enabled: true,
    status: "healthy",
    priority: 3,
  },
  {
    id: "feed-variety-music",
    name: "Variety Music",
    url: "https://variety.com/v/music/feed/",
    category: "financial",
    website: "https://variety.com/c/music",
    tier: "tier1",
    enabled: true,
    status: "healthy",
  },
  {
    id: "feed-rollingstone",
    name: "Rolling Stone Music",
    url: "https://www.rollingstone.com/music/music-news/feed/",
    category: "marketing",
    website: "https://rollingstone.com",
    tier: "tier1",
    enabled: true,
    status: "healthy",
  },
  {
    id: "feed-pitchfork",
    name: "Pitchfork News",
    url: "https://pitchfork.com/feed/feed-news/rss",
    category: "marketing",
    website: "https://pitchfork.com",
    tier: "tier1",
    enabled: true,
    status: "healthy",
  },
  {
    id: "feed-pitchfork-reviews",
    name: "Pitchfork Reviews",
    url: "https://pitchfork.com/feed/feed-album-reviews/rss",
    category: "social",
    website: "https://pitchfork.com/reviews/albums",
    tier: "tier1",
    enabled: true,
    status: "healthy",
  },
  {
    id: "feed-thefader",
    name: "The FADER",
    url: "https://www.thefader.com/feed",
    category: "marketing",
    website: "https://thefader.com",
    tier: "tier1",
    enabled: true,
    status: "healthy",
  },
  {
    id: "feed-stereogum",
    name: "Stereogum",
    url: "https://www.stereogum.com/feed/",
    category: "streaming",
    website: "https://stereogum.com",
    tier: "tier1",
    enabled: true,
    status: "healthy",
  },
  {
    id: "feed-consequence",
    name: "Consequence of Sound",
    url: "https://consequence.net/feed/",
    category: "marketing",
    website: "https://consequence.net",
    tier: "tier1",
    enabled: true,
    status: "healthy",
  },
  {
    id: "feed-npr-music",
    name: "NPR Music",
    url: "https://feeds.npr.org/1039/rss.xml",
    category: "social",
    website: "https://npr.org/music",
    tier: "tier1",
    enabled: true,
    status: "healthy",
  },
  {
    id: "feed-nme",
    name: "NME",
    url: "https://www.nme.com/music/feed",
    category: "marketing",
    website: "https://nme.com",
    tier: "tier1",
    enabled: true,
    status: "healthy",
  },
  {
    id: "feed-spin",
    name: "SPIN Magazine",
    url: "https://www.spin.com/feed/",
    category: "marketing",
    website: "https://spin.com",
    tier: "tier1",
    enabled: true,
    status: "healthy",
  },
  {
    id: "feed-guardian-music",
    name: "The Guardian Music",
    url: "https://www.theguardian.com/music/rss",
    category: "marketing",
    website: "https://theguardian.com/music",
    tier: "tier1",
    enabled: true,
    status: "healthy",
  },
  {
    id: "feed-bandcamp-daily",
    name: "Bandcamp Daily",
    url: "https://daily.bandcamp.com/feed",
    category: "social",
    website: "https://daily.bandcamp.com",
    tier: "tier1",
    enabled: true,
    status: "healthy",
  },
  {
    id: "feed-cdbaby-diy",
    name: "DIY Musician (CD Baby)",
    url: "https://diymusician.cdbaby.com/feed/",
    category: "tutorials",
    website: "https://diymusician.cdbaby.com",
    tier: "tier1",
    enabled: true,
    status: "healthy",
  },
  {
    id: "feed-hypebot",
    name: "Hypebot",
    url: "https://www.hypebot.com/feed/",
    category: "marketing",
    website: "https://hypebot.com",
    tier: "tier1",
    enabled: true,
    status: "healthy",
  },
  {
    id: "feed-musictech",
    name: "MusicTech",
    url: "https://musictech.com/feed/",
    category: "tech-ai",
    website: "https://musictech.com",
    tier: "tier1",
    enabled: true,
    status: "healthy",
  },
  {
    id: "feed-digitalmusicnews",
    name: "Digital Music News",
    url: "https://www.digitalmusicnews.com/feed/",
    category: "streaming",
    website: "https://digitalmusicnews.com",
    tier: "tier1",
    enabled: true,
    status: "healthy",
  },
  {
    id: "feed-musicrow",
    name: "MusicRow Magazine",
    url: "https://musicrow.com/feed/",
    category: "financial",
    website: "https://musicrow.com",
    tier: "tier1",
    enabled: true,
    status: "healthy",
  },

  // ============================================================================
  // TIER 2: GENRE-SPECIFIC SOURCES (40 feeds)
  // Hip-Hop, Electronic, Indie, Country, Latin, Rock, Pop, R&B
  // ============================================================================

  // Hip-Hop & R&B
  {
    id: "feed-hotnewhiphop",
    name: "HotNewHipHop",
    url: "https://www.hotnewhiphop.com/rss/news.xml",
    category: "streaming",
    website: "https://hotnewhiphop.com",
    tier: "tier2",
    enabled: true,
    status: "healthy",
  },
  {
    id: "feed-complex-music",
    name: "Complex Music",
    url: "https://www.complex.com/music/rss",
    category: "streaming",
    website: "https://complex.com/music",
    tier: "tier2",
    enabled: true,
    status: "healthy",
  },
  {
    id: "feed-xxl",
    name: "XXL Magazine",
    url: "https://www.xxlmag.com/feed/",
    category: "streaming",
    website: "https://xxlmag.com",
    tier: "tier2",
    enabled: true,
    status: "healthy",
  },
  {
    id: "feed-hypebeast-music",
    name: "Hypebeast Music",
    url: "https://hypebeast.com/feed",
    category: "streaming",
    website: "https://hypebeast.com/music",
    tier: "tier2",
    enabled: true,
    status: "healthy",
  },
  {
    id: "feed-rap-up",
    name: "Rap-Up",
    url: "https://www.rap-up.com/feed/",
    category: "streaming",
    website: "https://rap-up.com",
    tier: "tier2",
    enabled: true,
    status: "healthy",
  },
  {
    id: "feed-2dopeboyz",
    name: "2DopeBoyz",
    url: "https://2dopeboyz.com/feed/",
    category: "streaming",
    website: "https://2dopeboyz.com",
    tier: "tier2",
    enabled: true,
    status: "healthy",
  },
  {
    id: "feed-okayplayer",
    name: "Okayplayer",
    url: "https://www.okayplayer.com/feed",
    category: "social",
    website: "https://okayplayer.com",
    tier: "tier2",
    enabled: true,
    status: "healthy",
  },
  {
    id: "feed-thesource",
    name: "The Source",
    url: "https://thesource.com/feed/",
    category: "streaming",
    website: "https://thesource.com",
    tier: "tier2",
    enabled: true,
    status: "healthy",
  },

  // Electronic & Dance
  {
    id: "feed-resident-advisor",
    name: "Resident Advisor",
    url: "https://ra.co/xml/news.xml",
    category: "streaming",
    website: "https://ra.co",
    tier: "tier2",
    enabled: true,
    status: "healthy",
  },
  {
    id: "feed-mixmag",
    name: "Mixmag",
    url: "https://mixmag.net/feed",
    category: "streaming",
    website: "https://mixmag.net",
    tier: "tier2",
    enabled: true,
    status: "healthy",
  },
  {
    id: "feed-djmag",
    name: "DJ Mag",
    url: "https://djmag.com/feed",
    category: "streaming",
    website: "https://djmag.com",
    tier: "tier2",
    enabled: true,
    status: "healthy",
  },
  {
    id: "feed-edm",
    name: "EDM.com",
    url: "https://edm.com/feed/",
    category: "streaming",
    website: "https://edm.com",
    tier: "tier2",
    enabled: true,
    status: "healthy",
  },
  {
    id: "feed-dancing-astronaut",
    name: "Dancing Astronaut",
    url: "https://dancingastronaut.com/feed/",
    category: "streaming",
    website: "https://dancingastronaut.com",
    tier: "tier2",
    enabled: true,
    status: "healthy",
  },
  {
    id: "feed-youredm",
    name: "Your EDM",
    url: "https://www.youredm.com/feed/",
    category: "streaming",
    website: "https://youredm.com",
    tier: "tier2",
    enabled: true,
    status: "healthy",
  },
  {
    id: "feed-magnetic-mag",
    name: "Magnetic Magazine",
    url: "https://magneticmag.com/feed/",
    category: "streaming",
    website: "https://magneticmag.com",
    tier: "tier2",
    enabled: true,
    status: "healthy",
  },

  // Indie & Alternative
  {
    id: "feed-brooklynvegan",
    name: "Brooklyn Vegan",
    url: "https://www.brooklynvegan.com/feed/",
    category: "social",
    website: "https://brooklynvegan.com",
    tier: "tier2",
    enabled: true,
    status: "healthy",
  },
  {
    id: "feed-indieheads",
    name: "Paste Magazine Music",
    url: "https://www.pastemagazine.com/music/rss",
    category: "social",
    website: "https://pastemagazine.com/music",
    tier: "tier2",
    enabled: true,
    status: "healthy",
  },
  {
    id: "feed-exclaim",
    name: "Exclaim!",
    url: "https://exclaim.ca/music/rss",
    category: "social",
    website: "https://exclaim.ca",
    tier: "tier2",
    enabled: true,
    status: "healthy",
  },
  {
    id: "feed-quietus",
    name: "The Quietus",
    url: "https://thequietus.com/feed",
    category: "social",
    website: "https://thequietus.com",
    tier: "tier2",
    enabled: true,
    status: "healthy",
  },
  {
    id: "feed-line-of-best-fit",
    name: "The Line of Best Fit",
    url: "https://www.thelineofbestfit.com/feed",
    category: "social",
    website: "https://thelineofbestfit.com",
    tier: "tier2",
    enabled: true,
    status: "healthy",
  },
  {
    id: "feed-diy-magazine",
    name: "DIY Magazine",
    url: "https://diymag.com/rss",
    category: "social",
    website: "https://diymag.com",
    tier: "tier2",
    enabled: true,
    status: "healthy",
  },
  {
    id: "feed-clash",
    name: "Clash Magazine",
    url: "https://www.clashmusic.com/feed/",
    category: "social",
    website: "https://clashmusic.com",
    tier: "tier2",
    enabled: true,
    status: "healthy",
  },
  {
    id: "feed-under-radar",
    name: "Under the Radar",
    url: "https://www.undertheradarmag.com/feed",
    category: "social",
    website: "https://undertheradarmag.com",
    tier: "tier2",
    enabled: true,
    status: "healthy",
  },

  // Country & Americana
  {
    id: "feed-taste-of-country",
    name: "Taste of Country",
    url: "https://tasteofcountry.com/feed/",
    category: "streaming",
    website: "https://tasteofcountry.com",
    tier: "tier2",
    enabled: true,
    status: "healthy",
  },
  {
    id: "feed-the-boot",
    name: "The Boot",
    url: "https://theboot.com/feed/",
    category: "streaming",
    website: "https://theboot.com",
    tier: "tier2",
    enabled: true,
    status: "healthy",
  },
  {
    id: "feed-saving-country",
    name: "Saving Country Music",
    url: "https://www.savingcountrymusic.com/feed/",
    category: "social",
    website: "https://savingcountrymusic.com",
    tier: "tier2",
    enabled: true,
    status: "healthy",
  },
  {
    id: "feed-no-depression",
    name: "No Depression",
    url: "https://www.nodepression.com/feed/",
    category: "social",
    website: "https://nodepression.com",
    tier: "tier2",
    enabled: true,
    status: "healthy",
  },
  {
    id: "feed-americana-uk",
    name: "Americana UK",
    url: "https://americana-uk.com/feed",
    category: "social",
    website: "https://americana-uk.com",
    tier: "tier2",
    enabled: true,
    status: "healthy",
  },

  // Latin Music
  {
    id: "feed-billboard-latin",
    name: "Billboard Latin",
    url: "https://www.billboard.com/latin/feed/",
    category: "streaming",
    website: "https://billboard.com/latin",
    tier: "tier2",
    enabled: true,
    status: "healthy",
  },
  {
    id: "feed-remezcla",
    name: "Remezcla",
    url: "https://remezcla.com/feed/",
    category: "social",
    website: "https://remezcla.com",
    tier: "tier2",
    enabled: true,
    status: "healthy",
  },
  {
    id: "feed-alt-latino",
    name: "NPR Alt.Latino",
    url: "https://feeds.npr.org/510026/podcast.xml",
    category: "podcasts",
    website: "https://npr.org/sections/altlatino",
    tier: "tier2",
    enabled: true,
    status: "healthy",
  },

  // Rock & Metal
  {
    id: "feed-loudwire",
    name: "Loudwire",
    url: "https://loudwire.com/feed/",
    category: "streaming",
    website: "https://loudwire.com",
    tier: "tier2",
    enabled: true,
    status: "healthy",
  },
  {
    id: "feed-blabbermouth",
    name: "Blabbermouth",
    url: "https://www.blabbermouth.net/feed/",
    category: "streaming",
    website: "https://blabbermouth.net",
    tier: "tier2",
    enabled: true,
    status: "healthy",
  },
  {
    id: "feed-metal-injection",
    name: "Metal Injection",
    url: "https://metalinjection.net/feed",
    category: "streaming",
    website: "https://metalinjection.net",
    tier: "tier2",
    enabled: true,
    status: "healthy",
  },
  {
    id: "feed-metal-hammer",
    name: "Metal Hammer",
    url: "https://www.loudersound.com/metal-hammer/feed",
    category: "streaming",
    website: "https://loudersound.com/metal-hammer",
    tier: "tier2",
    enabled: true,
    status: "healthy",
  },
  {
    id: "feed-ultimate-guitar",
    name: "Ultimate Guitar News",
    url: "https://www.ultimate-guitar.com/news/rss.xml",
    category: "streaming",
    website: "https://ultimate-guitar.com",
    tier: "tier2",
    enabled: true,
    status: "healthy",
  },
  {
    id: "feed-kerrang",
    name: "Kerrang!",
    url: "https://www.kerrang.com/feed",
    category: "streaming",
    website: "https://kerrang.com",
    tier: "tier2",
    enabled: true,
    status: "healthy",
  },

  // Pop & Charts
  {
    id: "feed-popcrush",
    name: "PopCrush",
    url: "https://popcrush.com/feed/",
    category: "streaming",
    website: "https://popcrush.com",
    tier: "tier2",
    enabled: true,
    status: "healthy",
  },
  {
    id: "feed-idolator",
    name: "Idolator",
    url: "https://www.idolator.com/feed",
    category: "streaming",
    website: "https://idolator.com",
    tier: "tier2",
    enabled: true,
    status: "healthy",
  },
  {
    id: "feed-pop-justice",
    name: "Popjustice",
    url: "https://www.popjustice.com/feed/",
    category: "streaming",
    website: "https://popjustice.com",
    tier: "tier2",
    enabled: true,
    status: "healthy",
  },

  // ============================================================================
  // TIER 3: DISTRIBUTOR & INDUSTRY BLOGS (25 feeds)
  // Music business education, distribution platforms, rights organizations
  // ============================================================================

  {
    id: "feed-symphonic-blog",
    name: "Symphonic Distribution",
    url: "https://blog.symphonic.com/feed/",
    category: "tutorials",
    website: "https://blog.symphonic.com",
    tier: "tier3",
    enabled: true,
    status: "healthy",
  },
  {
    id: "feed-routenote",
    name: "RouteNote Distribution",
    url: "https://routenote.com/blog/feed/",
    category: "tutorials",
    website: "https://routenote.com",
    tier: "tier3",
    enabled: true,
    status: "healthy",
  },
  {
    id: "feed-distrokid-blog",
    name: "DistroKid Blog",
    url: "https://news.distrokid.com/feed",
    category: "tutorials",
    website: "https://news.distrokid.com",
    tier: "tier3",
    enabled: true,
    status: "healthy",
  },
  {
    id: "feed-tunecore-blog",
    name: "TuneCore Blog",
    url: "https://www.tunecore.com/blog/feed",
    category: "tutorials",
    website: "https://tunecore.com/blog",
    tier: "tier3",
    enabled: true,
    status: "healthy",
  },
  {
    id: "feed-amuse-blog",
    name: "Amuse.io Blog",
    url: "https://www.amuse.io/blog/feed/",
    category: "tutorials",
    website: "https://amuse.io/blog",
    tier: "tier3",
    enabled: true,
    status: "healthy",
  },
  {
    id: "feed-landr-blog",
    name: "LANDR Blog",
    url: "https://blog.landr.com/feed/",
    category: "tech-ai",
    website: "https://blog.landr.com",
    tier: "tier3",
    enabled: true,
    status: "healthy",
  },
  {
    id: "feed-splice-blog",
    name: "Splice Blog",
    url: "https://splice.com/blog/feed/",
    category: "tech-ai",
    website: "https://splice.com/blog",
    tier: "tier3",
    enabled: true,
    status: "healthy",
  },
  {
    id: "feed-songtrust",
    name: "Songtrust Blog",
    url: "https://blog.songtrust.com/rss.xml",
    category: "financial",
    website: "https://blog.songtrust.com",
    tier: "tier3",
    enabled: true,
    status: "healthy",
  },
  {
    id: "feed-soundcharts",
    name: "Soundcharts Blog",
    url: "https://soundcharts.com/blog/feed",
    category: "tutorials",
    website: "https://soundcharts.com/blog",
    tier: "tier3",
    enabled: true,
    status: "healthy",
  },
  {
    id: "feed-chartmetric",
    name: "Chartmetric Blog",
    url: "https://blog.chartmetric.com/feed/",
    category: "streaming",
    website: "https://blog.chartmetric.com",
    tier: "tier3",
    enabled: true,
    status: "healthy",
  },
  {
    id: "feed-a2im",
    name: "A2IM Independent Music News",
    url: "https://a2im.org/feed/",
    category: "legal",
    website: "https://a2im.org",
    tier: "tier3",
    enabled: true,
    status: "healthy",
  },
  {
    id: "feed-riaa",
    name: "RIAA News",
    url: "https://www.riaa.com/feed/",
    category: "legal",
    website: "https://riaa.com",
    tier: "tier3",
    enabled: true,
    status: "healthy",
  },
  {
    id: "feed-ifpi",
    name: "IFPI News",
    url: "https://www.ifpi.org/feed/",
    category: "legal",
    website: "https://ifpi.org",
    tier: "tier3",
    enabled: true,
    status: "healthy",
  },
  {
    id: "feed-nmpa",
    name: "NMPA News",
    url: "https://www.nmpa.org/feed/",
    category: "legal",
    website: "https://nmpa.org",
    tier: "tier3",
    enabled: true,
    status: "healthy",
  },
  {
    id: "feed-sos",
    name: "Sound on Sound",
    url: "https://www.soundonsound.com/feed/all",
    category: "tech-ai",
    website: "https://soundonsound.com",
    tier: "tier3",
    enabled: true,
    status: "healthy",
  },
  {
    id: "feed-gearslutz",
    name: "Gearspace",
    url: "https://gearspace.com/board/external.php?type=RSS2",
    category: "tech-ai",
    website: "https://gearspace.com",
    tier: "tier3",
    enabled: true,
    status: "healthy",
  },
  {
    id: "feed-recording-revolution",
    name: "Recording Revolution",
    url: "https://www.recordingrevolution.com/feed/",
    category: "tutorials",
    website: "https://recordingrevolution.com",
    tier: "tier3",
    enabled: true,
    status: "healthy",
  },
  {
    id: "feed-audio-mentor",
    name: "Pro Audio Files",
    url: "https://theproaudiofiles.com/feed/",
    category: "tutorials",
    website: "https://theproaudiofiles.com",
    tier: "tier3",
    enabled: true,
    status: "healthy",
  },
  {
    id: "feed-produce-like-pro",
    name: "Produce Like A Pro",
    url: "https://producelikeapro.com/feed/",
    category: "tutorials",
    website: "https://producelikeapro.com",
    tier: "tier3",
    enabled: true,
    status: "healthy",
  },
  {
    id: "feed-tape-op",
    name: "Tape Op Magazine",
    url: "https://tapeop.com/feed/",
    category: "social",
    website: "https://tapeop.com",
    tier: "tier3",
    enabled: true,
    status: "healthy",
  },
  {
    id: "feed-music-ally",
    name: "Music Ally",
    url: "https://musically.com/feed/",
    category: "tech-ai",
    website: "https://musically.com",
    tier: "tier3",
    enabled: true,
    status: "healthy",
  },
  {
    id: "feed-water-music",
    name: "Water & Music",
    url: "https://www.waterandmusic.com/feed/",
    category: "tech-ai",
    website: "https://waterandmusic.com",
    tier: "tier3",
    enabled: true,
    status: "healthy",
  },
  {
    id: "feed-music-radar",
    name: "MusicRadar",
    url: "https://www.musicradar.com/feeds/news",
    category: "tech-ai",
    website: "https://musicradar.com",
    tier: "tier3",
    enabled: true,
    status: "healthy",
  },
  {
    id: "feed-future-music",
    name: "Future Music",
    url: "https://www.musicradar.com/future-music/feed",
    category: "tech-ai",
    website: "https://musicradar.com/future-music",
    tier: "tier3",
    enabled: true,
    status: "healthy",
  },
  {
    id: "feed-attack-magazine",
    name: "Attack Magazine",
    url: "https://www.attackmagazine.com/feed/",
    category: "tech-ai",
    website: "https://attackmagazine.com",
    tier: "tier3",
    enabled: true,
    status: "healthy",
  },

  // ============================================================================
  // TIER 4: PODCASTS & INTERVIEWS (15 feeds)
  // Industry podcasts with artist interviews and business insights
  // ============================================================================

  {
    id: "feed-trapital",
    name: "Trapital Podcast",
    url: "https://feeds.simplecast.com/MrsYBgPz",
    category: "podcasts",
    website: "https://trapital.co",
    tier: "tier3",
    enabled: true,
    status: "healthy",
  },
  {
    id: "feed-switched-on-pop",
    name: "Switched on Pop",
    url: "https://feeds.megaphone.fm/switchedonpop",
    category: "podcasts",
    website: "https://switchedonpop.com",
    tier: "tier3",
    enabled: true,
    status: "healthy",
  },
  {
    id: "feed-song-exploder",
    name: "Song Exploder",
    url: "https://feed.songexploder.net/SongExploder",
    category: "podcasts",
    website: "https://songexploder.net",
    tier: "tier3",
    enabled: true,
    status: "healthy",
  },
  {
    id: "feed-broken-record",
    name: "Broken Record",
    url: "https://feeds.simplecast.com/dHoohVNH",
    category: "podcasts",
    website: "https://brokenrecordpodcast.com",
    tier: "tier3",
    enabled: true,
    status: "healthy",
  },
  {
    id: "feed-dissect",
    name: "Dissect Podcast",
    url: "https://feeds.simplecast.com/eLNpYg5f",
    category: "podcasts",
    website: "https://dissectpodcast.com",
    tier: "tier3",
    enabled: true,
    status: "healthy",
  },
  {
    id: "feed-music-business-hq",
    name: "Music Industry Podcast",
    url: "https://anchor.fm/s/1c5f5c88/podcast/rss",
    category: "podcasts",
    website: "https://musicindustrypodcast.com",
    tier: "tier3",
    enabled: true,
    status: "healthy",
  },
  {
    id: "feed-music-biz-weekly",
    name: "Music Biz Weekly",
    url: "https://feeds.simplecast.com/xuV6FHOL",
    category: "podcasts",
    website: "https://musicbizweekly.com",
    tier: "tier3",
    enabled: true,
    status: "healthy",
  },
  {
    id: "feed-and-the-writer-is",
    name: "And the Writer Is...",
    url: "https://rss.art19.com/and-the-writer-is",
    category: "podcasts",
    website: "https://ascap.com/andthewriteris",
    tier: "tier3",
    enabled: true,
    status: "healthy",
  },
  {
    id: "feed-all-songs-considered",
    name: "All Songs Considered",
    url: "https://feeds.npr.org/510019/podcast.xml",
    category: "podcasts",
    website: "https://npr.org/allsongs",
    tier: "tier3",
    enabled: true,
    status: "healthy",
  },
  {
    id: "feed-tiny-desk",
    name: "Tiny Desk Concerts",
    url: "https://feeds.npr.org/510306/podcast.xml",
    category: "social",
    website: "https://npr.org/tinydesk",
    tier: "tier3",
    enabled: true,
    status: "healthy",
  },

  // ============================================================================
  // SOCIAL MEDIA FEEDS (via RSS bridges/services)
  // X (Twitter), Instagram, TikTok hashtag monitoring
  // ============================================================================

  // Note: Direct social media RSS is limited. These use public RSS bridges
  // or official RSS where available. Consider adding Nitter mirrors for X.

  {
    id: "feed-reddit-wearethemusicmakers",
    name: "Reddit: WeAreTheMusicMakers",
    url: "https://www.reddit.com/r/WeAreTheMusicMakers/.rss",
    category: "social",
    website: "https://reddit.com/r/WeAreTheMusicMakers",
    tier: "tier3",
    enabled: true,
    status: "healthy",
  },
  {
    id: "feed-reddit-musicindustry",
    name: "Reddit: Music Industry",
    url: "https://www.reddit.com/r/MusicIndustry/.rss",
    category: "social",
    website: "https://reddit.com/r/MusicIndustry",
    tier: "tier3",
    enabled: true,
    status: "healthy",
  },
  {
    id: "feed-reddit-indieheads",
    name: "Reddit: IndieHeads",
    url: "https://www.reddit.com/r/indieheads/.rss",
    category: "social",
    website: "https://reddit.com/r/indieheads",
    tier: "tier3",
    enabled: true,
    status: "healthy",
  },
  {
    id: "feed-reddit-hiphopheads",
    name: "Reddit: HipHopHeads",
    url: "https://www.reddit.com/r/hiphopheads/.rss",
    category: "social",
    website: "https://reddit.com/r/hiphopheads",
    tier: "tier3",
    enabled: true,
    status: "healthy",
  },
  {
    id: "feed-reddit-edmproduction",
    name: "Reddit: EDM Production",
    url: "https://www.reddit.com/r/edmproduction/.rss",
    category: "social",
    website: "https://reddit.com/r/edmproduction",
    tier: "tier3",
    enabled: true,
    status: "healthy",
  },
  {
    id: "feed-hn-music",
    name: "Hacker News: Music",
    url: "https://hnrss.org/newest?q=music+industry",
    category: "tech-ai",
    website: "https://news.ycombinator.com",
    tier: "tier3",
    enabled: true,
    status: "healthy",
  },

  // ============================================================================
  // OPPORTUNITIES & GRANTS (5 feeds)
  // Submission opportunities, grants, showcases
  // ============================================================================

  {
    id: "feed-submithub-blog",
    name: "SubmitHub Blog",
    url: "https://www.submithub.com/blog/feed",
    category: "opportunities",
    website: "https://submithub.com/blog",
    tier: "tier3",
    enabled: true,
    status: "healthy",
  },
  {
    id: "feed-music-grants",
    name: "Music Grants & Funding",
    url: "https://www.musicianguide.com/feed/",
    category: "opportunities",
    website: "https://musicianguide.com",
    tier: "tier3",
    enabled: true,
    status: "healthy",
  },
  {
    id: "feed-sonicbids",
    name: "Sonicbids Blog",
    url: "https://blog.sonicbids.com/rss.xml",
    category: "opportunities",
    website: "https://blog.sonicbids.com",
    tier: "tier3",
    enabled: true,
    status: "healthy",
  },
];

export const SPONSORSHIP_PACKAGES: SponsorshipPackage[] = [
  {
    id: "newsletter-banner",
    name: "Daily Newsletter Primary Sponsor",
    priceFormatted: "$149",
    priceCents: 14900,
    period: "one-time",
    description: "Top-of-fold featured placement in the Artist Daily News morning intelligence email blast sent to 35,000+ verified musicians & managers.",
    features: [
      "Top Hero Banner (600x150) with tracking link",
      "75-word sponsor shoutout & CTA copy",
      "42%+ average industry open rate",
      "Full performance click-through report",
    ],
  },
  {
    id: "artist-spotlight",
    name: "Sponsored Artist / Brand Feature",
    priceFormatted: "$299",
    priceCents: 29900,
    period: "one-time",
    highlight: true,
    description: "Dedicated editorial feature article published on ArtistDailyNews.com homepage, syndicated across RSS, and blasted to our newsletter.",
    features: [
      "Permanent feature article on ADN with high-authority dofollow link",
      "Pinned to Homepage Trending Showcase for 7 days",
      "Featured segment in Daily Email Dispatch",
      "Social amplification to 45,000+ music industry network",
      "Press release pickup index on Google News",
    ],
  },
  {
    id: "site-takeover",
    name: "Monthly Homepage Takeover & Retargeting",
    priceFormatted: "$799",
    priceCents: 79900,
    period: "monthly",
    description: "Maximum category dominance for music tech SaaS, distributors, plugins, hardware gear, or enterprise labels.",
    features: [
      "Exclusive Header Leaderboard & Sticky Sidebar display unit",
      "4 Weekly Newsletter Primary Sponsor slots included",
      "2 Dedicated Featured Spotlight articles per month",
      "Direct conversion pixel & custom UTM attribution tracking",
      "Guaranteed 150,000+ monthly impressions",
    ],
  },
];
