import { CategoryInfo, FeedSource, SponsorshipPackage } from "./types";

export const CATEGORIES: CategoryInfo[] = [
  {
    id: "financial",
    name: "Royalties & Catalogues",
    slug: "financial",
    icon: "BadgeDollarSign",
    color: "#10B981",
    description: "Publishing rights, catalogue sales benchmarks, streaming payouts, sync licenses, and artist equity.",
  },
  {
    id: "streaming",
    name: "Streaming & Playlists",
    slug: "streaming",
    icon: "Radio",
    color: "#3B82F6",
    description: "Spotify algorithm updates, Apple Music discovery, editorial playlist strategies, and DSP threshold policy.",
  },
  {
    id: "tech-ai",
    name: "AI & Music Tech",
    slug: "tech-ai",
    icon: "Cpu",
    color: "#8B5CF6",
    description: "Generative audio tools, stem separation, AI mastering, blockchain metadata, and creator software.",
  },
  {
    id: "marketing",
    name: "TikTok & Viral Growth",
    slug: "marketing",
    icon: "TrendingUp",
    color: "#EC4899",
    description: "Short-form video strategies, influencer sound seeding, pre-save campaigns, and grassroots fan engagement.",
  },
  {
    id: "legal",
    name: "Legal & Copyright",
    slug: "legal",
    icon: "Scale",
    color: "#F59E0B",
    description: "Sampling rights, 360 deals vs distribution splits, copyright enforcement, and trademark defense.",
  },
  {
    id: "podcasts",
    name: "Podcasts & Interviews",
    slug: "podcasts",
    icon: "Headphones",
    color: "#06B6D4",
    description: "Deep conversations with A&Rs, music attorneys, independent moguls, and chart-topping producers.",
  },
  {
    id: "tutorials",
    name: "DIY Masterclasses",
    slug: "tutorials",
    icon: "GraduationCap",
    color: "#14B8A6",
    description: "Step-by-step guides on release schedules, Meta ad funnels, pitch decks, and home studio acoustics.",
  },
  {
    id: "opportunities",
    name: "Press Passes & Grants",
    slug: "opportunities",
    icon: "Ticket",
    color: "#D4FF00",
    description: "Open artist grants, festival showcase submissions, media accreditation, and sync licensing briefs.",
  },
];

export const INITIAL_FEEDS: FeedSource[] = [
  // Financial & Publishing
  {
    id: "feed-mbw",
    name: "Music Business Worldwide",
    url: "https://www.musicbusinessworldwide.com/feed/",
    category: "financial",
    website: "https://musicbusinessworldwide.com",
    tier: "tier1",
    enabled: true,
    status: "healthy",
  },
  {
    id: "feed-billboard-biz",
    name: "Billboard Pro",
    url: "https://www.billboard.com/c/business/feed/",
    category: "financial",
    website: "https://billboard.com/business",
    tier: "tier1",
    enabled: true,
    status: "healthy",
  },
  {
    id: "feed-musicrow",
    name: "MusicRow Magazine",
    url: "https://musicrow.com/feed/",
    category: "financial",
    website: "https://musicrow.com",
    tier: "tier2",
    enabled: true,
    status: "healthy",
  },

  // Streaming & Playlists
  {
    id: "feed-digitalmusicnews",
    name: "Digital Music News",
    url: "https://www.digitalmusicnews.com/feed/",
    category: "streaming",
    website: "https://digitalmusicnews.com",
    tier: "tier1",
    enabled: true,
    status: "healthy",
  },
  {
    id: "feed-routenote",
    name: "RouteNote Distribution",
    url: "https://routenote.com/blog/feed/",
    category: "streaming",
    website: "https://routenote.com",
    tier: "tier2",
    enabled: true,
    status: "healthy",
  },
  {
    id: "feed-stereogum",
    name: "Stereogum",
    url: "https://www.stereogum.com/feed/",
    category: "streaming",
    website: "https://stereogum.com",
    tier: "tier1",
    enabled: true,
    status: "healthy",
  },

  // AI & Music Tech
  {
    id: "feed-music-ally",
    name: "Music Ally",
    url: "https://musically.com/feed/",
    category: "tech-ai",
    website: "https://musically.com",
    tier: "tier1",
    enabled: true,
    status: "healthy",
  },
  {
    id: "feed-musictech",
    name: "MusicTech",
    url: "https://musictech.com/feed/",
    category: "tech-ai",
    website: "https://musictech.com",
    tier: "tier1",
    enabled: true,
    status: "healthy",
  },

  // Marketing & Growth
  {
    id: "feed-cdbaby-diy",
    name: "DIY Musician (CD Baby)",
    url: "https://diymusician.cdbaby.com/feed/",
    category: "marketing",
    website: "https://diymusician.cdbaby.com",
    tier: "tier1",
    enabled: true,
    status: "healthy",
  },
  {
    id: "feed-symphonic-blog",
    name: "Symphonic Distribution",
    url: "https://blog.symphonic.com/feed/",
    category: "marketing",
    website: "https://blog.symphonic.com",
    tier: "tier2",
    enabled: true,
    status: "healthy",
  },
  {
    id: "feed-bandcamp-daily",
    name: "Bandcamp Daily",
    url: "https://daily.bandcamp.com/feed",
    category: "marketing",
    website: "https://daily.bandcamp.com",
    tier: "tier1",
    enabled: true,
    status: "healthy",
  },
  {
    id: "feed-pitchfork",
    name: "Pitchfork News",
    url: "https://pitchfork.com/feed/feed-news/rss",
    category: "marketing",
    website: "https://pitchfork.com",
    tier: "tier1",
    enabled: true,
    status: "healthy",
  },
  {
    id: "feed-rollingstone",
    name: "Rolling Stone Music",
    url: "https://www.rollingstone.com/music/music-news/feed/",
    category: "marketing",
    website: "https://rollingstone.com",
    tier: "tier1",
    enabled: true,
    status: "healthy",
  },
  {
    id: "feed-thefader",
    name: "The FADER",
    url: "https://www.thefader.com/feed",
    category: "marketing",
    website: "https://thefader.com",
    tier: "tier1",
    enabled: true,
    status: "healthy",
  },
  {
    id: "feed-consequence",
    name: "Consequence of Sound",
    url: "https://consequence.net/feed/",
    category: "marketing",
    website: "https://consequence.net",
    tier: "tier1",
    enabled: true,
    status: "healthy",
  },

  // Legal & Rights
  {
    id: "feed-a2im",
    name: "A2IM Independent Music News",
    url: "https://a2im.org/feed/",
    category: "legal",
    website: "https://a2im.org",
    tier: "tier2",
    enabled: true,
    status: "healthy",
  },

  // Tutorials & Masterclasses
  {
    id: "feed-diymusician-guides",
    name: "DIY Musician Guides",
    url: "https://diymusician.cdbaby.com/feed/",
    category: "tutorials",
    website: "https://diymusician.cdbaby.com",
    tier: "tier1",
    enabled: true,
    status: "healthy",
  },

  // Opportunities & Grants
  {
    id: "feed-bandcamp-spotlight",
    name: "Bandcamp Artist Spotlights",
    url: "https://daily.bandcamp.com/feed",
    category: "opportunities",
    website: "https://daily.bandcamp.com",
    tier: "tier1",
    enabled: true,
    status: "healthy",
  },
];

export const SPONSORSHIP_PACKAGES: SponsorshipPackage[] = [
  {
    id: "newsletter-banner",
    name: "Daily Newsletter Primary Sponsor",
    priceFormatted: "$149",
    priceCents: 14900,
    period: "one-time",
    description: "Top-of-fold featured placement in the Artist Daily News morning intelligence email blast sent to 35,000+ verified musicians & managers.",
    features: [
      "Top Hero Banner (600x150) with tracking link",
      "75-word sponsor shoutout & CTA copy",
      "42%+ average industry open rate",
      "Full performance click-through report",
    ],
  },
  {
    id: "artist-spotlight",
    name: "Sponsored Artist / Brand Feature",
    priceFormatted: "$299",
    priceCents: 29900,
    period: "one-time",
    highlight: true,
    description: "Dedicated editorial feature article published on ArtistDailyNews.com homepage, syndicated across RSS, and blasted to our newsletter.",
    features: [
      "Permanent feature article on ADN with high-authority dofollow link",
      "Pinned to Homepage Trending Showcase for 7 days",
      "Featured segment in Daily Email Dispatch",
      "Social amplification to 45,000+ music industry network",
      "Press release pickup index on Google News",
    ],
  },
  {
    id: "site-takeover",
    name: "Monthly Homepage Takeover & Retargeting",
    priceFormatted: "$799",
    priceCents: 79900,
    period: "monthly",
    description: "Maximum category dominance for music tech SaaS, distributors, plugins, hardware gear, or enterprise labels.",
    features: [
      "Exclusive Header Leaderboard & Sticky Sidebar display unit",
      "4 Weekly Newsletter Primary Sponsor slots included",
      "2 Dedicated Featured Spotlight articles per month",
      "Direct conversion pixel & custom UTM attribution tracking",
      "Guaranteed 150,000+ monthly impressions",
    ],
  },
];
