import { ChannelResource } from "./types";

export const CURATED_MEDIA_CHANNELS: ChannelResource[] = [
  // ── 1. Business & A&R ──
  {
    id: "trapital",
    name: "Trapital",
    handle: "@Trapital",
    category: "Business & A&R",
    subscribers: "125K+",
    description: "Deep business essays on hip-hop, creator economies, DSP monetization, and music business executives.",
    youtubeUrl: "https://www.youtube.com/@Trapital",
    websiteUrl: "https://trapital.co",
    rssFeedUrl: "https://trapital.co/feed/",
    featuredTopic: "Independent Artist Business Models",
  },
  {
    id: "mbw-video",
    name: "Music Business Worldwide",
    handle: "@MusicBusinessWorldwide",
    category: "Business & A&R",
    subscribers: "90K+",
    description: "Global record label market share, publishing rights acquisitions, streaming payouts, and executive interviews.",
    youtubeUrl: "https://www.youtube.com/@MusicBusinessWorldwide",
    websiteUrl: "https://musicbusinessworldwide.com",
    rssFeedUrl: "https://musicbusinessworldwide.com/feed/",
    featuredTopic: "Global Music Industry Finance & Rights",
  },
  {
    id: "billboard-pro",
    name: "Billboard Pro & News",
    handle: "@Billboard",
    category: "Business & A&R",
    subscribers: "4.8M+",
    description: "The music industry's benchmark for Hot 100 chart data, touring grosses, and major record deals.",
    youtubeUrl: "https://www.youtube.com/@Billboard",
    websiteUrl: "https://billboard.com/business",
    rssFeedUrl: "https://billboard.com/feed/",
    featuredTopic: "Chart Analytics & Touring Revenue",
  },
  {
    id: "damien-keyes",
    name: "Damien Keyes",
    handle: "@DamienKeyes",
    category: "Business & A&R",
    subscribers: "210K+",
    description: "Actionable DIY artist strategies, release schedules, direct-to-fan sales funnels, and tour booking.",
    youtubeUrl: "https://www.youtube.com/@DamienKeyes",
    websiteUrl: "https://damienkeyes.com",
    featuredTopic: "Modern Music Release Playbooks",
  },
  {
    id: "aris-take",
    name: "Ari's Take",
    handle: "@ArisTake",
    category: "Business & A&R",
    subscribers: "115K+",
    description: "Independent music management advice, distributor comparisons, sync licensing, and copyright fundamentals.",
    youtubeUrl: "https://www.youtube.com/@ArisTake",
    websiteUrl: "https://aristake.com",
    rssFeedUrl: "https://aristake.com/feed/",
    featuredTopic: "DIY Touring & Distributor Audits",
  },
  {
    id: "producergrind",
    name: "Producergrind",
    handle: "@Producergrind",
    category: "Business & A&R",
    subscribers: "480K+",
    description: "Interviews with chart-topping beatmakers on placement contracts, publishing splits, and beat sales businesses.",
    youtubeUrl: "https://www.youtube.com/@Producergrind",
    websiteUrl: "https://producergrind.com",
    rssFeedUrl: "https://producergrind.com/feed/",
    featuredTopic: "Beat Licensing & Producer Split Sheets",
  },

  // ── 2. Production, Mixing & Sound Design ──
  {
    id: "rick-beato",
    name: "Rick Beato (Everything Music)",
    handle: "@RickBeato",
    category: "Production & Mixing",
    subscribers: "4.2M+",
    description: "Ear training, harmonic analysis, what makes classic and modern songs great, and audio production mastery.",
    youtubeUrl: "https://www.youtube.com/@RickBeato",
    websiteUrl: "https://rickbeato.com",
    featuredTopic: "Song Breakdown & Production Architecture",
  },
  {
    id: "sound-on-sound",
    name: "Sound On Sound Video",
    handle: "@SoundOnSound",
    category: "Production & Mixing",
    subscribers: "380K+",
    description: "World-renowned audio recording, mixing acoustics, microphone shootouts, and DAW engineering tutorials.",
    youtubeUrl: "https://www.youtube.com/@SoundOnSound",
    websiteUrl: "https://soundonsound.com",
    rssFeedUrl: "https://soundonsound.com/news/feed",
    featuredTopic: "Vocal Compression & Bus Processing",
  },
  {
    id: "pensados-place",
    name: "Pensado's Place",
    handle: "@PensadosPlace",
    category: "Production & Mixing",
    subscribers: "360K+",
    description: "Grammy-winning mixing engineer Dave Pensado and Herb Trawick interview top producers and demonstrate mix techniques.",
    youtubeUrl: "https://www.youtube.com/@PensadosPlace",
    websiteUrl: "https://pensadosplace.tv",
    featuredTopic: "Pro Vocal Mixing Chains & Saturation",
  },
  {
    id: "in-the-mix",
    name: "In The Mix",
    handle: "@InTheMix",
    category: "Production & Mixing",
    subscribers: "1.4M+",
    description: "Clean, comprehensive mixing masterclasses covering EQ, compression, reverb, mastering, and studio setup.",
    youtubeUrl: "https://www.youtube.com/@InTheMix",
    websiteUrl: "https://inthemix.co.uk",
    featuredTopic: "Mastering for DSP Streaming Standards",
  },
  {
    id: "mix-with-the-masters",
    name: "Mix With The Masters",
    handle: "@MixWithTheMasters",
    category: "Production & Mixing",
    subscribers: "520K+",
    description: "Exclusive studio deconstructions from legends like Serban Ghenea, Chris Lord-Alge, and Finneas.",
    youtubeUrl: "https://www.youtube.com/@MixWithTheMasters",
    websiteUrl: "https://mixwiththemasters.com",
    featuredTopic: "Multi-Track Session Deconstruction",
  },
  {
    id: "sonicscoop",
    name: "SonicScoop",
    handle: "@SonicScoop",
    category: "Production & Mixing",
    subscribers: "240K+",
    description: "Justin Colletti dives deep into low-end mixing, dynamic range, monitoring, and studio acoustics.",
    youtubeUrl: "https://www.youtube.com/@SonicScoop",
    websiteUrl: "https://sonicscoop.com",
    rssFeedUrl: "https://sonicscoop.com/feed/",
    featuredTopic: "Low-End & Sub-Bass Phase Alignment",
  },
  {
    id: "spitfire-audio",
    name: "Spitfire Audio",
    handle: "@SpitfireAudio",
    category: "Production & Mixing",
    subscribers: "650K+",
    description: "Cinematic orchestral scoring, virtual instruments, Foley synthesis, and modern film music composition.",
    youtubeUrl: "https://www.youtube.com/@SpitfireAudio",
    websiteUrl: "https://spitfireaudio.com",
    rssFeedUrl: "https://spitfireaudio.com/feed/",
    featuredTopic: "Orchestral Scoring & Dynamic Layering",
  },

  // ── 3. Marketing, Algorithms & Growth ──
  {
    id: "burstimo",
    name: "Burstimo",
    handle: "@Burstimo",
    category: "Marketing & Growth",
    subscribers: "190K+",
    description: "Spotify editorial pitching strategies, Release Radar algorithmic triggers, and TikTok conversion campaigns.",
    youtubeUrl: "https://www.youtube.com/@Burstimo",
    websiteUrl: "https://burstimo.com",
    featuredTopic: "Spotify Algorithm Triggers & Pre-Saves",
  },
  {
    id: "berklee-online",
    name: "Berklee Online",
    handle: "@BerkleeOnline",
    category: "Marketing & Growth",
    subscribers: "740K+",
    description: "Collegiate-grade music marketing, music theory, arrangement, synthesis, and music licensing masterclasses.",
    youtubeUrl: "https://www.youtube.com/@BerkleeOnline",
    websiteUrl: "https://online.berklee.edu",
    featuredTopic: "Music Licensing & Sync Placement Guide",
  },
  {
    id: "andrew-southworth",
    name: "Andrew Southworth",
    handle: "@AndrewSouthworth",
    category: "Marketing & Growth",
    subscribers: "170K+",
    description: "Data-driven Meta Ads for musicians, Spotify playlist conversion tracking, and Spotify Canvas optimization.",
    youtubeUrl: "https://www.youtube.com/@AndrewSouthworth",
    websiteUrl: "https://andrewsouthworth.com",
    featuredTopic: "Meta Conversion Ads for Spotify Growth",
  },
  {
    id: "brandman-sean",
    name: "BrandMan Sean",
    handle: "@BrandManNetwork",
    category: "Marketing & Growth",
    subscribers: "320K+",
    description: "Music marketing case studies breaking down how viral artists break through the noise and scale loyal fanbases.",
    youtubeUrl: "https://www.youtube.com/@BrandManNetwork",
    websiteUrl: "https://brandman.network",
    featuredTopic: "Artist Identity & Narrative Building",
  },
  {
    id: "jesse-cannon",
    name: "Jesse Cannon (Musformation)",
    handle: "@JesseCannon",
    category: "Marketing & Growth",
    subscribers: "150K+",
    description: "Author of 'Get More Fans' shares real-world marketing playbooks, short-form content cadence, and fan retention.",
    youtubeUrl: "https://www.youtube.com/@JesseCannon",
    websiteUrl: "https://musformation.com",
    featuredTopic: "Converting Casual Listeners into Superfans",
  },

  // ── 4. Culture, Documentaries & Live ──
  {
    id: "rbma",
    name: "Red Bull Music Academy",
    handle: "@RedBullMusicAcademy",
    category: "Culture & Documentaries",
    subscribers: "980K+",
    description: "Legendary studio lectures, electronic music origins, sampling history, and in-depth cultural documentaries.",
    youtubeUrl: "https://www.youtube.com/@RedBullMusicAcademy",
    websiteUrl: "https://redbullmusicacademy.com",
    featuredTopic: "Pioneering Producers & History of Beats",
  },
  {
    id: "dj-mag",
    name: "DJ Mag",
    handle: "@DJMag",
    category: "Culture & Documentaries",
    subscribers: "1.2M+",
    description: "Underground club culture, sound system origins, live festival broadcasts, and electronic artist features.",
    youtubeUrl: "https://www.youtube.com/@DJMag",
    websiteUrl: "https://djmag.com",
    rssFeedUrl: "https://djmag.com/rss.xml",
    featuredTopic: "Sound System Culture & Club History",
  },
  {
    id: "npr-music",
    name: "NPR Music (Tiny Desk)",
    handle: "@NPRMusic",
    category: "Culture & Documentaries",
    subscribers: "9.1M+",
    description: "Iconic intimate live performances, genre-defining music journalism, and independent artist discoveries.",
    youtubeUrl: "https://www.youtube.com/@NPRMusic",
    websiteUrl: "https://npr.org/music",
    rssFeedUrl: "https://feeds.npr.org/1039/rss.xml",
    featuredTopic: "Acoustic Live Audio Performance",
  },
  {
    id: "kexp",
    name: "KEXP Live Sessions",
    handle: "@KEXP",
    category: "Culture & Documentaries",
    subscribers: "3.5M+",
    description: "Independent radio powerhouse delivering pristine multi-track live recordings of world music and indie artists.",
    youtubeUrl: "https://www.youtube.com/@KEXP",
    websiteUrl: "https://kexp.org",
    rssFeedUrl: "https://kexp.org/feed/",
    featuredTopic: "Live Sound Engineering & Indie Curation",
  },
  {
    id: "pitchfork-media",
    name: "Pitchfork",
    handle: "@Pitchfork",
    category: "Culture & Documentaries",
    subscribers: "1.3M+",
    description: "Critical video essays, artist interviews (Over/Under), album reviews, and cultural journalism.",
    youtubeUrl: "https://www.youtube.com/@Pitchfork",
    websiteUrl: "https://pitchfork.com",
    rssFeedUrl: "https://pitchfork.com/feed/feed-news/rss",
    featuredTopic: "Music Criticism & Cultural Trends",
  },

  // ── 5. Gear, Tech, DAWs & Beatmaking ──
  {
    id: "andrew-huang",
    name: "Andrew Huang",
    handle: "@AndrewHuang",
    category: "Gear & Tech",
    subscribers: "2.4M+",
    description: "Innovative music production challenges, synthesizer deep-dives, sound design experiments, and gear reviews.",
    youtubeUrl: "https://www.youtube.com/@AndrewHuang",
    websiteUrl: "https://andrewhuang.com",
    featuredTopic: "Creative Sound Design & Fast Workflows",
  },
  {
    id: "landr-music",
    name: "LANDR Audio",
    handle: "@LANDRMusic",
    category: "Gear & Tech",
    subscribers: "310K+",
    description: "Audio mastering tutorials, VST plugin rundowns, music distribution setup, and stem mastering guides.",
    youtubeUrl: "https://www.youtube.com/@LANDRMusic",
    websiteUrl: "https://landr.com",
    rssFeedUrl: "https://blog.landr.com/feed/",
    featuredTopic: "Mastering Fundamentals & Release Checklist",
  },
  {
    id: "native-instruments",
    name: "Native Instruments",
    handle: "@NativeInstruments",
    category: "Gear & Tech",
    subscribers: "710K+",
    description: "Maschine groovebox beatmaking, Kontakt sampling engines, Komplete synthesizers, and Traktor DJ workflows.",
    youtubeUrl: "https://www.youtube.com/@NativeInstruments",
    websiteUrl: "https://native-instruments.com",
    featuredTopic: "Sampler Workflows & Hardware Control",
  },
  {
    id: "venus-theory",
    name: "Venus Theory",
    handle: "@VenusTheory",
    category: "Gear & Tech",
    subscribers: "390K+",
    description: "Ambient synthesis, synth patch architecture, dystopian sound design, and honest talks on being an artist.",
    youtubeUrl: "https://www.youtube.com/@VenusTheory",
    websiteUrl: "https://venustheory.com",
    featuredTopic: "Wavetable Synthesis & Atmospheric Sound",
  },
];
