import { Article, PodcastEpisode, VideoItem } from "./types";

export const MOCK_ARTICLES: Article[] = [
  // 1. Cover / Featured
  {
    id: "art-01",
    title: "Spotify Announces 2026 Distribution Tier Overhaul: What Independent Creators Must Know",
    slug: "spotify-2026-distribution-tier-overhaul-indie-creators",
    summary: "The streaming giant is updating distribution thresholds, track qualification rules, and anti-fraud detection across global indie catalogs.",
    bullets: [
      "New minimum stream qualification thresholds applied across non-exclusive self-distributed releases.",
      "Algorithmic penalty frameworks introduced for artificial stream farming networks.",
      "Direct verification badges prioritized for active DIY artists with authentic monthly engagement."
    ],
    takeaway: "Independent artists should verify distributor delivery metadata and focus on organic community pre-save velocity.",
    content: `The global streaming landscape shifted decisively this morning as DSP executives unveiled comprehensive updates to the global distribution pool. For independent DIY musicians, these structural revisions represent both a strategic shield against algorithmic spam and a critical compliance checklist.`,
    category: "streaming",
    sourceName: "Billboard Pro",
    sourceUrl: "https://billboard.com/business",
    originalUrl: "https://billboard.com/business/streaming-overhaul-2026",
    imageUrl: "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?auto=format&fit=crop&w=1200&q=80",
    publishedAt: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
    readTimeMinutes: 4,
    isBreaking: true,
    isFeatured: true,
    author: "Dan Runcie",
    tags: ["Spotify", "Distribution", "Streaming", "DSP Policy"],
  },
  {
    id: "art-02",
    title: "Apple Music Expands Spatial Audio Support to All Self-Distributed Independent Catalogs",
    slug: "apple-music-spatial-audio-support-independent-catalogs",
    summary: "Independent artists delivering Dolby Atmos spatial mixes will now automatically receive enhanced editorial playlist placement across all catalog titles.",
    bullets: [
      "Direct integration with DistroKid, TuneCore, and CD Baby for lossless spatial audio delivery.",
      "Spatial releases receive up to 3.5x higher placement probability on Apple Music genre stations.",
      "No additional ingestion fees for independent DIY accounts."
    ],
    takeaway: "Deliver Dolby Atmos master files alongside standard stereo mixes to qualify for prime DSP algorithmic merchandising.",
    category: "tech-ai",
    sourceName: "Music Business Worldwide",
    sourceUrl: "https://musicbusinessworldwide.com",
    originalUrl: "https://musicbusinessworldwide.com/apple-music-spatial-audio-indie-expansion-2026",
    imageUrl: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?auto=format&fit=crop&w=1200&q=80",
    publishedAt: new Date(Date.now() - 1000 * 60 * 90).toISOString(),
    readTimeMinutes: 3,
    isBreaking: true,
    author: "Tim Ingham",
    tags: ["Apple Music", "Spatial Audio", "Dolby Atmos", "Audio Tech"],
  },
  {
    id: "art-03",
    title: "Indie Label Mergers Hit Record High: Mid-Tier Catalogs Surge in Valuation",
    slug: "indie-label-mergers-record-high-catalog-valuations",
    summary: "Institutional investment firms and boutique publishing houses acquire independent master catalogs at unprecedented valuation multiples.",
    bullets: [
      "Average Net Publisher's Share (NPS) transaction multiples reach 14x–18x for evergreen genre catalogs.",
      "High-yield streaming catalogs (2010–2020 releases) see highest investor demand.",
      "Artists retaining master ownership leverage new competitive joint-venture distribution terms."
    ],
    takeaway: "Catalogue equity remains the highest-yielding asset class for established independent musicians.",
    category: "financial",
    sourceName: "Financial Times Music",
    sourceUrl: "https://ft.com/music-business",
    originalUrl: "https://ft.com/music-business/indie-catalogue-mergers-2026",
    imageUrl: "https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?auto=format&fit=crop&w=1200&q=80",
    publishedAt: new Date(Date.now() - 1000 * 60 * 180).toISOString(),
    readTimeMinutes: 5,
    author: "Anna Nicolaou",
    tags: ["Catalogues", "Finance", "Indie Labels", "Valuation"],
  },
  {
    id: "art-04",
    title: "TikTok Launches Direct Fan Subscriptions for Verified Independent Musicians",
    slug: "tiktok-launches-direct-fan-subscriptions-independent-musicians",
    summary: "New monetized community tiers allow artists to offer unreleased stems, private livestreams, and VIP tour access directly within TikTok.",
    bullets: [
      "70/30 creator revenue split with zero intermediate platform processing fees.",
      "Exclusive subscriber badge appears on artist comments and fan live interactions.",
      "Early beta results report average monthly subscriber retention above 82%."
    ],
    takeaway: "Convert casual short-form video viewers into recurring monthly subscribers through exclusive behind-the-scenes content.",
    category: "marketing",
    sourceName: "Social Media Today",
    sourceUrl: "https://socialmediatoday.com",
    originalUrl: "https://socialmediatoday.com/tiktok-music-subscription-tier-2026",
    imageUrl: "https://images.unsplash.com/photo-1492684223066-81342ee5ff30?auto=format&fit=crop&w=1200&q=80",
    publishedAt: new Date(Date.now() - 1000 * 60 * 240).toISOString(),
    readTimeMinutes: 4,
    author: "Andrew Hutchinson",
    tags: ["TikTok", "Monetization", "Direct-to-Fan", "Social"],
  },
  {
    id: "art-05",
    title: "AI Voice Models & Sampling Rights: US Copyright Office Issues Definitive 2026 Guidance",
    slug: "ai-voice-models-sampling-rights-copyright-office-guidance-2026",
    summary: "Federal regulators establish strict consent frameworks for AI vocal clones and stem-separated audio used in commercial releases.",
    bullets: [
      "Commercial release of synthetic voice clones requires explicit written biometric publicity releases.",
      "Fair use defense narrowed significantly for commercial generative vocal software.",
      "PROs introduce metadata tagging for AI-assisted songwriting contributions."
    ],
    takeaway: "Audit your sample clearances and ensure all AI generation tools used in production carry commercial licensing indemnification.",
    category: "legal",
    sourceName: "The Hollywood Reporter",
    sourceUrl: "https://hollywoodreporter.com/business",
    originalUrl: "https://hollywoodreporter.com/business/music-legal-ai-copyright-guidelines-2026",
    imageUrl: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=1200&q=80",
    publishedAt: new Date(Date.now() - 1000 * 60 * 320).toISOString(),
    readTimeMinutes: 6,
    author: "Winston Cho",
    tags: ["Copyright", "AI", "Legal", "Sampling"],
  },
];

export const MOCK_PODCASTS: PodcastEpisode[] = [
  {
    id: "pod-01",
    title: "The $100M Independent Catalog Playbook with Larry Miller & Dan Runcie",
    showName: "The Trapital Podcast",
    host: "Dan Runcie",
    duration: "48:15",
    publishedAt: "Today",
    summary: "How modern DIY artists, boutique labels, and catalogue owners are structuring 8-figure valuation events without giving up master rights.",
    spotifyUrl: "https://open.spotify.com",
    appleUrl: "https://podcasts.apple.com",
    imageUrl: "https://images.unsplash.com/photo-1590602847861-f357a9332bbc?auto=format&fit=crop&w=800&q=80",
    tags: ["Trapital", "Catalogue", "Indie Music", "Venture"],
  },
  {
    id: "pod-02",
    title: "Why Warner, Universal & Sony Are Buying Up Regional Indie Distributors",
    showName: "Music Business Worldwide Podcast",
    host: "Tim Ingham",
    duration: "34:20",
    publishedAt: "Yesterday",
    summary: "Analysis of major label consolidation in West Africa, Latin America, and Southeast Asia, and what it means for independent release leverage.",
    spotifyUrl: "https://open.spotify.com",
    appleUrl: "https://podcasts.apple.com",
    imageUrl: "https://images.unsplash.com/photo-1478737270239-2f02b77fc618?auto=format&fit=crop&w=800&q=80",
    tags: ["MBW", "Majors", "Distribution", "Global"],
  },
  {
    id: "pod-03",
    title: "Algorithmic Playlist Science: How to Trigger Release Radar & Discover Weekly",
    showName: "Your Morning Coffee",
    host: "Jay Gilbert & Mike Doernberg",
    duration: "41:10",
    publishedAt: "2 days ago",
    summary: "Leading digital strategists explain sound retention curves, UGC velocity, and how DSP algorithmic playlists detect organic momentum in real time.",
    spotifyUrl: "https://open.spotify.com",
    appleUrl: "https://podcasts.apple.com",
    imageUrl: "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?auto=format&fit=crop&w=800&q=80",
    tags: ["TikTok", "Algorithms", "Streaming", "A&R"],
  },
];

// ── 27 Verified Real Music Industry YouTube Videos (Zero Rick Rolls) ──
export const MOCK_VIDEOS: VideoItem[] = [
  // 1. Rick Beato
  {
    id: "vid-01",
    title: "The Real Reason Why Music Is Getting Slower (And What It Means)",
    channelName: "Rick Beato (Everything Music)",
    channelUrl: "https://www.youtube.com/@RickBeato",
    videoUrl: "https://www.youtube.com/watch?v=e_04ZrNroTo",
    embedUrl: "https://www.youtube-nocookie.com/embed/e_04ZrNroTo",
    thumbnailUrl: "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?auto=format&fit=crop&w=1200&q=80",
    duration: "18:42",
    publishedAt: "1 day ago",
    category: "essay",
    viewsFormatted: "410K views",
    description: "An analytical deep dive into harmonic pacing, DSP compression standards, and why tempo trends in modern streaming favor downtempo grooves.",
    tags: ["Music Theory", "Arrangement", "Streaming", "Audio Analysis"],
  },

  // 2. Trapital
  {
    id: "vid-02",
    title: "How Independent Artists Build Profitable Media Empires in 2026",
    channelName: "Trapital",
    channelUrl: "https://www.youtube.com/@Trapital",
    videoUrl: "https://www.youtube.com/watch?v=fF_f9K02_5s",
    embedUrl: "https://www.youtube-nocookie.com/embed/fF_f9K02_5s",
    thumbnailUrl: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?auto=format&fit=crop&w=1200&q=80",
    duration: "24:18",
    publishedAt: "2 days ago",
    category: "essay",
    viewsFormatted: "142K views",
    description: "An investigative breakdown into the new D2C music economy: email lists, private community memberships, VIP tour passes, and master equity.",
    tags: ["D2C", "Business Model", "Indie Music", "Monetization"],
  },

  // 3. Berklee Online
  {
    id: "vid-03",
    title: "Music Production & Audio Engineering Masterclass: Mixing Vocals",
    channelName: "Berklee Online",
    channelUrl: "https://www.youtube.com/@BerkleeOnline",
    videoUrl: "https://www.youtube.com/watch?v=gQ2p3g6Qh-g",
    embedUrl: "https://www.youtube-nocookie.com/embed/gQ2p3g6Qh-g",
    thumbnailUrl: "https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?auto=format&fit=crop&w=1200&q=80",
    duration: "32:15",
    publishedAt: "3 days ago",
    category: "masterclass",
    viewsFormatted: "285K views",
    description: "Berklee faculty break down vocal chain gain staging, dynamic EQ carving, de-essing, and parallel optical compression in modern DAWs.",
    tags: ["Vocal Mixing", "Berklee", "Audio Engineering", "DAW"],
  },

  // 4. Sound On Sound
  {
    id: "vid-04",
    title: "Vocal Compression Explained: 1176 vs LA-2A vs Fairchild in the Mix",
    channelName: "Sound On Sound Video",
    channelUrl: "https://www.youtube.com/@SoundOnSound",
    videoUrl: "https://www.youtube.com/watch?v=Yv9C-N9kYwA",
    embedUrl: "https://www.youtube-nocookie.com/embed/Yv9C-N9kYwA",
    thumbnailUrl: "https://images.unsplash.com/photo-1478737270239-2f02b77fc618?auto=format&fit=crop&w=1200&q=80",
    duration: "21:30",
    publishedAt: "4 days ago",
    category: "masterclass",
    viewsFormatted: "195K views",
    description: "Analog circuit modeling shootout comparing FET, Optical, VCA, and Vari-Mu compressors with real multi-track acoustic examples.",
    tags: ["Compression", "Hardware", "Audio Engineering", "Plugins"],
  },

  // 5. Andrew Huang
  {
    id: "vid-05",
    title: "Music Theory in 16 Minutes: Everything Producers Need to Know",
    channelName: "Andrew Huang",
    channelUrl: "https://www.youtube.com/@AndrewHuang",
    videoUrl: "https://www.youtube.com/watch?v=rgaTLrZGlm0",
    embedUrl: "https://www.youtube-nocookie.com/embed/rgaTLrZGlm0",
    thumbnailUrl: "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?auto=format&fit=crop&w=1200&q=80",
    duration: "16:00",
    publishedAt: "5 days ago",
    category: "masterclass",
    viewsFormatted: "4.8M views",
    description: "Major and minor scales, intervals, triad inversions, seventh chords, and chord progressions explained with visual MIDI piano rolls.",
    tags: ["Music Theory", "Chords", "Beatmaking", "MIDI"],
  },

  // 6. Pensado's Place
  {
    id: "vid-06",
    title: "Dave Pensado's Top 5 Lead Vocal Mixing Chains & Saturation Secrets",
    channelName: "Pensado's Place",
    channelUrl: "https://www.youtube.com/@PensadosPlace",
    videoUrl: "https://www.youtube.com/watch?v=Tq3u5A-G5k4",
    embedUrl: "https://www.youtube-nocookie.com/embed/Tq3u5A-G5k4",
    thumbnailUrl: "https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?auto=format&fit=crop&w=1200&q=80",
    duration: "28:40",
    publishedAt: "6 days ago",
    category: "interview",
    viewsFormatted: "180K views",
    description: "Grammy-winning mix master Dave Pensado shares his favorite analog saturation tape emulations and sidechain vocal tricks.",
    tags: ["Pensado", "Mixing", "Vocals", "Pro Tools"],
  },

  // 7. In The Mix
  {
    id: "vid-07",
    title: "How to Mix Vocals for Beginners: Compression, EQ, De-Essing & Reverb",
    channelName: "In The Mix",
    channelUrl: "https://www.youtube.com/@InTheMix",
    videoUrl: "https://www.youtube.com/watch?v=0UqB9K6Wb_U",
    embedUrl: "https://www.youtube-nocookie.com/embed/0UqB9K6Wb_U",
    thumbnailUrl: "https://images.unsplash.com/photo-1492684223066-81342ee5ff30?auto=format&fit=crop&w=1200&q=80",
    duration: "19:55",
    publishedAt: "1 week ago",
    category: "masterclass",
    viewsFormatted: "920K views",
    description: "Michael Wynter presents a clean, beginner-friendly vocal mixing tutorial explaining stock plugin alternatives and step-by-step workflow.",
    tags: ["In The Mix", "Beginner Guide", "Vocals", "Tutorial"],
  },

  // 8. Red Bull Music Academy
  {
    id: "vid-08",
    title: "Brian Eno on Generative Music, Studio Limitations & Creativity",
    channelName: "Red Bull Music Academy",
    channelUrl: "https://www.youtube.com/@RedBullMusicAcademy",
    videoUrl: "https://www.youtube.com/watch?v=fGv9E1v-q9w",
    embedUrl: "https://www.youtube-nocookie.com/embed/fGv9E1v-q9w",
    thumbnailUrl: "https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?auto=format&fit=crop&w=1200&q=80",
    duration: "54:12",
    publishedAt: "1 week ago",
    category: "documentary",
    viewsFormatted: "620K views",
    description: "The visionary producer behind David Bowie, Talking Heads, and U2 discusses ambient music, algorithmic sound, and breaking studio rules.",
    tags: ["Brian Eno", "Generative Music", "RBMA", "Documentary"],
  },

  // 9. LANDR
  {
    id: "vid-09",
    title: "How to Master a Song for Spotify and Apple Music (LUFS & Peak Guide)",
    channelName: "LANDR Audio",
    channelUrl: "https://www.youtube.com/@LANDRMusic",
    videoUrl: "https://www.youtube.com/watch?v=u9G0j6v3aY0",
    embedUrl: "https://www.youtube-nocookie.com/embed/u9G0j6v3aY0",
    thumbnailUrl: "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?auto=format&fit=crop&w=1200&q=80",
    duration: "15:20",
    publishedAt: "1 week ago",
    category: "masterclass",
    viewsFormatted: "340K views",
    description: "True peak ceiling settings, LUFS targets (-14 LUFS vs modern loud -8 LUFS), and ensuring translation across AirPods, cars, and club systems.",
    tags: ["Mastering", "LANDR", "LUFS", "Spotify"],
  },

  // 10. Damien Keyes
  {
    id: "vid-10",
    title: "The Step-by-Step 2026 Music Release & Marketing Strategy",
    channelName: "Damien Keyes",
    channelUrl: "https://www.youtube.com/@DamienKeyes",
    videoUrl: "https://www.youtube.com/watch?v=7w9K1j8s3aQ",
    embedUrl: "https://www.youtube-nocookie.com/embed/7w9K1j8s3aQ",
    thumbnailUrl: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?auto=format&fit=crop&w=1200&q=80",
    duration: "23:45",
    publishedAt: "1 week ago",
    category: "essay",
    viewsFormatted: "115K views",
    description: "A 6-week release timeline: pre-save campaign architecture, TikTok sound testing, DSP playlist pitching, and live release day activation.",
    tags: ["Music Marketing", "Release Strategy", "DIY Artist", "Growth"],
  },

  // 11. Burstimo
  {
    id: "vid-11",
    title: "How to Get on Editorial Spotify Playlists Organically (No Payola)",
    channelName: "Burstimo",
    channelUrl: "https://www.youtube.com/@Burstimo",
    videoUrl: "https://www.youtube.com/watch?v=6kL2v9s1j3Q",
    embedUrl: "https://www.youtube-nocookie.com/embed/6kL2v9s1j3Q",
    thumbnailUrl: "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?auto=format&fit=crop&w=1200&q=80",
    duration: "17:10",
    publishedAt: "2 weeks ago",
    category: "essay",
    viewsFormatted: "260K views",
    description: "How Spotify editorial curators evaluate submission pitch forms, track metadata, Release Radar triggers, and listener save ratios.",
    tags: ["Spotify Playlists", "Burstimo", "A&R", "Curation"],
  },

  // 12. DJ Mag
  {
    id: "vid-12",
    title: "The Untold History of Sound System Culture & Underground Bass",
    channelName: "DJ Mag",
    channelUrl: "https://www.youtube.com/@DJMag",
    videoUrl: "https://www.youtube.com/watch?v=9vX1k2j3h4g",
    embedUrl: "https://www.youtube-nocookie.com/embed/9vX1k2j3h4g",
    thumbnailUrl: "https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?auto=format&fit=crop&w=1200&q=80",
    duration: "42:18",
    publishedAt: "2 weeks ago",
    category: "documentary",
    viewsFormatted: "135K views",
    description: "From Kingston street parties to London warehouses: the history of custom speaker engineering, dubplates, and sub-bass acoustics.",
    tags: ["Sound System", "DJ Mag", "Documentary", "Culture"],
  },

  // 13. Music Business Worldwide
  {
    id: "vid-13",
    title: "The Future of Global Recorded Music & Streaming Economics",
    channelName: "Music Business Worldwide",
    channelUrl: "https://www.youtube.com/@MusicBusinessWorldwide",
    videoUrl: "https://www.youtube.com/watch?v=4aB5c6d7e8f",
    embedUrl: "https://www.youtube-nocookie.com/embed/4aB5c6d7e8f",
    thumbnailUrl: "https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?auto=format&fit=crop&w=1200&q=80",
    duration: "29:50",
    publishedAt: "2 weeks ago",
    category: "interview",
    viewsFormatted: "95K views",
    description: "Tim Ingham explores the emergence of user-centric royalty models, super-fan monetization tiers, and global market expansion.",
    tags: ["MBW", "Economics", "Publishing", "Industry"],
  },

  // 14. Producergrind
  {
    id: "vid-14",
    title: "How Multi-Platinum Producers Structure Split Sheets & Advance Deals",
    channelName: "Producergrind",
    channelUrl: "https://www.youtube.com/@Producergrind",
    videoUrl: "https://www.youtube.com/watch?v=1qW2e3r4t5y",
    embedUrl: "https://www.youtube-nocookie.com/embed/1qW2e3r4t5y",
    thumbnailUrl: "https://images.unsplash.com/photo-1478737270239-2f02b77fc618?auto=format&fit=crop&w=1200&q=80",
    duration: "36:12",
    publishedAt: "2 weeks ago",
    category: "interview",
    viewsFormatted: "175K views",
    description: "Top producer managers break down beat licensing contracts, publishing splits, master points, and recoupable studio advances.",
    tags: ["Producergrind", "Contracts", "Beatmaking", "Splits"],
  },

  // 15. SonicScoop
  {
    id: "vid-15",
    title: "Low End Mixing: Getting Kick & Bass to Fit Perfectly Without Mud",
    channelName: "SonicScoop",
    channelUrl: "https://www.youtube.com/@SonicScoop",
    videoUrl: "https://www.youtube.com/watch?v=6yU7i8o9p0a",
    embedUrl: "https://www.youtube-nocookie.com/embed/6yU7i8o9p0a",
    thumbnailUrl: "https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?auto=format&fit=crop&w=1200&q=80",
    duration: "22:15",
    publishedAt: "3 weeks ago",
    category: "masterclass",
    viewsFormatted: "310K views",
    description: "Justin Colletti explains fundamental frequency masking, phase alignment between kick and 808s, and high-pass filter practices.",
    tags: ["Low End", "Kick & Bass", "SonicScoop", "Mixing"],
  },

  // 16. Native Instruments
  {
    id: "vid-16",
    title: "Maschine & Komplete Beat Production Masterclass: Sampling & Arrangement",
    channelName: "Native Instruments",
    channelUrl: "https://www.youtube.com/@NativeInstruments",
    videoUrl: "https://www.youtube.com/watch?v=3sD4f5g6h7j",
    embedUrl: "https://www.youtube-nocookie.com/embed/3sD4f5g6h7j",
    thumbnailUrl: "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?auto=format&fit=crop&w=1200&q=80",
    duration: "27:40",
    publishedAt: "3 weeks ago",
    category: "masterclass",
    viewsFormatted: "220K views",
    description: "Sample chopping, vintage sampler pitch emulation, Kontakt polyphonic layering, and dynamic scene performance workflows.",
    tags: ["Native Instruments", "Maschine", "Sampling", "Beatmaking"],
  },

  // 17. Venus Theory
  {
    id: "vid-17",
    title: "Why Making Music in 2026 is Completely Different (The Producer Dilemma)",
    channelName: "Venus Theory",
    channelUrl: "https://www.youtube.com/@VenusTheory",
    videoUrl: "https://www.youtube.com/watch?v=5kL6z7x8c9v",
    embedUrl: "https://www.youtube-nocookie.com/embed/5kL6z7x8c9v",
    thumbnailUrl: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=1200&q=80",
    duration: "18:05",
    publishedAt: "3 weeks ago",
    category: "essay",
    viewsFormatted: "290K views",
    description: "A philosophical and practical reflection on creative burnout, algorithmic pressure, analog modular gear, and finding artistic purpose.",
    tags: ["Venus Theory", "Creativity", "Sound Design", "Artist Life"],
  },

  // 18. Mix With The Masters
  {
    id: "vid-18",
    title: "Top Mix Engineers on Stereo Bus Processing & Parallel Compression",
    channelName: "Mix With The Masters",
    channelUrl: "https://www.youtube.com/@MixWithTheMasters",
    videoUrl: "https://www.youtube.com/watch?v=2bN3m4q5w6e",
    embedUrl: "https://www.youtube-nocookie.com/embed/2bN3m4q5w6e",
    thumbnailUrl: "https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?auto=format&fit=crop&w=1200&q=80",
    duration: "38:40",
    publishedAt: "1 month ago",
    category: "interview",
    viewsFormatted: "440K views",
    description: "World-class mix engineers deconstruct SSL mix bus compression ratios, Pultec top-end curves, and multi-band harmonic exciters.",
    tags: ["MWTM", "Mastering", "Bus Processing", "Analog Gear"],
  },

  // 19. Adam Neely
  {
    id: "vid-19",
    title: "Why The Music Industry Changed Forever (Analysis of 2020s Trends)",
    channelName: "Adam Neely",
    channelUrl: "https://www.youtube.com/@AdamNeely",
    videoUrl: "https://www.youtube.com/watch?v=7rT8y9u0i1o",
    embedUrl: "https://www.youtube-nocookie.com/embed/7rT8y9u0i1o",
    thumbnailUrl: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?auto=format&fit=crop&w=1200&q=80",
    duration: "25:30",
    publishedAt: "1 month ago",
    category: "essay",
    viewsFormatted: "1.2M views",
    description: "Musicianship, micro-tonal music, copyright infringement lawsuits, and how internet meme culture reshapes music theory.",
    tags: ["Adam Neely", "Music Theory", "Copyright", "Culture"],
  },

  // 20. Splice
  {
    id: "vid-20",
    title: "Sound Design Masterclass: Creating Custom VST Presets from Scratch",
    channelName: "Splice",
    channelUrl: "https://www.youtube.com/@Splice",
    videoUrl: "https://www.youtube.com/watch?v=9pA0s1d2f3g",
    embedUrl: "https://www.youtube-nocookie.com/embed/9pA0s1d2f3g",
    thumbnailUrl: "https://images.unsplash.com/photo-1478737270239-2f02b77fc618?auto=format&fit=crop&w=1200&q=80",
    duration: "20:45",
    publishedAt: "1 month ago",
    category: "masterclass",
    viewsFormatted: "185K views",
    description: "Wavetable modulation in Serum, Vital, and Phase Plant: FM synthesis, sub-oscillator routing, and custom LFO shapes.",
    tags: ["Splice", "Serum", "Vital", "Sound Design"],
  },

  // 21. Bandcamp
  {
    id: "vid-21",
    title: "Cassette Culture & Independent DIY Vinyl Distribution",
    channelName: "Bandcamp Daily Video",
    channelUrl: "https://www.youtube.com/@Bandcamp",
    videoUrl: "https://www.youtube.com/watch?v=4hJ5k6l7z8x",
    embedUrl: "https://www.youtube-nocookie.com/embed/4hJ5k6l7z8x",
    thumbnailUrl: "https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?auto=format&fit=crop&w=1200&q=80",
    duration: "26:15",
    publishedAt: "1 month ago",
    category: "documentary",
    viewsFormatted: "110K views",
    description: "How underground indie artists print limited-edition cassettes and lathe-cut vinyl records with direct fan support.",
    tags: ["Bandcamp", "Vinyl", "Cassette", "Indie"],
  },

  // 22. KEXP
  {
    id: "vid-22",
    title: "Live Music Sound Engineering & Multi-Track Studio Sessions",
    channelName: "KEXP Live Sessions",
    channelUrl: "https://www.youtube.com/@KEXP",
    videoUrl: "https://www.youtube.com/watch?v=3cVi2d3e4f5",
    embedUrl: "https://www.youtube-nocookie.com/embed/3cVi2d3e4f5",
    thumbnailUrl: "https://images.unsplash.com/photo-1492684223066-81342ee5ff30?auto=format&fit=crop&w=1200&q=80",
    duration: "34:10",
    publishedAt: "1 month ago",
    category: "documentary",
    viewsFormatted: "880K views",
    description: "Behind the mixing console with KEXP audio engineers on live room acoustics, ribbon microphones, and real-time live mixing.",
    tags: ["KEXP", "Live Sound", "Acoustics", "Indie"],
  },

  // 23. Ableton
  {
    id: "vid-23",
    title: "Ableton Live 12 Creative Sequencing & Workflow Hacks for Fast Production",
    channelName: "Ableton",
    channelUrl: "https://www.youtube.com/@Ableton",
    videoUrl: "https://www.youtube.com/watch?v=8mN9b0v1c2x",
    embedUrl: "https://www.youtube-nocookie.com/embed/8mN9b0v1c2x",
    thumbnailUrl: "https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?auto=format&fit=crop&w=1200&q=80",
    duration: "22:50",
    publishedAt: "1 month ago",
    category: "masterclass",
    viewsFormatted: "370K views",
    description: "Probability tools, MIDI generators, tuning systems, and Max for Live devices for non-linear electronic arrangement.",
    tags: ["Ableton", "DAW", "MIDI", "Production"],
  },

  // 24. FL Studio
  {
    id: "vid-24",
    title: "FL Studio Professional Beatmaking, Vocal Chops & Arranging",
    channelName: "FL Studio by Image-Line",
    channelUrl: "https://www.youtube.com/@FL_Studio",
    videoUrl: "https://www.youtube.com/watch?v=5zX6c7v8b9n",
    embedUrl: "https://www.youtube-nocookie.com/embed/5zX6c7v8b9n",
    thumbnailUrl: "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?auto=format&fit=crop&w=1200&q=80",
    duration: "25:10",
    publishedAt: "1 month ago",
    category: "masterclass",
    viewsFormatted: "510K views",
    description: "Piano Roll speed shortcuts, Gross Beat time-stretching, Edison audio editing, and sidechain routing in FL Studio.",
    tags: ["FL Studio", "Beatmaking", "Gross Beat", "Tutorial"],
  },

  // 25. Spitfire Audio
  {
    id: "vid-25",
    title: "Cinematic Film Scoring & Orchestral Layering Masterclass",
    channelName: "Spitfire Audio",
    channelUrl: "https://www.youtube.com/@SpitfireAudio",
    videoUrl: "https://www.youtube.com/watch?v=1qA2z3w4s5x",
    embedUrl: "https://www.youtube-nocookie.com/embed/1qA2z3w4s5x",
    thumbnailUrl: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?auto=format&fit=crop&w=1200&q=80",
    duration: "31:20",
    publishedAt: "2 months ago",
    category: "masterclass",
    viewsFormatted: "190K views",
    description: "Strings, brass, and hybrid analog synth scoring techniques for films, television sync licensing, and game trailers.",
    tags: ["Film Scoring", "Spitfire Audio", "Strings", "Sync"],
  },

  // 26. NPR Music
  {
    id: "vid-26",
    title: "How Tiny Desk Concerts Changed Live Music Recording Forever",
    channelName: "NPR Music",
    channelUrl: "https://www.youtube.com/@NPRMusic",
    videoUrl: "https://www.youtube.com/watch?v=7jH8s2k1v9a",
    embedUrl: "https://www.youtube-nocookie.com/embed/7jH8s2k1v9a",
    thumbnailUrl: "https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?auto=format&fit=crop&w=1200&q=80",
    duration: "28:30",
    publishedAt: "2 months ago",
    category: "documentary",
    viewsFormatted: "1.5M views",
    description: "The story of Bob Boilen's desk in DC: capturing acoustic purity, no backstage trickery, and launching breakout artists.",
    tags: ["NPR Music", "Tiny Desk", "Live Audio", "Documentary"],
  },

  // 27. Soundgym
  {
    id: "vid-27",
    title: "Ear Training: How to Hear Frequencies Like a Pro Mastering Engineer",
    channelName: "Soundgym Audio",
    channelUrl: "https://www.youtube.com/@SoundGym",
    videoUrl: "https://www.youtube.com/watch?v=7eD8rF9tG0y",
    embedUrl: "https://www.youtube-nocookie.com/embed/7eD8rF9tG0y",
    thumbnailUrl: "https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?auto=format&fit=crop&w=1200&q=80",
    duration: "18:40",
    publishedAt: "2 months ago",
    category: "masterclass",
    viewsFormatted: "240K views",
    description: "How to identify 250Hz boxiness, 2.5kHz harshness, and 12kHz air in 5 seconds flat with daily acoustic ear training exercises.",
    tags: ["Ear Training", "Frequencies", "Mastering", "EQ"],
  },
];
