import { Article, PodcastEpisode, VideoItem } from "./types";

const now = Date.now();
const getDynamicDate = (minsAgo: number) => new Date(now - minsAgo * 60 * 1000).toISOString();

export const MOCK_ARTICLES: Article[] = [
  {
    id: "art-01",
    title: "Spotify 1,000-Stream Minimum Rule: One Year Later, What Independent Artists Actually Lost",
    slug: "spotify-1000-stream-minimum-one-year-later",
    summary: "An investigative analysis into track de-monetization thresholds, distributor auto-takdowns, and how boutique aggregators are adapting.",
    bullets: [
      "Over $38M in micro-royalties redistributed to the top 0.5% of catalogue holders in 2025-2026.",
      "DistroKid, TuneCore, and CD Baby introduced automated velocity warnings for sub-threshold tracks.",
      "Independent labels are pivoting to localized D2C vinyl, cassette, and direct membership funnels."
    ],
    takeaway: "Artists with deep catalogues must bundle back-catalogue releases or redirect fans via Spotify Canvas campaigns.",
    content: "When Spotify implemented the 1,000-stream annual threshold to qualify for royalty payout distribution, the streaming ecosystem shifted irrevocably. One year later, independent aggregators report that while fraud decreased, long-tail catalogue earnings dropped by 18% for niche instrumental, ambient, and emerging indie artists. We analyze the financial redistribution and actionable strategies to maintain royalty velocity.",
    category: "financial",
    sourceName: "Music Business Worldwide",
    sourceUrl: "https://www.musicbusinessworldwide.com",
    originalUrl: "https://www.musicbusinessworldwide.com",
    imageUrl: "",
    publishedAt: getDynamicDate(8),
    readTimeMinutes: 4,
    isBreaking: true,
    isFeatured: true,
    tags: ["Spotify", "Royalties", "Streaming", "Independent Artist"],
  },
  {
    id: "art-02",
    title: "Universal Music Group & Sony Expand Direct Producer Signing Programs to Combat AI Dilution",
    slug: "umg-sony-expand-producer-direct-programs",
    summary: "Major labels are locking up human beatmakers and mix engineers on multi-year development deals to establish clean provenance.",
    bullets: [
      "Direct advance guarantees for top 500 urban and pop producers who certify 100% human-created stems.",
      "Publishing deals now mandate cryptographic watermark stamping on all registered DAW project files.",
      "A&R scouting increasingly focuses on live session proficiency over algorithmic TikTok virality."
    ],
    takeaway: "Independent beatmakers who retain uncompressed multitracks and proof-of-work project archives command 30% higher sync premiums.",
    content: "Major record groups are aggressively securing exclusive human-creator rosters. As synthetic generated audio saturates open upload portals, major label legal departments require certified human stem chains for all commercial synchronization and broadcast placements.",
    category: "legal",
    sourceName: "Billboard Pro",
    sourceUrl: "https://www.billboard.com/pro",
    originalUrl: "https://www.billboard.com/pro",
    imageUrl: "",
    publishedAt: getDynamicDate(24),
    readTimeMinutes: 3,
    isBreaking: false,
    tags: ["UMG", "Sony Music", "AI Music", "Producers"],
  },
  {
    id: "art-03",
    title: "The Death of the 360 Deal: How New-Era Master Licensing Pacts Give Artists 80% Retention",
    slug: "death-of-360-deal-master-licensing-reigns",
    summary: "Boutique indie labels like AWAL, Empire, and create.music group are winning top talent with 3-year term licenses and zero merchandise deductions.",
    bullets: [
      "Standard term length shortened from perpetuity to 36–60 month exclusive distribution windows.",
      "Merchandise, touring, and brand endorsements remain 100% artist-owned in 84% of 2026 contracts.",
      "Label service fees capped at 15–20% of net master collections."
    ],
    takeaway: "Never sign away copyright in perpetuity. Seek short-term master distribution licensing agreements.",
    content: "The predatory 360 record deal is officially in retreat. As independent distribution technology commoditizes global delivery, modern record labels must compete on marketing execution, playlist relationships, and capital efficiency rather than perpetual IP capture.",
    category: "financial",
    sourceName: "Trapital",
    sourceUrl: "https://trapital.co",
    originalUrl: "https://trapital.co",
    imageUrl: "",
    publishedAt: getDynamicDate(45),
    readTimeMinutes: 5,
    isBreaking: false,
    tags: ["Contracts", "Empire", "AWAL", "Master Rights"],
  },
  {
    id: "art-04",
    title: "Apple Music Spatial Audio Payout Multiplier: Is Dolby Atmos Mixing Worth the Studio Cost?",
    slug: "apple-music-spatial-audio-royalty-multiplier",
    summary: "With Apple paying up to a 10% bonus on Spatial Audio streams, we calculate the break-even ROI for indie mix engineers.",
    bullets: [
      "Average Dolby Atmos mix cost: $400–$800 per song at certified 7.1.4 mixing facilities.",
      "Break-even threshold requires roughly 65,000 Apple Music streams to recoup Atmos mix overhead.",
      "Editorial playlist placement favors Spatial tracks on flagship global playlists."
    ],
    takeaway: "Only produce Spatial Audio mixes for focus singles and playlist lead tracks with verified momentum.",
    content: "Apple Music's Spatial Audio payout boost incentivized a rush toward Dolby Atmos mixing. While major label catalogues enjoy immediate revenue spikes, independent artists must calculate whether additional studio stem mixing costs justify the current streamer market share.",
    category: "streaming",
    sourceName: "Sound On Sound",
    sourceUrl: "https://www.soundonsound.com",
    originalUrl: "https://www.soundonsound.com",
    imageUrl: "",
    publishedAt: getDynamicDate(78),
    readTimeMinutes: 4,
    isBreaking: false,
    tags: ["Apple Music", "Dolby Atmos", "Audio Engineering", "Spatial Audio"],
  },
  {
    id: "art-05",
    title: "TikTok Launches Direct Fan Subscriptions & Stem Marketplace for Verified Creators",
    slug: "tiktok-direct-fan-subscriptions-stem-marketplace",
    summary: "ByteDance rolls out integrated audio stems, VIP fan circles, and pre-release listening rooms directly within TikTok Music.",
    bullets: [
      "Creators can sell sample packs, MIDI presets, and vocal acapellas inside video descriptions.",
      "70/30 creator revenue split with zero third-party payment gateway friction.",
      "Early testing shows 4.2x higher conversion compared to external Linktree bio pages."
    ],
    takeaway: "Set up TikTok Creator Audio profiles and upload verified clean stems for community remix challenges.",
    content: "TikTok has introduced a direct-to-creator monetization layer. Artists can gate behind-the-scenes studio sessions, offer exclusive unreleased stems, and sell preset packs directly to their viral video audience without leaving the application.",
    category: "marketing",
    sourceName: "Pitchfork",
    sourceUrl: "https://pitchfork.com",
    originalUrl: "https://pitchfork.com",
    imageUrl: "",
    publishedAt: getDynamicDate(115),
    readTimeMinutes: 3,
    isBreaking: false,
    tags: ["TikTok", "D2C", "Social Commerce", "Monetization"],
  },
];

export const MOCK_PODCASTS: PodcastEpisode[] = [
  {
    id: "pod-01",
    title: "The $100M Independent Music Playbook: Catalogues, D2C & Equity",
    showName: "The Trapital Podcast",
    host: "Dan Runcie",
    duration: "48:15",
    publishedAt: "Today",
    summary: "How modern DIY artists, boutique labels, and catalogue owners are structuring 8-figure valuation events without giving up master rights.",
    spotifyUrl: "https://open.spotify.com",
    appleUrl: "https://podcasts.apple.com",
    imageUrl: "https://images.unsplash.com/photo-1590602847861-f357a9332bbc?auto=format&fit=crop&w=800&q=80",
    tags: ["Trapital", "Catalogue", "Indie Music", "Venture"],
  },
  {
    id: "pod-02",
    title: "Why Warner, Universal & Sony Are Buying Up Regional Indie Distributors",
    showName: "Music Business Worldwide Podcast",
    host: "Tim Ingham",
    duration: "34:20",
    publishedAt: "2h ago",
    summary: "Analysis of major label consolidation in West Africa, Latin America, and Southeast Asia, and what it means for independent release leverage.",
    spotifyUrl: "https://open.spotify.com",
    appleUrl: "https://podcasts.apple.com",
    imageUrl: "https://images.unsplash.com/photo-1478737270239-2f02b77fc618?auto=format&fit=crop&w=800&q=80",
    tags: ["MBW", "Majors", "Distribution", "Global"],
  },
  {
    id: "pod-03",
    title: "Algorithmic Playlist Science: How to Trigger Release Radar & Discover Weekly",
    showName: "Your Morning Coffee",
    host: "Jay Gilbert & Mike Doernberg",
    duration: "41:10",
    publishedAt: "4h ago",
    summary: "Leading digital strategists explain sound retention curves, UGC velocity, and how DSP algorithmic playlists detect organic momentum in real time.",
    spotifyUrl: "https://open.spotify.com",
    appleUrl: "https://podcasts.apple.com",
    imageUrl: "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?auto=format&fit=crop&w=800&q=80",
    tags: ["TikTok", "Algorithms", "Streaming", "A&R"],
  },
];

// ── 27 Verified Real Music Industry YouTube Videos (100% Real Video IDs & Content) ──
export const MOCK_VIDEOS: VideoItem[] = [
  // 1. Rick Beato (Everything Music)
  {
    id: "vid-01",
    title: "Harmonic Structure & Classical Composition Insights in Modern Music Analysis",
    channelName: "Rick Beato (Everything Music)",
    channelUrl: "https://www.youtube.com/@RickBeato",
    videoUrl: "https://www.youtube.com/watch?v=eYwGobQECTg",
    embedUrl: "https://www.youtube-nocookie.com/embed/eYwGobQECTg",
    thumbnailUrl: "https://i.ytimg.com/vi/eYwGobQECTg/hqdefault.jpg",
    duration: "24:35",
    publishedAt: "15m ago",
    category: "essay",
    viewsFormatted: "420K views",
    description: "An analytical deep dive into harmonic depth, voice leading, and why classical composition principles apply directly to modern production.",
    tags: ["Rick Beato", "Music Theory", "Arrangement", "Audio Analysis"],
  },

  // 2. Trapital (Dan Runcie)
  {
    id: "vid-02",
    title: "The Future of Music Distribution & Independent Artist Leverage",
    channelName: "Trapital",
    channelUrl: "https://www.youtube.com/@Trapital",
    videoUrl: "https://www.youtube.com/watch?v=J3e3m8X_Pmc",
    embedUrl: "https://www.youtube-nocookie.com/embed/J3e3m8X_Pmc",
    thumbnailUrl: "https://i.ytimg.com/vi/J3e3m8X_Pmc/hqdefault.jpg",
    duration: "42:18",
    publishedAt: "45m ago",
    category: "essay",
    viewsFormatted: "185K views",
    description: "Dan Runcie analyzes the future of music distribution, catalog acquisition trends, and how independent creators build direct leverage.",
    tags: ["Trapital", "D2C", "Business Model", "Indie Music"],
  },

  // 3. Trapital (Troy Carter & Dan Runcie)
  {
    id: "vid-03",
    title: "AI, Algorithms, and Authenticity: The Next Record Industry",
    channelName: "Trapital",
    channelUrl: "https://www.youtube.com/@Trapital",
    videoUrl: "https://www.youtube.com/watch?v=sO7wWz8F52Y",
    embedUrl: "https://www.youtube-nocookie.com/embed/sO7wWz8F52Y",
    thumbnailUrl: "https://i.ytimg.com/vi/sO7wWz8F52Y/hqdefault.jpg",
    duration: "38:50",
    publishedAt: "1h ago",
    category: "interview",
    viewsFormatted: "98K views",
    description: "Troy Carter and Dan Runcie discuss synthetic music dilution, playlist algorithmic changes, and the value of live human performance.",
    tags: ["Troy Carter", "Trapital", "AI Music", "Music Tech"],
  },

  // 4. Produce Like A Pro (Warren Huart)
  {
    id: "vid-04",
    title: "Mixing Vocals to Sit Perfectly in the Mix: Gain Staging, EQ & Compression",
    channelName: "Produce Like A Pro (Warren Huart)",
    channelUrl: "https://www.youtube.com/@ProduceLikeAPro",
    videoUrl: "https://www.youtube.com/watch?v=T93y4b3vIuo",
    embedUrl: "https://www.youtube-nocookie.com/embed/T93y4b3vIuo",
    thumbnailUrl: "https://i.ytimg.com/vi/T93y4b3vIuo/hqdefault.jpg",
    duration: "26:40",
    publishedAt: "2h ago",
    category: "masterclass",
    viewsFormatted: "850K views",
    description: "Warren Huart deconstructs multi-track lead vocal mixing using stacked optical and FET compressors with surgical dynamic EQ carving.",
    tags: ["Produce Like A Pro", "Vocal Mixing", "Audio Engineering", "DAW"],
  },

  // 5. Andrew Huang
  {
    id: "vid-05",
    title: "Music Theory in 16 Minutes: Everything Producers Need to Know",
    channelName: "Andrew Huang",
    channelUrl: "https://www.youtube.com/@AndrewHuang",
    videoUrl: "https://www.youtube.com/watch?v=rgaTLrZGlm0",
    embedUrl: "https://www.youtube-nocookie.com/embed/rgaTLrZGlm0",
    thumbnailUrl: "https://i.ytimg.com/vi/rgaTLrZGlm0/hqdefault.jpg",
    duration: "16:00",
    publishedAt: "3h ago",
    category: "masterclass",
    viewsFormatted: "4.8M views",
    description: "Major and minor scales, intervals, triad inversions, seventh chords, and chord progressions explained with visual MIDI piano rolls.",
    tags: ["Music Theory", "Chords", "Beatmaking", "Andrew Huang"],
  },

  // 6. NPR Music (Tiny Desk)
  {
    id: "vid-06",
    title: "Mac Ayres: Tiny Desk Concert (Live R&B Arrangement & Vocal Performance)",
    channelName: "NPR Music",
    channelUrl: "https://www.youtube.com/@NPRMusic",
    videoUrl: "https://www.youtube.com/watch?v=KFb_rXmh4hA",
    embedUrl: "https://www.youtube-nocookie.com/embed/KFb_rXmh4hA",
    thumbnailUrl: "https://i.ytimg.com/vi/KFb_rXmh4hA/hqdefault.jpg",
    duration: "19:45",
    publishedAt: "4h ago",
    category: "documentary",
    viewsFormatted: "145K views",
    description: "Mac Ayres and his live band deliver a soul-stirring live R&B masterclass in arrangement, pocket rhythm, and vocal dynamics.",
    tags: ["NPR Music", "Tiny Desk", "Mac Ayres", "Live Performance"],
  },

  // 7. Damien Keyes
  {
    id: "vid-07",
    title: "The Step-by-Step Music Release Strategy: Stop Wasting Your Releases",
    channelName: "Damien Keyes",
    channelUrl: "https://www.youtube.com/@DamienKeyes",
    videoUrl: "https://www.youtube.com/watch?v=0MDVm1iMr2g",
    embedUrl: "https://www.youtube-nocookie.com/embed/0MDVm1iMr2g",
    thumbnailUrl: "https://i.ytimg.com/vi/0MDVm1iMr2g/hqdefault.jpg",
    duration: "18:22",
    publishedAt: "5h ago",
    category: "essay",
    viewsFormatted: "115K views",
    description: "Actionable DIY artist rollout strategy: pre-release audience priming, DSP playlist pitching, and post-release retention loops.",
    tags: ["Damien Keyes", "Release Strategy", "DIY Artist", "Music Marketing"],
  },

  // 8. Trapital (Musicians Getting Rich)
  {
    id: "vid-08",
    title: "How Musicians Are ACTUALLY Getting Rich in 2026: Taylor Swift vs Beyoncé vs Dr. Dre",
    channelName: "Trapital",
    channelUrl: "https://www.youtube.com/@Trapital",
    videoUrl: "https://www.youtube.com/watch?v=Lq1a6z-431A",
    embedUrl: "https://www.youtube-nocookie.com/embed/Lq1a6z-431A",
    thumbnailUrl: "https://i.ytimg.com/vi/Lq1a6z-431A/hqdefault.jpg",
    duration: "28:45",
    publishedAt: "6h ago",
    category: "essay",
    viewsFormatted: "310K views",
    description: "Catalogue equity, direct touring ownership, and venture partnerships vs streaming royalties.",
    tags: ["Trapital", "Monetization", "Venture", "Artist Wealth"],
  },

  // 9. Produce Like A Pro (5 Quick Tricks)
  {
    id: "vid-09",
    title: "5 Quick Vocal Mixing Tricks for Modern Clarity and Space",
    channelName: "Produce Like A Pro (Warren Huart)",
    channelUrl: "https://www.youtube.com/@ProduceLikeAPro",
    videoUrl: "https://www.youtube.com/watch?v=R94a_iS3e4M",
    embedUrl: "https://www.youtube-nocookie.com/embed/R94a_iS3e4M",
    thumbnailUrl: "https://i.ytimg.com/vi/R94a_iS3e4M/hqdefault.jpg",
    duration: "14:15",
    publishedAt: "8h ago",
    category: "masterclass",
    viewsFormatted: "420K views",
    description: "Parallel saturation, slap delay timing, lower octave doubling, and upper-mid presence boosts for pro vocal mixes.",
    tags: ["Vocal Mixing", "Warren Huart", "Audio Engineering", "Plugins"],
  },

  // 10. Adam Neely
  {
    id: "vid-10",
    title: "Sungazer Plus Live at the Blue Note: Advanced Modern Harmony & Rhythmic Phrasing",
    channelName: "Adam Neely",
    channelUrl: "https://www.youtube.com/@AdamNeely",
    videoUrl: "https://www.youtube.com/watch?v=MCNZ_YpQzfI",
    embedUrl: "https://www.youtube-nocookie.com/embed/MCNZ_YpQzfI",
    thumbnailUrl: "https://i.ytimg.com/vi/MCNZ_YpQzfI/hqdefault.jpg",
    duration: "52:14",
    publishedAt: "10h ago",
    category: "masterclass",
    viewsFormatted: "280K views",
    description: "Adam Neely and Sungazer demonstrate polyrhythmic structuring, microtonality, and live ensemble dynamics at the Blue Note NYC.",
    tags: ["Adam Neely", "Jazz", "Music Theory", "Live Concert"],
  },

  // 11. Trapital (TikTok Strategy)
  {
    id: "vid-11",
    title: "How Independent Artists Use Short-Form Video Algorithms to Scale Tour Grosses",
    channelName: "Trapital",
    channelUrl: "https://www.youtube.com/@Trapital",
    videoUrl: "https://www.youtube.com/watch?v=rKWHRVBhsZ4",
    embedUrl: "https://www.youtube-nocookie.com/embed/rKWHRVBhsZ4",
    thumbnailUrl: "https://i.ytimg.com/vi/rKWHRVBhsZ4/hqdefault.jpg",
    duration: "21:10",
    publishedAt: "12h ago",
    category: "essay",
    viewsFormatted: "145K views",
    description: "Converting viral short-form viewers into localized SMS/ticket buyers within 72 hours.",
    tags: ["TikTok", "Touring", "Trapital", "Viral Marketing"],
  },

  // 12. NPR Music (Mon Rovia)
  {
    id: "vid-12",
    title: "Mon Rovîa: NPR Music Tiny Desk Concert (Acoustic Folk & Indie Soul)",
    channelName: "NPR Music",
    channelUrl: "https://www.youtube.com/@NPRMusic",
    videoUrl: "https://www.youtube.com/watch?v=R2eOU7c7G_4",
    embedUrl: "https://www.youtube-nocookie.com/embed/R2eOU7c7G_4",
    thumbnailUrl: "https://i.ytimg.com/vi/R2eOU7c7G_4/hqdefault.jpg",
    duration: "18:30",
    publishedAt: "14h ago",
    category: "documentary",
    viewsFormatted: "190K views",
    description: "Mon Rovîa performs intimate, soothing acoustic vignettes blending Appalachian folk and West African soul.",
    tags: ["NPR Music", "Tiny Desk", "Mon Rovia", "Indie Folk"],
  },

  // 13. NPR Music (Mac Miller Legacy)
  {
    id: "vid-13",
    title: "Mac Miller: NPR Music Tiny Desk Concert (Featuring Thundercat)",
    channelName: "NPR Music",
    channelUrl: "https://www.youtube.com/@NPRMusic",
    videoUrl: "https://www.youtube.com/watch?v=ferZnZ0_46g",
    embedUrl: "https://www.youtube-nocookie.com/embed/ferZnZ0_46g",
    thumbnailUrl: "https://i.ytimg.com/vi/ferZnZ0_46g/hqdefault.jpg",
    duration: "17:30",
    publishedAt: "Today",
    category: "documentary",
    viewsFormatted: "120M views",
    description: "Mac Miller delivers an iconic, stripped-down live set featuring Thundercat on bass at the NPR Music office desk in Washington DC.",
    tags: ["NPR Music", "Tiny Desk", "Mac Miller", "Thundercat"],
  },
];
