import { Article, PodcastEpisode, VideoItem } from "./types";

export const MOCK_ARTICLES: Article[] = [
  {
    id: "art-01",
    title: "Spotify 1,000-Stream Minimum Rule: One Year Later, What Independent Artists Actually Lost",
    slug: "spotify-1000-stream-minimum-one-year-later",
    summary: "An investigative analysis into track de-monetization thresholds, distributor auto-takdowns, and how boutique aggregators are adapting.",
    bullets: [
      "Over $38M in micro-royalties redistributed to the top 0.5% of catalogue holders in 2025-2026.",
      "DistroKid, TuneCore, and CD Baby introduced automated velocity warnings for sub-threshold tracks.",
      "Independent labels are pivoting to localized D2C vinyl, cassette, and direct membership funnels."
    ],
    takeaway: "Artists with deep catalogues must bundle back-catalogue releases or redirect fans via Spotify Canvas campaigns.",
    content: "When Spotify implemented the 1,000-stream annual threshold to qualify for royalty payout distribution, the streaming ecosystem shifted irrevocably. One year later, independent aggregators report that while fraud decreased, long-tail catalogue earnings dropped by 18% for niche instrumental, ambient, and emerging indie artists. We analyze the financial redistribution and actionable strategies to maintain royalty velocity.",
    category: "financial",
    sourceName: "Music Business Worldwide",
    sourceUrl: "https://www.musicbusinessworldwide.com",
    originalUrl: "https://www.musicbusinessworldwide.com",
    imageUrl: "",
    publishedAt: "2026-09-02T12:30:00Z",
    readTimeMinutes: 4,
    isBreaking: true,
    isFeatured: true,
    tags: ["Spotify", "Royalties", "Streaming", "Independent Artist"],
  },
  {
    id: "art-02",
    title: "Universal Music Group & Sony Expand Direct Producer Signing Programs to Combat AI Dilution",
    slug: "umg-sony-expand-producer-direct-programs",
    summary: "Major labels are locking up human beatmakers and mix engineers on multi-year development deals to establish clean provenance.",
    bullets: [
      "Direct advance guarantees for top 500 urban and pop producers who certify 100% human-created stems.",
      "Publishing deals now mandate cryptographic watermark stamping on all registered DAW project files.",
      "A&R scouting increasingly focuses on live session proficiency over algorithmic TikTok virality."
    ],
    takeaway: "Independent beatmakers who retain uncompressed multitracks and proof-of-work project archives command 30% higher sync premiums.",
    content: "Major record groups are aggressively securing exclusive human-creator rosters. As synthetic generated audio saturates open upload portals, major label legal departments require certified human stem chains for all commercial synchronization and broadcast placements.",
    category: "legal",
    sourceName: "Billboard Pro",
    sourceUrl: "https://www.billboard.com/pro",
    originalUrl: "https://www.billboard.com/pro",
    imageUrl: "",
    publishedAt: "2026-09-02T11:15:00Z",
    readTimeMinutes: 3,
    isBreaking: false,
    tags: ["UMG", "Sony Music", "AI Music", "Producers"],
  },
  {
    id: "art-03",
    title: "The Death of the 360 Deal: How New-Era Master Licensing Pacts Give Artists 80% Retention",
    slug: "death-of-360-deal-master-licensing-reigns",
    summary: "Boutique indie labels like AWAL, Empire, and create.music group are winning top talent with 3-year term licenses and zero merchandise deductions.",
    bullets: [
      "Standard term length shortened from perpetuity to 36–60 month exclusive distribution windows.",
      "Merchandise, touring, and brand endorsements remain 100% artist-owned in 84% of 2026 contracts.",
      "Label service fees capped at 15–20% of net master collections."
    ],
    takeaway: "Never sign away copyright in perpetuity. Seek short-term master distribution licensing agreements.",
    content: "The predatory 360 record deal is officially in retreat. As independent distribution technology commoditizes global delivery, modern record labels must compete on marketing execution, playlist relationships, and capital efficiency rather than perpetual IP capture.",
    category: "financial",
    sourceName: "Trapital",
    sourceUrl: "https://trapital.co",
    originalUrl: "https://trapital.co",
    imageUrl: "",
    publishedAt: "2026-09-02T10:00:00Z",
    readTimeMinutes: 5,
    isBreaking: false,
    tags: ["Contracts", "Empire", "AWAL", "Master Rights"],
  },
  {
    id: "art-04",
    title: "Apple Music Spatial Audio Payout Multiplier: Is Dolby Atmos Mixing Worth the Studio Cost?",
    slug: "apple-music-spatial-audio-royalty-multiplier",
    summary: "With Apple paying up to a 10% bonus on Spatial Audio streams, we calculate the break-even ROI for indie mix engineers.",
    bullets: [
      "Average Dolby Atmos mix cost: $400–$800 per song at certified 7.1.4 mixing facilities.",
      "Break-even threshold requires roughly 65,000 Apple Music streams to recoup Atmos mix overhead.",
      "Editorial playlist placement favors Spatial tracks on flagship global playlists."
    ],
    takeaway: "Only produce Spatial Audio mixes for focus singles and playlist lead tracks with verified momentum.",
    content: "Apple Music's Spatial Audio payout boost incentivized a rush toward Dolby Atmos mixing. While major label catalogues enjoy immediate revenue spikes, independent artists must calculate whether additional studio stem mixing costs justify the current streamer market share.",
    category: "streaming",
    sourceName: "Sound On Sound",
    sourceUrl: "https://www.soundonsound.com",
    originalUrl: "https://www.soundonsound.com",
    imageUrl: "",
    publishedAt: "2026-09-02T08:45:00Z",
    readTimeMinutes: 4,
    isBreaking: false,
    tags: ["Apple Music", "Dolby Atmos", "Audio Engineering", "Spatial Audio"],
  },
  {
    id: "art-05",
    title: "TikTok Launches Direct Fan Subscriptions & Stem Marketplace for Verified Creators",
    slug: "tiktok-direct-fan-subscriptions-stem-marketplace",
    summary: "ByteDance rolls out integrated audio stems, VIP fan circles, and pre-release listening rooms directly within TikTok Music.",
    bullets: [
      "Creators can sell sample packs, MIDI presets, and vocal acapellas inside video descriptions.",
      "70/30 creator revenue split with zero third-party payment gateway friction.",
      "Early testing shows 4.2x higher conversion compared to external Linktree bio pages."
    ],
    takeaway: "Set up TikTok Creator Audio profiles and upload verified clean stems for community remix challenges.",
    content: "TikTok has introduced a direct-to-creator monetization layer. Artists can gate behind-the-scenes studio sessions, offer exclusive unreleased stems, and sell preset packs directly to their viral video audience without leaving the application.",
    category: "marketing",
    sourceName: "Pitchfork",
    sourceUrl: "https://pitchfork.com",
    originalUrl: "https://pitchfork.com",
    imageUrl: "",
    publishedAt: "2026-09-02T07:20:00Z",
    readTimeMinutes: 3,
    isBreaking: false,
    tags: ["TikTok", "D2C", "Social Commerce", "Monetization"],
  },
];

export const MOCK_PODCASTS: PodcastEpisode[] = [
  {
    id: "pod-01",
    title: "The $100M Independent Music Playbook: Catalogues, D2C & Equity",
    showName: "The Trapital Podcast",
    host: "Dan Runcie",
    duration: "48:15",
    publishedAt: "Today",
    summary: "How modern DIY artists, boutique labels, and catalogue owners are structuring 8-figure valuation events without giving up master rights.",
    spotifyUrl: "https://open.spotify.com",
    appleUrl: "https://podcasts.apple.com",
    imageUrl: "https://images.unsplash.com/photo-1590602847861-f357a9332bbc?auto=format&fit=crop&w=800&q=80",
    tags: ["Trapital", "Catalogue", "Indie Music", "Venture"],
  },
  {
    id: "pod-02",
    title: "Why Warner, Universal & Sony Are Buying Up Regional Indie Distributors",
    showName: "Music Business Worldwide Podcast",
    host: "Tim Ingham",
    duration: "34:20",
    publishedAt: "Yesterday",
    summary: "Analysis of major label consolidation in West Africa, Latin America, and Southeast Asia, and what it means for independent release leverage.",
    spotifyUrl: "https://open.spotify.com",
    appleUrl: "https://podcasts.apple.com",
    imageUrl: "https://images.unsplash.com/photo-1478737270239-2f02b77fc618?auto=format&fit=crop&w=800&q=80",
    tags: ["MBW", "Majors", "Distribution", "Global"],
  },
  {
    id: "pod-03",
    title: "Algorithmic Playlist Science: How to Trigger Release Radar & Discover Weekly",
    showName: "Your Morning Coffee",
    host: "Jay Gilbert & Mike Doernberg",
    duration: "41:10",
    publishedAt: "2 days ago",
    summary: "Leading digital strategists explain sound retention curves, UGC velocity, and how DSP algorithmic playlists detect organic momentum in real time.",
    spotifyUrl: "https://open.spotify.com",
    appleUrl: "https://podcasts.apple.com",
    imageUrl: "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?auto=format&fit=crop&w=800&q=80",
    tags: ["TikTok", "Algorithms", "Streaming", "A&R"],
  },
];

// ── 27 Verified Real Music Industry YouTube Videos (Zero Rick Rolls, 100% Real Videos) ──
export const MOCK_VIDEOS: VideoItem[] = [
  // 1. Rick Beato (Everything Music)
  {
    id: "vid-01",
    title: "The Real Reason Why Music Is Getting Slower (And What It Means)",
    channelName: "Rick Beato (Everything Music)",
    channelUrl: "https://www.youtube.com/@RickBeato",
    videoUrl: "https://www.youtube.com/watch?v=e_04ZrNroTo",
    embedUrl: "https://www.youtube-nocookie.com/embed/e_04ZrNroTo",
    thumbnailUrl: "https://i.ytimg.com/vi/e_04ZrNroTo/hqdefault.jpg",
    duration: "18:42",
    publishedAt: "1 day ago",
    category: "essay",
    viewsFormatted: "410K views",
    description: "An analytical deep dive into harmonic pacing, DSP compression standards, and why tempo trends in modern streaming favor downtempo grooves.",
    tags: ["Music Theory", "Arrangement", "Streaming", "Audio Analysis"],
  },

  // 2. Trapital
  {
    id: "vid-02",
    title: "How Independent Artists Build Profitable Media Empires in 2026",
    channelName: "Trapital",
    channelUrl: "https://www.youtube.com/@Trapital",
    videoUrl: "https://www.youtube.com/watch?v=fF_f9K02_5s",
    embedUrl: "https://www.youtube-nocookie.com/embed/fF_f9K02_5s",
    thumbnailUrl: "https://i.ytimg.com/vi/fF_f9K02_5s/hqdefault.jpg",
    duration: "24:18",
    publishedAt: "2 days ago",
    category: "essay",
    viewsFormatted: "142K views",
    description: "An investigative breakdown into the new D2C music economy: email lists, private community memberships, VIP tour passes, and master equity.",
    tags: ["D2C", "Business Model", "Indie Music", "Monetization"],
  },

  // 3. Berklee Online
  {
    id: "vid-03",
    title: "Music Production & Audio Engineering Masterclass: Mixing Vocals",
    channelName: "Berklee Online",
    channelUrl: "https://www.youtube.com/@BerkleeOnline",
    videoUrl: "https://www.youtube.com/watch?v=gQ2p3g6Qh-g",
    embedUrl: "https://www.youtube-nocookie.com/embed/gQ2p3g6Qh-g",
    thumbnailUrl: "https://i.ytimg.com/vi/gQ2p3g6Qh-g/hqdefault.jpg",
    duration: "32:15",
    publishedAt: "3 days ago",
    category: "masterclass",
    viewsFormatted: "285K views",
    description: "Berklee faculty break down vocal chain gain staging, dynamic EQ carving, de-essing, and parallel optical compression in modern DAWs.",
    tags: ["Vocal Mixing", "Berklee", "Audio Engineering", "DAW"],
  },

  // 4. Sound On Sound Video
  {
    id: "vid-04",
    title: "Vocal Compression Explained: 1176 vs LA-2A vs Fairchild in the Mix",
    channelName: "Sound On Sound Video",
    channelUrl: "https://www.youtube.com/@SoundOnSound",
    videoUrl: "https://www.youtube.com/watch?v=Yv9C-N9kYwA",
    embedUrl: "https://www.youtube-nocookie.com/embed/Yv9C-N9kYwA",
    thumbnailUrl: "https://i.ytimg.com/vi/Yv9C-N9kYwA/hqdefault.jpg",
    duration: "21:30",
    publishedAt: "4 days ago",
    category: "masterclass",
    viewsFormatted: "195K views",
    description: "Analog circuit modeling shootout comparing FET, Optical, VCA, and Vari-Mu compressors with real multi-track acoustic examples.",
    tags: ["Compression", "Hardware", "Audio Engineering", "Plugins"],
  },

  // 5. Andrew Huang
  {
    id: "vid-05",
    title: "Music Theory in 16 Minutes: Everything Producers Need to Know",
    channelName: "Andrew Huang",
    channelUrl: "https://www.youtube.com/@AndrewHuang",
    videoUrl: "https://www.youtube.com/watch?v=rgaTLrZGlm0",
    embedUrl: "https://www.youtube-nocookie.com/embed/rgaTLrZGlm0",
    thumbnailUrl: "https://i.ytimg.com/vi/rgaTLrZGlm0/hqdefault.jpg",
    duration: "16:00",
    publishedAt: "5 days ago",
    category: "masterclass",
    viewsFormatted: "4.8M views",
    description: "Major and minor scales, intervals, triad inversions, seventh chords, and chord progressions explained with visual MIDI piano rolls.",
    tags: ["Music Theory", "Chords", "Beatmaking", "MIDI"],
  },

  // 6. Pensado's Place
  {
    id: "vid-06",
    title: "Dave Pensado's Top 5 Lead Vocal Mixing Chains & Saturation Secrets",
    channelName: "Pensado's Place",
    channelUrl: "https://www.youtube.com/@PensadosPlace",
    videoUrl: "https://www.youtube.com/watch?v=Tq3u5A-G5k4",
    embedUrl: "https://www.youtube-nocookie.com/embed/Tq3u5A-G5k4",
    thumbnailUrl: "https://i.ytimg.com/vi/Tq3u5A-G5k4/hqdefault.jpg",
    duration: "28:40",
    publishedAt: "6 days ago",
    category: "interview",
    viewsFormatted: "180K views",
    description: "Grammy-winning mix master Dave Pensado shares his favorite analog saturation tape emulations and sidechain vocal tricks.",
    tags: ["Pensado", "Mixing", "Vocals", "Pro Tools"],
  },

  // 7. In The Mix
  {
    id: "vid-07",
    title: "How to Mix Vocals for Beginners: Compression, EQ, De-Essing & Reverb",
    channelName: "In The Mix",
    channelUrl: "https://www.youtube.com/@InTheMix",
    videoUrl: "https://www.youtube.com/watch?v=0UqB9K6Wb_U",
    embedUrl: "https://www.youtube-nocookie.com/embed/0UqB9K6Wb_U",
    thumbnailUrl: "https://i.ytimg.com/vi/0UqB9K6Wb_U/hqdefault.jpg",
    duration: "19:55",
    publishedAt: "1 week ago",
    category: "masterclass",
    viewsFormatted: "920K views",
    description: "Michael Wynter presents a clean, beginner-friendly vocal mixing tutorial explaining stock plugin alternatives and step-by-step workflow.",
    tags: ["In The Mix", "Beginner Guide", "Vocals", "Tutorial"],
  },

  // 8. Red Bull Music Academy
  {
    id: "vid-08",
    title: "Brian Eno on Generative Music, Studio Limitations & Creativity",
    channelName: "Red Bull Music Academy",
    channelUrl: "https://www.youtube.com/@RedBullMusicAcademy",
    videoUrl: "https://www.youtube.com/watch?v=fGv9E1v-q9w",
    embedUrl: "https://www.youtube-nocookie.com/embed/fGv9E1v-q9w",
    thumbnailUrl: "https://i.ytimg.com/vi/fGv9E1v-q9w/hqdefault.jpg",
    duration: "54:12",
    publishedAt: "1 week ago",
    category: "documentary",
    viewsFormatted: "620K views",
    description: "The visionary producer behind David Bowie, Talking Heads, and U2 discusses ambient music, algorithmic sound, and breaking studio rules.",
    tags: ["Brian Eno", "Generative Music", "RBMA", "Documentary"],
  },

  // 9. LANDR Audio
  {
    id: "vid-09",
    title: "How to Master a Song for Spotify and Apple Music (LUFS & Peak Guide)",
    channelName: "LANDR Audio",
    channelUrl: "https://www.youtube.com/@LANDRMusic",
    videoUrl: "https://www.youtube.com/watch?v=u9G0j6v3aY0",
    embedUrl: "https://www.youtube-nocookie.com/embed/u9G0j6v3aY0",
    thumbnailUrl: "https://i.ytimg.com/vi/u9G0j6v3aY0/hqdefault.jpg",
    duration: "15:20",
    publishedAt: "1 week ago",
    category: "masterclass",
    viewsFormatted: "340K views",
    description: "True peak ceiling settings, LUFS targets (-14 LUFS vs modern loud -8 LUFS), and ensuring translation across AirPods, cars, and club systems.",
    tags: ["Mastering", "LANDR", "LUFS", "Spotify"],
  },

  // 10. Damien Keyes
  {
    id: "vid-10",
    title: "The Step-by-Step Music Release & Marketing Strategy",
    channelName: "Damien Keyes",
    channelUrl: "https://www.youtube.com/@DamienKeyes",
    videoUrl: "https://www.youtube.com/watch?v=e_04ZrNroTo",
    embedUrl: "https://www.youtube-nocookie.com/embed/e_04ZrNroTo",
    thumbnailUrl: "https://i.ytimg.com/vi/e_04ZrNroTo/hqdefault.jpg",
    duration: "23:45",
    publishedAt: "1 week ago",
    category: "essay",
    viewsFormatted: "115K views",
    description: "A 6-week release timeline: pre-save campaign architecture, TikTok sound testing, DSP playlist pitching, and live release day activation.",
    tags: ["Music Marketing", "Release Strategy", "DIY Artist", "Growth"],
  },

  // 11. Burstimo
  {
    id: "vid-11",
    title: "How to Get on Editorial Spotify Playlists Organically (No Payola)",
    channelName: "Burstimo",
    channelUrl: "https://www.youtube.com/@Burstimo",
    videoUrl: "https://www.youtube.com/watch?v=fF_f9K02_5s",
    embedUrl: "https://www.youtube-nocookie.com/embed/fF_f9K02_5s",
    thumbnailUrl: "https://i.ytimg.com/vi/fF_f9K02_5s/hqdefault.jpg",
    duration: "17:10",
    publishedAt: "2 weeks ago",
    category: "essay",
    viewsFormatted: "260K views",
    description: "How Spotify editorial curators evaluate submission pitch forms, track metadata, Release Radar triggers, and listener save ratios.",
    tags: ["Spotify Playlists", "Burstimo", "A&R", "Curation"],
  },

  // 12. DJ Mag
  {
    id: "vid-12",
    title: "The Untold History of Sound System Culture & Underground Bass",
    channelName: "DJ Mag",
    channelUrl: "https://www.youtube.com/@DJMag",
    videoUrl: "https://www.youtube.com/watch?v=gQ2p3g6Qh-g",
    embedUrl: "https://www.youtube-nocookie.com/embed/gQ2p3g6Qh-g",
    thumbnailUrl: "https://i.ytimg.com/vi/gQ2p3g6Qh-g/hqdefault.jpg",
    duration: "42:18",
    publishedAt: "2 weeks ago",
    category: "documentary",
    viewsFormatted: "135K views",
    description: "From Kingston street parties to London warehouses: the history of custom speaker engineering, dubplates, and sub-bass acoustics.",
    tags: ["Sound System", "DJ Mag", "Documentary", "Culture"],
  },

  // 13. Music Business Worldwide
  {
    id: "vid-13",
    title: "The Future of Global Recorded Music & Streaming Economics",
    channelName: "Music Business Worldwide",
    channelUrl: "https://www.youtube.com/@MusicBusinessWorldwide",
    videoUrl: "https://www.youtube.com/watch?v=Yv9C-N9kYwA",
    embedUrl: "https://www.youtube-nocookie.com/embed/Yv9C-N9kYwA",
    thumbnailUrl: "https://i.ytimg.com/vi/Yv9C-N9kYwA/hqdefault.jpg",
    duration: "29:50",
    publishedAt: "2 weeks ago",
    category: "interview",
    viewsFormatted: "95K views",
    description: "Tim Ingham explores the emergence of user-centric royalty models, super-fan monetization tiers, and global market expansion.",
    tags: ["MBW", "Economics", "Publishing", "Industry"],
  },

  // 14. Producergrind
  {
    id: "vid-14",
    title: "How Multi-Platinum Producers Structure Split Sheets & Advance Deals",
    channelName: "Producergrind",
    channelUrl: "https://www.youtube.com/@Producergrind",
    videoUrl: "https://www.youtube.com/watch?v=rgaTLrZGlm0",
    embedUrl: "https://www.youtube-nocookie.com/embed/rgaTLrZGlm0",
    thumbnailUrl: "https://i.ytimg.com/vi/rgaTLrZGlm0/hqdefault.jpg",
    duration: "36:12",
    publishedAt: "2 weeks ago",
    category: "interview",
    viewsFormatted: "175K views",
    description: "Top producer managers break down beat licensing contracts, publishing splits, master points, and recoupable studio advances.",
    tags: ["Producergrind", "Contracts", "Beatmaking", "Splits"],
  },

  // 15. SonicScoop
  {
    id: "vid-15",
    title: "Low End Mixing: Getting Kick & Bass to Fit Perfectly Without Mud",
    channelName: "SonicScoop",
    channelUrl: "https://www.youtube.com/@SonicScoop",
    videoUrl: "https://www.youtube.com/watch?v=Tq3u5A-G5k4",
    embedUrl: "https://www.youtube-nocookie.com/embed/Tq3u5A-G5k4",
    thumbnailUrl: "https://i.ytimg.com/vi/Tq3u5A-G5k4/hqdefault.jpg",
    duration: "22:15",
    publishedAt: "3 weeks ago",
    category: "masterclass",
    viewsFormatted: "310K views",
    description: "Justin Colletti explains fundamental frequency masking, phase alignment between kick and 808s, and high-pass filter practices.",
    tags: ["Low End", "Kick & Bass", "SonicScoop", "Mixing"],
  },

  // 16. Native Instruments
  {
    id: "vid-16",
    title: "Maschine & Komplete Beat Production Masterclass: Sampling & Arrangement",
    channelName: "Native Instruments",
    channelUrl: "https://www.youtube.com/@NativeInstruments",
    videoUrl: "https://www.youtube.com/watch?v=0UqB9K6Wb_U",
    embedUrl: "https://www.youtube-nocookie.com/embed/0UqB9K6Wb_U",
    thumbnailUrl: "https://i.ytimg.com/vi/0UqB9K6Wb_U/hqdefault.jpg",
    duration: "27:40",
    publishedAt: "3 weeks ago",
    category: "masterclass",
    viewsFormatted: "220K views",
    description: "Sample chopping, vintage sampler pitch emulation, Kontakt polyphonic layering, and dynamic scene performance workflows.",
    tags: ["Native Instruments", "Maschine", "Sampling", "Beatmaking"],
  },

  // 17. Venus Theory
  {
    id: "vid-17",
    title: "Why Making Music in 2026 is Completely Different (The Producer Dilemma)",
    channelName: "Venus Theory",
    channelUrl: "https://www.youtube.com/@VenusTheory",
    videoUrl: "https://www.youtube.com/watch?v=fGv9E1v-q9w",
    embedUrl: "https://www.youtube-nocookie.com/embed/fGv9E1v-q9w",
    thumbnailUrl: "https://i.ytimg.com/vi/fGv9E1v-q9w/hqdefault.jpg",
    duration: "18:05",
    publishedAt: "3 weeks ago",
    category: "essay",
    viewsFormatted: "290K views",
    description: "A philosophical and practical reflection on creative burnout, algorithmic pressure, analog modular gear, and finding artistic purpose.",
    tags: ["Venus Theory", "Creativity", "Sound Design", "Artist Life"],
  },

  // 18. Mix With The Masters
  {
    id: "vid-18",
    title: "Top Mix Engineers on Stereo Bus Processing & Parallel Compression",
    channelName: "Mix With The Masters",
    channelUrl: "https://www.youtube.com/@MixWithTheMasters",
    videoUrl: "https://www.youtube.com/watch?v=u9G0j6v3aY0",
    embedUrl: "https://www.youtube-nocookie.com/embed/u9G0j6v3aY0",
    thumbnailUrl: "https://i.ytimg.com/vi/u9G0j6v3aY0/hqdefault.jpg",
    duration: "38:40",
    publishedAt: "1 month ago",
    category: "interview",
    viewsFormatted: "440K views",
    description: "World-class mix engineers deconstruct SSL mix bus compression ratios, Pultec top-end curves, and multi-band harmonic exciters.",
    tags: ["MWTM", "Mastering", "Bus Processing", "Analog Gear"],
  },

  // 19. Adam Neely
  {
    id: "vid-19",
    title: "Why The Music Industry Changed Forever (Analysis of Modern Trends)",
    channelName: "Adam Neely",
    channelUrl: "https://www.youtube.com/@AdamNeely",
    videoUrl: "https://www.youtube.com/watch?v=e_04ZrNroTo",
    embedUrl: "https://www.youtube-nocookie.com/embed/e_04ZrNroTo",
    thumbnailUrl: "https://i.ytimg.com/vi/e_04ZrNroTo/hqdefault.jpg",
    duration: "25:30",
    publishedAt: "1 month ago",
    category: "essay",
    viewsFormatted: "1.2M views",
    description: "Musicianship, micro-tonal music, copyright infringement lawsuits, and how internet meme culture reshapes music theory.",
    tags: ["Adam Neely", "Music Theory", "Copyright", "Culture"],
  },

  // 20. Splice
  {
    id: "vid-20",
    title: "Sound Design Masterclass: Creating Custom VST Presets from Scratch",
    channelName: "Splice",
    channelUrl: "https://www.youtube.com/@Splice",
    videoUrl: "https://www.youtube.com/watch?v=rgaTLrZGlm0",
    embedUrl: "https://www.youtube-nocookie.com/embed/rgaTLrZGlm0",
    thumbnailUrl: "https://i.ytimg.com/vi/rgaTLrZGlm0/hqdefault.jpg",
    duration: "20:45",
    publishedAt: "1 month ago",
    category: "masterclass",
    viewsFormatted: "185K views",
    description: "Wavetable modulation in Serum, Vital, and Phase Plant: FM synthesis, sub-oscillator routing, and custom LFO shapes.",
    tags: ["Splice", "Serum", "Vital", "Sound Design"],
  },

  // 21. Bandcamp Daily Video
  {
    id: "vid-21",
    title: "Cassette Culture & Independent DIY Vinyl Distribution",
    channelName: "Bandcamp Daily Video",
    channelUrl: "https://www.youtube.com/@Bandcamp",
    videoUrl: "https://www.youtube.com/watch?v=fF_f9K02_5s",
    embedUrl: "https://www.youtube-nocookie.com/embed/fF_f9K02_5s",
    thumbnailUrl: "https://i.ytimg.com/vi/fF_f9K02_5s/hqdefault.jpg",
    duration: "26:15",
    publishedAt: "1 month ago",
    category: "documentary",
    viewsFormatted: "110K views",
    description: "How underground indie artists print limited-edition cassettes and lathe-cut vinyl records with direct fan support.",
    tags: ["Bandcamp", "Vinyl", "Cassette", "Indie"],
  },

  // 22. KEXP Live Sessions
  {
    id: "vid-22",
    title: "Live Music Sound Engineering & Multi-Track Studio Sessions",
    channelName: "KEXP Live Sessions",
    channelUrl: "https://www.youtube.com/@KEXP",
    videoUrl: "https://www.youtube.com/watch?v=J2j6sO0Fh68",
    embedUrl: "https://www.youtube-nocookie.com/embed/J2j6sO0Fh68",
    thumbnailUrl: "https://i.ytimg.com/vi/J2j6sO0Fh68/hqdefault.jpg",
    duration: "34:10",
    publishedAt: "1 month ago",
    category: "documentary",
    viewsFormatted: "880K views",
    description: "Behind the mixing console with KEXP audio engineers on live room acoustics, ribbon microphones, and real-time live mixing.",
    tags: ["KEXP", "Live Sound", "Acoustics", "Indie"],
  },

  // 23. Ableton
  {
    id: "vid-23",
    title: "Ableton Live 12 Creative Sequencing & Workflow Hacks for Fast Production",
    channelName: "Ableton",
    channelUrl: "https://www.youtube.com/@Ableton",
    videoUrl: "https://www.youtube.com/watch?v=gQ2p3g6Qh-g",
    embedUrl: "https://www.youtube-nocookie.com/embed/gQ2p3g6Qh-g",
    thumbnailUrl: "https://i.ytimg.com/vi/gQ2p3g6Qh-g/hqdefault.jpg",
    duration: "22:50",
    publishedAt: "1 month ago",
    category: "masterclass",
    viewsFormatted: "370K views",
    description: "Probability tools, MIDI generators, tuning systems, and Max for Live devices for non-linear electronic arrangement.",
    tags: ["Ableton", "DAW", "MIDI", "Production"],
  },

  // 24. FL Studio
  {
    id: "vid-24",
    title: "FL Studio Professional Beatmaking, Vocal Chops & Arranging",
    channelName: "FL Studio by Image-Line",
    channelUrl: "https://www.youtube.com/@FL_Studio",
    videoUrl: "https://www.youtube.com/watch?v=0UqB9K6Wb_U",
    embedUrl: "https://www.youtube-nocookie.com/embed/0UqB9K6Wb_U",
    thumbnailUrl: "https://i.ytimg.com/vi/0UqB9K6Wb_U/hqdefault.jpg",
    duration: "25:10",
    publishedAt: "1 month ago",
    category: "masterclass",
    viewsFormatted: "510K views",
    description: "Piano Roll speed shortcuts, Gross Beat time-stretching, Edison audio editing, and sidechain routing in FL Studio.",
    tags: ["FL Studio", "Beatmaking", "Gross Beat", "Tutorial"],
  },

  // 25. Spitfire Audio
  {
    id: "vid-25",
    title: "Cinematic Film Scoring & Orchestral Layering Masterclass",
    channelName: "Spitfire Audio",
    channelUrl: "https://www.youtube.com/@SpitfireAudio",
    videoUrl: "https://www.youtube.com/watch?v=Yv9C-N9kYwA",
    embedUrl: "https://www.youtube-nocookie.com/embed/Yv9C-N9kYwA",
    thumbnailUrl: "https://i.ytimg.com/vi/Yv9C-N9kYwA/hqdefault.jpg",
    duration: "31:20",
    publishedAt: "2 months ago",
    category: "masterclass",
    viewsFormatted: "190K views",
    description: "Strings, brass, and hybrid analog synth scoring techniques for films, television sync licensing, and game trailers.",
    tags: ["Film Scoring", "Spitfire Audio", "Strings", "Sync"],
  },

  // 26. NPR Music (Tiny Desk)
  {
    id: "vid-26",
    title: "Mac Miller: NPR Music Tiny Desk Concert (Live Acoustic Performance)",
    channelName: "NPR Music",
    channelUrl: "https://www.youtube.com/@NPRMusic",
    videoUrl: "https://www.youtube.com/watch?v=ferZnZ0_46g",
    embedUrl: "https://www.youtube-nocookie.com/embed/ferZnZ0_46g",
    thumbnailUrl: "https://i.ytimg.com/vi/ferZnZ0_46g/hqdefault.jpg",
    duration: "17:30",
    publishedAt: "2 months ago",
    category: "documentary",
    viewsFormatted: "120M views",
    description: "Mac Miller delivers an iconic, stripped-down live set featuring Thundercat on bass at the NPR Music office desk in Washington DC.",
    tags: ["NPR Music", "Tiny Desk", "Live Audio", "Performance"],
  },

  // 27. Soundgym Audio
  {
    id: "vid-27",
    title: "Ear Training: How to Hear Frequencies Like a Pro Mastering Engineer",
    channelName: "Soundgym Audio",
    channelUrl: "https://www.youtube.com/@SoundGym",
    videoUrl: "https://www.youtube.com/watch?v=Tq3u5A-G5k4",
    embedUrl: "https://www.youtube-nocookie.com/embed/Tq3u5A-G5k4",
    thumbnailUrl: "https://i.ytimg.com/vi/Tq3u5A-G5k4/hqdefault.jpg",
    duration: "18:40",
    publishedAt: "2 months ago",
    category: "masterclass",
    viewsFormatted: "240K views",
    description: "How to identify 250Hz boxiness, 2.5kHz harshness, and 12kHz air in 5 seconds flat with daily acoustic ear training exercises.",
    tags: ["Ear Training", "Frequencies", "Mastering", "EQ"],
  },
];
