import { PlatformResource } from "./types";

export const TOP_100_PLATFORMS: PlatformResource[] = [
  // ============================================================================
  // PILLAR 1: TRADE & BUSINESS JOURNALISM (20 Platforms)
  // ============================================================================
  {
    id: "plat-mbw",
    name: "Music Business Worldwide",
    slug: "music-business-worldwide",
    pillar: "Trade & Business Journalism",
    category: "financial",
    tier: "tier1",
    websiteUrl: "https://www.musicbusinessworldwide.com",
    rssFeedUrl: "https://www.musicbusinessworldwide.com/feed/",
    youtubeChannelUrl: "https://www.youtube.com/@MusicBusinessWorldwide",
    contentType: "Articles",
    dailyPostFrequency: 8,
    scrapeStatus: "active",
    priorityRank: 1,
    description: "The premier global business news information service for the music industry.",
    editorialNotes: "Primary authority for major label financials, streaming payouts, and catalogue M&A.",
  },
  {
    id: "plat-billboard-biz",
    name: "Billboard Pro",
    slug: "billboard-pro",
    pillar: "Trade & Business Journalism",
    category: "financial",
    tier: "tier1",
    websiteUrl: "https://www.billboard.com/pro",
    rssFeedUrl: "https://www.billboard.com/c/business/feed/",
    youtubeChannelUrl: "https://www.youtube.com/@Billboard",
    contentType: "Articles",
    dailyPostFrequency: 12,
    scrapeStatus: "active",
    priorityRank: 2,
    description: "Essential intelligence for the music business, chart data, and executive reporting.",
    editorialNotes: "Benchmark for Hot 100 tracking, live touring revenues, and executive moves.",
  },
  {
    id: "plat-hits-daily-double",
    name: "Hits Daily Double",
    slug: "hits-daily-double",
    pillar: "Trade & Business Journalism",
    category: "financial",
    tier: "tier1",
    websiteUrl: "https://hitsdailydouble.com",
    rssFeedUrl: "https://hitsdailydouble.com/rss",
    contentType: "Articles",
    dailyPostFrequency: 10,
    scrapeStatus: "active",
    priorityRank: 3,
    description: "Music industry insider news, sales rumors, A&R radar, and chart projections.",
    editorialNotes: "Top publication for label negotiations, album projections, and A&R rumormill.",
  },
  {
    id: "plat-variety-music",
    name: "Variety Music",
    slug: "variety-music",
    pillar: "Trade & Business Journalism",
    category: "financial",
    tier: "tier1",
    websiteUrl: "https://variety.com/c/music",
    rssFeedUrl: "https://variety.com/v/music/feed/",
    contentType: "Articles",
    dailyPostFrequency: 6,
    scrapeStatus: "active",
    priorityRank: 4,
    description: "Entertainment industry business news covering major music deals, film syncs, and executive leadership.",
    editorialNotes: "Authoritative sync, Grammy coverage, and label executive transitions.",
  },
  {
    id: "plat-digital-music-news",
    name: "Digital Music News",
    slug: "digital-music-news",
    pillar: "Trade & Business Journalism",
    category: "financial",
    tier: "tier1",
    websiteUrl: "https://www.digitalmusicnews.com",
    rssFeedUrl: "https://www.digitalmusicnews.com/feed/",
    contentType: "Articles",
    dailyPostFrequency: 9,
    scrapeStatus: "active",
    priorityRank: 5,
    description: "Information authority for executives in digital music, streaming copyright, and music tech.",
    editorialNotes: "Aggressive coverage of copyright lawsuits, Spotify dispute filings, and distributor metrics.",
  },
  {
    id: "plat-cmu",
    name: "Complete Music Update (CMU)",
    slug: "complete-music-update",
    pillar: "Trade & Business Journalism",
    category: "financial",
    tier: "tier1",
    websiteUrl: "https://completemusicupdate.com",
    rssFeedUrl: "https://completemusicupdate.com/feed/",
    contentType: "Articles",
    dailyPostFrequency: 5,
    scrapeStatus: "active",
    priorityRank: 6,
    description: "Clear, concise analysis of the commercial and legal developments shaping the global music business.",
    editorialNotes: "Specialist coverage of UK/EU copyright directives and streaming regulation.",
  },
  {
    id: "plat-pollstar",
    name: "Pollstar",
    slug: "pollstar",
    pillar: "Trade & Business Journalism",
    category: "financial",
    tier: "tier1",
    websiteUrl: "https://www.pollstar.com",
    rssFeedUrl: "https://www.pollstar.com/feed",
    contentType: "Research & Data",
    dailyPostFrequency: 6,
    scrapeStatus: "active",
    priorityRank: 7,
    description: "The concert industry's leading publication tracking worldwide tour grosses, venues, and festival box offices.",
    editorialNotes: "Live music touring benchmark, ticketing data, and arena routing analysis.",
  },
  {
    id: "plat-music-week",
    name: "Music Week",
    slug: "music-week",
    pillar: "Trade & Business Journalism",
    category: "financial",
    tier: "tier1",
    websiteUrl: "https://www.musicweek.com",
    rssFeedUrl: "https://www.musicweek.com/rss",
    contentType: "Articles",
    dailyPostFrequency: 7,
    scrapeStatus: "active",
    priorityRank: 8,
    description: "UK trade bible for the commercial record industry, charts, and sync licensing.",
    editorialNotes: "Essential for European distribution and UK Official Charts telemetry.",
  },
  {
    id: "plat-record-of-the-day",
    name: "Record of the Day",
    slug: "record-of-the-day",
    pillar: "Trade & Business Journalism",
    category: "financial",
    tier: "tier2",
    websiteUrl: "https://www.recordoftheday.com",
    rssFeedUrl: "https://www.recordoftheday.com/feed",
    contentType: "Articles",
    dailyPostFrequency: 4,
    scrapeStatus: "active",
    priorityRank: 9,
    description: "Independent music consultancy, daily news digest, and buzz track discovery.",
    editorialNotes: "Focus on A&R scouting and UK broadcast play-listing.",
  },
  {
    id: "plat-celebrity-access",
    name: "CelebrityAccess",
    slug: "celebrity-access",
    pillar: "Trade & Business Journalism",
    category: "financial",
    tier: "tier2",
    websiteUrl: "https://celebrityaccess.com",
    rssFeedUrl: "https://celebrityaccess.com/feed/",
    contentType: "Articles",
    dailyPostFrequency: 5,
    scrapeStatus: "active",
    priorityRank: 10,
    description: "Live touring profiles, talent buyer directories, agent rosters, and festival booking news.",
    editorialNotes: "Crucial for booking agents, venue managers, and live promoters.",
  },
  {
    id: "plat-iq-mag",
    name: "IQ Magazine",
    slug: "iq-magazine",
    pillar: "Trade & Business Journalism",
    category: "financial",
    tier: "tier2",
    websiteUrl: "https://www.iq-mag.net",
    rssFeedUrl: "https://www.iq-mag.net/feed/",
    contentType: "Articles",
    dailyPostFrequency: 4,
    scrapeStatus: "active",
    priorityRank: 11,
    description: "International live music trade intelligence, festival sustainability, and production tech.",
    editorialNotes: "Global festival market analysis and touring logistics.",
  },
  {
    id: "plat-berklee-journal",
    name: "Music Business Journal (Berklee)",
    slug: "music-business-journal-berklee",
    pillar: "Trade & Business Journalism",
    category: "financial",
    tier: "tier2",
    websiteUrl: "https://www.thembj.org",
    rssFeedUrl: "https://www.thembj.org/feed/",
    contentType: "Research & Data",
    dailyPostFrequency: 2,
    scrapeStatus: "active",
    priorityRank: 12,
    description: "Academic and investigative journal examining economic shifts in the music economy.",
    editorialNotes: "Rigorous research on publishing royalties, antitrust, and streaming micro-economics.",
  },
  {
    id: "plat-lefsetz",
    name: "The Lefsetz Letter",
    slug: "the-lefsetz-letter",
    pillar: "Trade & Business Journalism",
    category: "financial",
    tier: "tier2",
    websiteUrl: "https://lefsetz.com",
    rssFeedUrl: "https://lefsetz.com/feed/",
    contentType: "Articles",
    dailyPostFrequency: 2,
    scrapeStatus: "active",
    priorityRank: 13,
    description: "Bob Lefsetz's influential, unfiltered commentary on music industry power dynamics and tech shifts.",
    editorialNotes: "Must-read for major label heads, managers, and entertainment attorneys.",
  },
  {
    id: "plat-soundcharts-blog",
    name: "Soundcharts Blog",
    slug: "soundcharts-blog",
    pillar: "Trade & Business Journalism",
    category: "streaming",
    tier: "tier2",
    websiteUrl: "https://soundcharts.com/blog",
    rssFeedUrl: "https://soundcharts.com/blog/rss",
    contentType: "Research & Data",
    dailyPostFrequency: 2,
    scrapeStatus: "active",
    priorityRank: 14,
    description: "Market telemetry, streaming data analysis, radio airplay tracking, and playlist insights.",
    editorialNotes: "In-depth case studies on playlist velocity and global market expansion.",
  },
  {
    id: "plat-chartmetric-blog",
    name: "Chartmetric Blog (How Music Charts)",
    slug: "chartmetric-blog",
    pillar: "Trade & Business Journalism",
    category: "streaming",
    tier: "tier2",
    websiteUrl: "https://blog.chartmetric.com",
    rssFeedUrl: "https://blog.chartmetric.com/rss/",
    contentType: "Research & Data",
    dailyPostFrequency: 3,
    scrapeStatus: "active",
    priorityRank: 15,
    description: "Data-driven music industry insights, genre migration reports, and cross-platform growth metrics.",
    editorialNotes: "Essential for tracking audience demographics and algorithmic trigger curves.",
  },
  {
    id: "plat-billboard-country",
    name: "Billboard Country & Regional Desks",
    slug: "billboard-regional-desks",
    pillar: "Trade & Business Journalism",
    category: "financial",
    tier: "tier2",
    websiteUrl: "https://www.billboard.com/c/country/",
    rssFeedUrl: "https://www.billboard.com/c/country/feed/",
    contentType: "Articles",
    dailyPostFrequency: 4,
    scrapeStatus: "active",
    priorityRank: 16,
    description: "Specialized coverage of Country, Latin, and Afrobeats market dominance.",
    editorialNotes: "Regional market expansion and terrestrial radio impact.",
  },
  {
    id: "plat-music-dish",
    name: "MusicDish e-Center",
    slug: "musicdish",
    pillar: "Trade & Business Journalism",
    category: "marketing",
    tier: "tier3",
    websiteUrl: "http://musicdish.com",
    rssFeedUrl: "http://musicdish.com/rss.xml",
    contentType: "Articles",
    dailyPostFrequency: 2,
    scrapeStatus: "active",
    priorityRank: 17,
    description: "International music industry bridge connecting Western markets with Greater China & Asia.",
    editorialNotes: "Crucial for East Asian touring, NetEase/QQ Music DSP landscape.",
  },
  {
    id: "plat-routenote-blog",
    name: "RouteNote Blog",
    slug: "routenote-blog",
    pillar: "Trade & Business Journalism",
    category: "streaming",
    tier: "tier3",
    websiteUrl: "https://routenote.com/blog",
    rssFeedUrl: "https://routenote.com/blog/feed/",
    contentType: "Articles",
    dailyPostFrequency: 5,
    scrapeStatus: "active",
    priorityRank: 18,
    description: "Digital music distribution trends, DSP payout changes, and indie artist guides.",
    editorialNotes: "Practical updates on release delivery windows and DSP algorithmic updates.",
  },
  {
    id: "plat-a-journal-of-musical-things",
    name: "A Journal of Musical Things (Alan Cross)",
    slug: "alan-cross-journal",
    pillar: "Trade & Business Journalism",
    category: "financial",
    tier: "tier3",
    websiteUrl: "https://www.ajournalofmusicalthings.com",
    rssFeedUrl: "https://www.ajournalofmusicalthings.com/feed/",
    contentType: "Articles",
    dailyPostFrequency: 4,
    scrapeStatus: "active",
    priorityRank: 19,
    description: "Broad-spectrum analysis of music industry economics, vinyl sales records, and tech disruption.",
    editorialNotes: "Great perspective on physical format resurgence and consumer listening behavior.",
  },
  {
    id: "plat-hypebot-trade",
    name: "Hypebot Industry Desk",
    slug: "hypebot-trade",
    pillar: "Trade & Business Journalism",
    category: "financial",
    tier: "tier1",
    websiteUrl: "https://www.hypebot.com",
    rssFeedUrl: "https://www.hypebot.com/hypebot/atom.xml",
    contentType: "Articles",
    dailyPostFrequency: 8,
    scrapeStatus: "active",
    priorityRank: 20,
    description: "The intersection of music, technology, and indie artist empowering models.",
    editorialNotes: "Foundational publication for music-tech venture and D2C marketing.",
  },

  // ============================================================================
  // PILLAR 2: INDIE STRATEGY, D2C, ROYALTIES & CREATOR ECONOMY (20 Platforms)
  // ============================================================================
  {
    id: "plat-trapital",
    name: "Trapital",
    slug: "trapital",
    pillar: "Indie Strategy & D2C",
    category: "financial",
    tier: "tier1",
    websiteUrl: "https://trapital.co",
    rssFeedUrl: "https://trapital.co/feed/",
    youtubeChannelUrl: "https://www.youtube.com/@Trapital",
    contentType: "Multi-Format",
    dailyPostFrequency: 3,
    scrapeStatus: "active",
    priorityRank: 21,
    description: "Business essays and podcasts dissecting hip-hop business, D2C fan clubs, and creator capital.",
    editorialNotes: "Top tier strategic teardowns by Dan Runcie on master ownership and D2C scale.",
  },
  {
    id: "plat-water-and-music",
    name: "Water & Music",
    slug: "water-and-music",
    pillar: "Indie Strategy & D2C",
    category: "tech-ai",
    tier: "tier1",
    websiteUrl: "https://waterandmusic.com",
    rssFeedUrl: "https://waterandmusic.substack.com/feed",
    contentType: "Research & Data",
    dailyPostFrequency: 2,
    scrapeStatus: "active",
    priorityRank: 22,
    description: "Collaborative research network tracking the cutting edge of music tech, Web3, and AI models.",
    editorialNotes: "Deepest academic datasets on synthetic voice rights and AI copyright licensing.",
  },
  {
    id: "plat-midia-research",
    name: "MIDiA Research",
    slug: "midia-research",
    pillar: "Indie Strategy & D2C",
    category: "financial",
    tier: "tier1",
    websiteUrl: "https://www.midiaresearch.com/blog",
    rssFeedUrl: "https://www.midiaresearch.com/blog/rss",
    contentType: "Research & Data",
    dailyPostFrequency: 3,
    scrapeStatus: "active",
    priorityRank: 23,
    description: "Global media and entertainment market intelligence, streaming subscriber forecasts, and creator economics.",
    editorialNotes: "Authoritative annual reports on independent label market share vs major label share.",
  },
  {
    id: "plat-diy-musician",
    name: "DIY Musician Blog (CD Baby)",
    slug: "diy-musician-cdbaby",
    pillar: "Indie Strategy & D2C",
    category: "tutorials",
    tier: "tier1",
    websiteUrl: "https://diymusician.cdbaby.com",
    rssFeedUrl: "https://diymusician.cdbaby.com/feed/",
    youtubeChannelUrl: "https://www.youtube.com/@cdbaby",
    contentType: "Articles",
    dailyPostFrequency: 4,
    scrapeStatus: "active",
    priorityRank: 24,
    description: "Actionable guides on distribution, copyright registration, sync pitching, and album release timelines.",
    editorialNotes: "Practical playbooks for independent musicians navigating distributor portals.",
  },
  {
    id: "plat-aris-take",
    name: "Ari's Take",
    slug: "aris-take",
    pillar: "Indie Strategy & D2C",
    category: "financial",
    tier: "tier1",
    websiteUrl: "https://aristake.com",
    rssFeedUrl: "https://aristake.com/feed/",
    youtubeChannelUrl: "https://www.youtube.com/@ArisTake",
    contentType: "Multi-Format",
    dailyPostFrequency: 2,
    scrapeStatus: "active",
    priorityRank: 25,
    description: "Independent music management advice, distributor comparisons, sync licensing, and copyright fundamentals.",
    editorialNotes: "Creator of the definitive annual Music Distributor Comparison Review.",
  },
  {
    id: "plat-soundfly",
    name: "Soundfly Flypaper",
    slug: "soundfly-flypaper",
    pillar: "Indie Strategy & D2C",
    category: "tutorials",
    tier: "tier2",
    websiteUrl: "https://flypaper.soundfly.com",
    rssFeedUrl: "https://flypaper.soundfly.com/feed/",
    contentType: "Articles",
    dailyPostFrequency: 3,
    scrapeStatus: "active",
    priorityRank: 26,
    description: "In-depth articles on songwriting, advanced music theory, vocal production, and creative career management.",
    editorialNotes: "Superb balance of creative craft tutorials and practical career strategy.",
  },
  {
    id: "plat-symphonic-blog",
    name: "Symphonic Distribution Blog",
    slug: "symphonic-blog",
    pillar: "Indie Strategy & D2C",
    category: "streaming",
    tier: "tier2",
    websiteUrl: "https://blog.symphonic.com",
    rssFeedUrl: "https://blog.symphonic.com/feed/",
    contentType: "Articles",
    dailyPostFrequency: 3,
    scrapeStatus: "active",
    priorityRank: 27,
    description: "Independent distributor blog covering DSP pitching, marketing strategies, and music rights management.",
    editorialNotes: "Strong coverage of Latin, Urban, and Electronic streaming strategies.",
  },
  {
    id: "plat-cyber-pr",
    name: "Cyber PR Music",
    slug: "cyber-pr-music",
    pillar: "Indie Strategy & D2C",
    category: "marketing",
    tier: "tier2",
    websiteUrl: "https://www.cyberprmusic.com/blog",
    rssFeedUrl: "https://www.cyberprmusic.com/feed/",
    contentType: "Articles",
    dailyPostFrequency: 2,
    scrapeStatus: "active",
    priorityRank: 28,
    description: "Ariel Hyatt's digital PR, social media roadmap, email list growth, and crowdfunding frameworks.",
    editorialNotes: "Focus on fan email capture, newsletter monetization, and PR pitching.",
  },
  {
    id: "plat-bandzoogle-blog",
    name: "Bandzoogle Blog",
    slug: "bandzoogle-blog",
    pillar: "Indie Strategy & D2C",
    category: "marketing",
    tier: "tier2",
    websiteUrl: "https://bandzoogle.com/blog",
    rssFeedUrl: "https://bandzoogle.com/blog.rss",
    contentType: "Articles",
    dailyPostFrequency: 2,
    scrapeStatus: "active",
    priorityRank: 29,
    description: "Direct-to-fan sales, band website optimization, merchandise fulfillment, and fan subscriptions.",
    editorialNotes: "Authoritative D2C merchandise tips and website conversion tactics.",
  },
  {
    id: "plat-tunecore-blog",
    name: "TuneCore Blog",
    slug: "tunecore-blog",
    pillar: "Indie Strategy & D2C",
    category: "financial",
    tier: "tier2",
    websiteUrl: "https://www.tunecore.com/blog",
    rssFeedUrl: "https://www.tunecore.com/feed",
    contentType: "Articles",
    dailyPostFrequency: 3,
    scrapeStatus: "active",
    priorityRank: 30,
    description: "Independent artist guides, publishing administration, Spotify Canvas tips, and royalty collection.",
    editorialNotes: "Tips for managing global publishing administration and mechanicals.",
  },
  {
    id: "plat-distrokid-news",
    name: "DistroKid Newsroom & Guides",
    slug: "distrokid-newsroom",
    pillar: "Indie Strategy & D2C",
    category: "streaming",
    tier: "tier2",
    websiteUrl: "https://news.distrokid.com",
    rssFeedUrl: "https://news.distrokid.com/feed",
    contentType: "Articles",
    dailyPostFrequency: 2,
    scrapeStatus: "active",
    priorityRank: 31,
    description: "Updates on DSP delivery, automated split payouts, Dolby Atmos delivery, and streaming verification.",
    editorialNotes: "High-volume aggregator release management updates.",
  },
  {
    id: "plat-awal-blog",
    name: "AWAL Insights",
    slug: "awal-insights",
    pillar: "Indie Strategy & D2C",
    category: "financial",
    tier: "tier2",
    websiteUrl: "https://www.awal.com/blog",
    rssFeedUrl: "https://www.awal.com/feed.xml",
    contentType: "Articles",
    dailyPostFrequency: 2,
    scrapeStatus: "active",
    priorityRank: 32,
    description: "Artist development case studies, global marketing blueprints, and streaming trajectory breakdowns.",
    editorialNotes: "Excellent boutique label service breakdowns (Lauv, Little Simz).",
  },
  {
    id: "plat-venice-music",
    name: "Venice Music Community",
    slug: "venice-music-community",
    pillar: "Indie Strategy & D2C",
    category: "financial",
    tier: "tier2",
    websiteUrl: "https://veniceplaybook.com",
    rssFeedUrl: "https://veniceplaybook.com/feed",
    contentType: "Articles",
    dailyPostFrequency: 2,
    scrapeStatus: "active",
    priorityRank: 33,
    description: "Troy Carter's independent artist distribution platform, synchronization network, and manager resources.",
    editorialNotes: "Modern A&R intelligence and sync master placement strategies.",
  },
  {
    id: "plat-stem-blog",
    name: "Stem Dissect",
    slug: "stem-dissect",
    pillar: "Indie Strategy & D2C",
    category: "financial",
    tier: "tier2",
    websiteUrl: "https://stem.is/blog",
    rssFeedUrl: "https://stem.is/feed.xml",
    contentType: "Articles",
    dailyPostFrequency: 1,
    scrapeStatus: "active",
    priorityRank: 34,
    description: "Financial management, royalty split transparency, advance capital modeling, and label accounting.",
    editorialNotes: "Financial health and transparent cashflow forecasting for artists.",
  },
  {
    id: "plat-two-story-melody",
    name: "Two Story Melody",
    slug: "two-story-melody",
    pillar: "Indie Strategy & D2C",
    category: "tutorials",
    tier: "tier3",
    websiteUrl: "https://twostorymelody.com",
    rssFeedUrl: "https://twostorymelody.com/feed/",
    contentType: "Articles",
    dailyPostFrequency: 2,
    scrapeStatus: "active",
    priorityRank: 35,
    description: "Songwriting philosophy, album promotional campaigns, and direct fan community building.",
    editorialNotes: "Intimate artist interview series exploring the creative story behind indie singles.",
  },
  {
    id: "plat-music-think-tank",
    name: "Music Think Tank",
    slug: "music-think-tank",
    pillar: "Indie Strategy & D2C",
    category: "marketing",
    tier: "tier3",
    websiteUrl: "https://www.musicthinktank.com",
    rssFeedUrl: "https://www.musicthinktank.com/mtt/atom.xml",
    contentType: "Articles",
    dailyPostFrequency: 2,
    scrapeStatus: "active",
    priorityRank: 36,
    description: "Crowdsourced music business forum featuring guest essays by managers, publicists, and booking agents.",
    editorialNotes: "Community-driven tactical tips on merchandise and live performance contracts.",
  },
  {
    id: "plat-damien-keyes-portal",
    name: "Damien Keyes Academy",
    slug: "damien-keyes-academy",
    pillar: "Indie Strategy & D2C",
    category: "marketing",
    tier: "tier1",
    websiteUrl: "https://damienkeyes.com",
    youtubeChannelUrl: "https://www.youtube.com/@DamienKeyes",
    contentType: "Multi-Format",
    dailyPostFrequency: 3,
    scrapeStatus: "active",
    priorityRank: 37,
    description: "Release rollouts, TikTok content funnels, tour marketing, and DIY brand building.",
    editorialNotes: "Highly practical daily videos on release momentum and Spotify waterfall strategies.",
  },
  {
    id: "plat-andrew-southworth",
    name: "Andrew Southworth (Music Marketing)",
    slug: "andrew-southworth",
    pillar: "Indie Strategy & D2C",
    category: "marketing",
    tier: "tier2",
    websiteUrl: "https://generatormusic.com",
    youtubeChannelUrl: "https://www.youtube.com/@AndrewSouthworth",
    contentType: "Multi-Format",
    dailyPostFrequency: 2,
    scrapeStatus: "active",
    priorityRank: 38,
    description: "Meta Ads, TikTok Ad Manager, Spotify algorithmic conversion, and conversion API tracking.",
    editorialNotes: "The undisputed master of Meta Ads / Facebook Ads direct conversion funnels for Spotify.",
  },
  {
    id: "plat-burstimo",
    name: "Burstimo Music Marketing",
    slug: "burstimo-music-marketing",
    pillar: "Indie Strategy & D2C",
    category: "marketing",
    tier: "tier2",
    websiteUrl: "https://burstimo.com",
    youtubeChannelUrl: "https://www.youtube.com/@Burstimo",
    contentType: "Multi-Format",
    dailyPostFrequency: 2,
    scrapeStatus: "active",
    priorityRank: 39,
    description: "Music promotion agency breakdown: TikTok sound trends, playlist pitching scams, and PR strategy.",
    editorialNotes: "UK music marketing agency uncovering playlist payola scams and influencer marketing.",
  },
  {
    id: "plat-smart-rapper",
    name: "Smart Rapper (Rob Level)",
    slug: "smart-rapper",
    pillar: "Indie Strategy & D2C",
    category: "tutorials",
    tier: "tier3",
    websiteUrl: "https://smartrapper.com",
    youtubeChannelUrl: "https://www.youtube.com/@SmartRapper",
    contentType: "Videos",
    dailyPostFrequency: 1,
    scrapeStatus: "active",
    priorityRank: 40,
    description: "Hip-hop career development, vocal delivery techniques, beat leasing contracts, and studio discipline.",
    editorialNotes: "Targeted tutorials for independent rappers and hip-hop entrepreneurs.",
  },

  // ============================================================================
  // PILLAR 3: STREAMING INTELLIGENCE, METADATA & RIGHTS (15 Platforms)
  // ============================================================================
  {
    id: "plat-spotify-for-artists",
    name: "Spotify for Artists (News & Blog)",
    slug: "spotify-for-artists",
    pillar: "Streaming, Metadata & Rights",
    category: "streaming",
    tier: "tier1",
    websiteUrl: "https://artists.spotify.com/blog",
    rssFeedUrl: "https://artists.spotify.com/blog/rss",
    contentType: "Articles",
    dailyPostFrequency: 3,
    scrapeStatus: "active",
    priorityRank: 41,
    description: "Official product announcements, Discovery Mode metrics, Canvas best practices, and playlist pitching tips.",
    editorialNotes: "Primary source for algorithmic changes, 1000-stream rules, and Countdown Pages.",
  },
  {
    id: "plat-apple-music-artists",
    name: "Apple Music for Artists",
    slug: "apple-music-for-artists",
    pillar: "Streaming, Metadata & Rights",
    category: "streaming",
    tier: "tier1",
    websiteUrl: "https://artists.apple.com",
    rssFeedUrl: "https://artists.apple.com/feed.xml",
    contentType: "Articles",
    dailyPostFrequency: 1,
    scrapeStatus: "active",
    priorityRank: 42,
    description: "Spatial Audio guidelines, Shazam telemetry data, Apple Music Classical, and global radio play analytics.",
    editorialNotes: "Key resource for Dolby Atmos spatial audio mixing compliance and Shazam velocity.",
  },
  {
    id: "plat-songtrust-blog",
    name: "Songtrust Blog (Publishing & Royalties)",
    slug: "songtrust-blog",
    pillar: "Streaming, Metadata & Rights",
    category: "legal",
    tier: "tier1",
    websiteUrl: "https://blog.songtrust.com",
    rssFeedUrl: "https://blog.songtrust.com/rss.xml",
    contentType: "Articles",
    dailyPostFrequency: 2,
    scrapeStatus: "active",
    priorityRank: 43,
    description: "Global music publishing administration, mechanical royalty collection, PRO registrations, and sync splits.",
    editorialNotes: "Top authority on uncollected black box royalties, ISRC/ISWC mapping, and PRO administration.",
  },
  {
    id: "plat-songstats-blog",
    name: "Songstats Lab",
    slug: "songstats-lab",
    pillar: "Streaming, Metadata & Rights",
    category: "streaming",
    tier: "tier2",
    websiteUrl: "https://songstats.com/blog",
    rssFeedUrl: "https://songstats.com/feed",
    contentType: "Research & Data",
    dailyPostFrequency: 2,
    scrapeStatus: "active",
    priorityRank: 44,
    description: "Real-time cross-platform track analytics, playlist notification alerts, and DJ chart performance.",
    editorialNotes: "Live tracking of 1001Tracklists, Beatport, Apple Music, and Spotify playlist additions.",
  },
  {
    id: "plat-luminate-mrc",
    name: "Luminate Data (formerly MRC Data)",
    slug: "luminate-data",
    pillar: "Streaming, Metadata & Rights",
    category: "financial",
    tier: "tier1",
    websiteUrl: "https://luminatedata.com/insights",
    rssFeedUrl: "https://luminatedata.com/feed",
    contentType: "Research & Data",
    dailyPostFrequency: 2,
    scrapeStatus: "active",
    priorityRank: 45,
    description: "The definitive entertainment data platform powering the Billboard Charts and global industry reports.",
    editorialNotes: "Authoritative quarterly music consumption, stream volume, and genre share reports.",
  },
  {
    id: "plat-viberate",
    name: "Viberate Analytics",
    slug: "viberate-analytics",
    pillar: "Streaming, Metadata & Rights",
    category: "streaming",
    tier: "tier2",
    websiteUrl: "https://www.viberate.com/blog",
    rssFeedUrl: "https://www.viberate.com/feed",
    contentType: "Research & Data",
    dailyPostFrequency: 2,
    scrapeStatus: "active",
    priorityRank: 46,
    description: "Artist benchmarking, festival lineups intelligence, radio airplay charts, and playlist discovery tools.",
    editorialNotes: "Comparative metrics for emerging indie acts vs regional chart toppers.",
  },
  {
    id: "plat-future-of-music",
    name: "Future of Music Coalition",
    slug: "future-of-music-coalition",
    pillar: "Streaming, Metadata & Rights",
    category: "legal",
    tier: "tier2",
    websiteUrl: "https://futureofmusic.org",
    rssFeedUrl: "https://futureofmusic.org/feed",
    contentType: "Articles",
    dailyPostFrequency: 1,
    scrapeStatus: "active",
    priorityRank: 47,
    description: "Artist advocacy, copyright policy, net neutrality, and public policy for creator compensation.",
    editorialNotes: "Congressional testimony analysis and legal policy affecting artist streaming equity.",
  },
  {
    id: "plat-the-mlc",
    name: "The Mechanical Licensing Collective (The MLC)",
    slug: "the-mechanical-licensing-collective",
    pillar: "Streaming, Metadata & Rights",
    category: "legal",
    tier: "tier1",
    websiteUrl: "https://www.themlc.com/news",
    rssFeedUrl: "https://www.themlc.com/feed.xml",
    contentType: "Articles",
    dailyPostFrequency: 1,
    scrapeStatus: "active",
    priorityRank: 48,
    description: "Administers blanket mechanical licenses to streaming services in the US and pays mechanical royalties to songwriters.",
    editorialNotes: "Essential for US mechanical royalty matching and unmatched black-box search.",
  },
  {
    id: "plat-soundexchange-news",
    name: "SoundExchange Newsroom",
    slug: "soundexchange-newsroom",
    pillar: "Streaming, Metadata & Rights",
    category: "legal",
    tier: "tier1",
    websiteUrl: "https://www.soundexchange.com/newsroom",
    rssFeedUrl: "https://www.soundexchange.com/feed/",
    contentType: "Articles",
    dailyPostFrequency: 1,
    scrapeStatus: "active",
    priorityRank: 49,
    description: "Collects and distributes digital performance royalties for featured artists and master rights owners (Pandora, SiriusXM).",
    editorialNotes: "Primary source for statutory satellite and digital radio non-interactive master payouts.",
  },
  {
    id: "plat-ascap-blog",
    name: "ASCAP Inside Music",
    slug: "ascap-inside-music",
    pillar: "Streaming, Metadata & Rights",
    category: "legal",
    tier: "tier2",
    websiteUrl: "https://www.ascap.com/music-creators",
    rssFeedUrl: "https://www.ascap.com/rss/news.xml",
    contentType: "Articles",
    dailyPostFrequency: 2,
    scrapeStatus: "active",
    priorityRank: 50,
    description: "Songwriter advocacy, performance rights distributions, cue sheet compliance, and career workshops.",
    editorialNotes: "Public performance rights management and live performance royalty registration.",
  },
  {
    id: "plat-bmi-news",
    name: "BMI News & Songwriter Spotlights",
    slug: "bmi-news",
    pillar: "Streaming, Metadata & Rights",
    category: "legal",
    tier: "tier2",
    websiteUrl: "https://www.bmi.com/news",
    rssFeedUrl: "https://www.bmi.com/news/rss",
    contentType: "Articles",
    dailyPostFrequency: 2,
    scrapeStatus: "active",
    priorityRank: 51,
    description: "Performing rights organization news, Live at the Ace songwriter showcases, and copyright legislative updates.",
    editorialNotes: "PRO distribution dates, royalty calendar, and film scoring rights.",
  },
  {
    id: "plat-prs-for-music",
    name: "PRS for Music M-Magazine",
    slug: "prs-for-music-m-mag",
    pillar: "Streaming, Metadata & Rights",
    category: "legal",
    tier: "tier2",
    websiteUrl: "https://www.prsformusic.com/m-magazine",
    rssFeedUrl: "https://www.prsformusic.com/m-magazine/rss",
    contentType: "Articles",
    dailyPostFrequency: 2,
    scrapeStatus: "active",
    priorityRank: 52,
    description: "UK performing rights organization publication covering international touring collections and broadcast sync.",
    editorialNotes: "UK and European collection society insights and international sub-publishing.",
  },
  {
    id: "plat-copyright-alliance",
    name: "Copyright Alliance Blog",
    slug: "copyright-alliance",
    pillar: "Streaming, Metadata & Rights",
    category: "legal",
    tier: "tier3",
    websiteUrl: "https://copyrightalliance.org/news-events/copyright-news/",
    rssFeedUrl: "https://copyrightalliance.org/feed/",
    contentType: "Articles",
    dailyPostFrequency: 2,
    scrapeStatus: "active",
    priorityRank: 53,
    description: "US Copyright Office updates, CASE Act small claims tribunal rulings, and AI training dataset litigation.",
    editorialNotes: "Legal deep dives into CASE Act copyright small claims court proceedings.",
  },
  {
    id: "plat-sync-summit",
    name: "Sync Summit Insights",
    slug: "sync-summit-insights",
    pillar: "Streaming, Metadata & Rights",
    category: "opportunities",
    tier: "tier3",
    websiteUrl: "https://syncsummit.com/blog",
    rssFeedUrl: "https://syncsummit.com/feed",
    contentType: "Articles",
    dailyPostFrequency: 1,
    scrapeStatus: "active",
    priorityRank: 54,
    description: "Music supervisors, TV/film sync briefs, video game licensing budgets, and master clearing advice.",
    editorialNotes: "Music supervisor interviews and master synchronization rate cards.",
  },
  {
    id: "plat-aimp",
    name: "Association of Independent Music Publishers (AIMP)",
    slug: "aimp-news",
    pillar: "Streaming, Metadata & Rights",
    category: "legal",
    tier: "tier3",
    websiteUrl: "https://www.aimp.org",
    rssFeedUrl: "https://www.aimp.org/feed.xml",
    contentType: "Articles",
    dailyPostFrequency: 1,
    scrapeStatus: "active",
    priorityRank: 55,
    description: "Independent publisher education, sub-publishing in foreign territories, and synchronization splits.",
    editorialNotes: "Boutique publisher networking and foreign reciprocal collection society deals.",
  },

  // ============================================================================
  // PILLAR 4: AUDIO ENGINEERING, PRODUCTION & GEAR (20 Platforms)
  // ============================================================================
  {
    id: "plat-sound-on-sound",
    name: "Sound On Sound",
    slug: "sound-on-sound",
    pillar: "Audio Engineering & Production",
    category: "tutorials",
    tier: "tier1",
    websiteUrl: "https://www.soundonsound.com",
    rssFeedUrl: "https://www.soundonsound.com/news/feed",
    youtubeChannelUrl: "https://www.youtube.com/@SoundOnSound",
    contentType: "Multi-Format",
    dailyPostFrequency: 6,
    scrapeStatus: "active",
    priorityRank: 56,
    description: "The world's premier audio recording and music technology magazine.",
    editorialNotes: "Unrivaled studio hardware teardowns, microphone shootouts, and mix breakdowns.",
  },
  {
    id: "plat-tape-op",
    name: "Tape Op Magazine",
    slug: "tape-op",
    pillar: "Audio Engineering & Production",
    category: "tutorials",
    tier: "tier1",
    websiteUrl: "https://tapeop.com",
    rssFeedUrl: "https://tapeop.com/rss/",
    contentType: "Articles",
    dailyPostFrequency: 3,
    scrapeStatus: "active",
    priorityRank: 57,
    description: "Creative music recording magazine focusing on real-world engineer interviews and unpretentious studio techniques.",
    editorialNotes: "Legendary long-form interviews with iconic audio engineers, tracking workflows, and analog consoles.",
  },
  {
    id: "plat-musictech",
    name: "MusicTech",
    slug: "musictech",
    pillar: "Audio Engineering & Production",
    category: "tech-ai",
    tier: "tier1",
    websiteUrl: "https://musictech.com",
    rssFeedUrl: "https://musictech.com/feed/",
    contentType: "Articles",
    dailyPostFrequency: 5,
    scrapeStatus: "active",
    priorityRank: 58,
    description: "Reviews, tutorials, and buyer guides for modern music producers, synth enthusiasts, and audio professionals.",
    editorialNotes: "Top tier reviews of plugin suites, DAWs, MIDI controllers, and audio interfaces.",
  },
  {
    id: "plat-attack-mag",
    name: "Attack Magazine",
    slug: "attack-magazine",
    pillar: "Audio Engineering & Production",
    category: "tutorials",
    tier: "tier1",
    websiteUrl: "https://www.attackmagazine.com",
    rssFeedUrl: "https://www.attackmagazine.com/feed/",
    contentType: "Articles",
    dailyPostFrequency: 4,
    scrapeStatus: "active",
    priorityRank: 59,
    description: "Electronic music production, beat programming, synth patch breakdowns, and studio technique.",
    editorialNotes: "Famous 'Beat Dissected' and 'Synth Secrets' step-by-step production series.",
  },
  {
    id: "plat-gearspace",
    name: "Gearspace (formerly Gearslutz)",
    slug: "gearspace",
    pillar: "Audio Engineering & Production",
    category: "tutorials",
    tier: "tier1",
    websiteUrl: "https://gearspace.com",
    rssFeedUrl: "https://gearspace.com/board/external.php?type=rss2",
    contentType: "Articles",
    dailyPostFrequency: 8,
    scrapeStatus: "active",
    priorityRank: 60,
    description: "The largest global community for pro audio engineers, studio builders, and hardware collectors.",
    editorialNotes: "Community discussion threads on converter shootouts, outboard preamps, and summing mixers.",
  },
  {
    id: "plat-production-expert",
    name: "Production Expert (Pro Tools / Studio One)",
    slug: "production-expert",
    pillar: "Audio Engineering & Production",
    category: "tutorials",
    tier: "tier2",
    websiteUrl: "https://www.production-expert.com",
    rssFeedUrl: "https://www.production-expert.com/production-expert-1?format=rss",
    contentType: "Articles",
    dailyPostFrequency: 5,
    scrapeStatus: "active",
    priorityRank: 61,
    description: "Independent workflow tutorials for Pro Tools, Studio One, Logic Pro, and Atmos post-production.",
    editorialNotes: "Go-to resource for DAW performance optimization, audio driver updates, and plugin compatibility.",
  },
  {
    id: "plat-mix-online",
    name: "Mix Online",
    slug: "mix-online",
    pillar: "Audio Engineering & Production",
    category: "tutorials",
    tier: "tier2",
    websiteUrl: "https://www.mixonline.com",
    rssFeedUrl: "https://www.mixonline.com/feed",
    contentType: "Articles",
    dailyPostFrequency: 4,
    scrapeStatus: "active",
    priorityRank: 62,
    description: "Professional audio, live sound reinforcement, studio architecture, and commercial facility design.",
    editorialNotes: "Live concert sound arrays (L-Acoustics, d&b audiotechnik) and immersive theater mixing.",
  },
  {
    id: "plat-cdm",
    name: "CDM (Create Digital Music)",
    slug: "create-digital-music",
    pillar: "Audio Engineering & Production",
    category: "tech-ai",
    tier: "tier2",
    websiteUrl: "https://cdm.link",
    rssFeedUrl: "https://cdm.link/feed/",
    contentType: "Articles",
    dailyPostFrequency: 3,
    scrapeStatus: "active",
    priorityRank: 63,
    description: "Peter Kirn's open-source music hardware, modular synthesis, Max/MSP, and live coding culture.",
    editorialNotes: "Focus on Eurorack modular synthesizers, Pure Data, and generative visual-audio performance.",
  },
  {
    id: "plat-kvr-audio",
    name: "KVR Audio News",
    slug: "kvr-audio",
    pillar: "Audio Engineering & Production",
    category: "tech-ai",
    tier: "tier2",
    websiteUrl: "https://www.kvraudio.com",
    rssFeedUrl: "https://www.kvraudio.com/news/rss.php",
    contentType: "Articles",
    dailyPostFrequency: 10,
    scrapeStatus: "active",
    priorityRank: 64,
    description: "The global hub for audio plugins, VSTs, virtual instruments, and soundware release announcements.",
    editorialNotes: "Real-time index of every plugin release, VST3 update, and seasonal audio developer sale.",
  },
  {
    id: "plat-waves-blog",
    name: "Waves Audio Blog",
    slug: "waves-audio-blog",
    pillar: "Audio Engineering & Production",
    category: "tutorials",
    tier: "tier2",
    websiteUrl: "https://www.waves.com/blog",
    rssFeedUrl: "https://www.waves.com/blog/feed",
    contentType: "Articles",
    dailyPostFrequency: 2,
    scrapeStatus: "active",
    priorityRank: 65,
    description: "Vocal mixing chains, master bus compression, EQ carving, and multi-track session staging.",
    editorialNotes: "Detailed chain walkthroughs from Grammy-winning mix engineers (Chris Lord-Alge, Tony Maserati).",
  },
  {
    id: "plat-izotope-learn",
    name: "iZotope Learn & Master",
    slug: "izotope-learn",
    pillar: "Audio Engineering & Production",
    category: "tutorials",
    tier: "tier2",
    websiteUrl: "https://www.izotope.com/en/learn.html",
    rssFeedUrl: "https://www.izotope.com/en/learn.rss",
    contentType: "Articles",
    dailyPostFrequency: 2,
    scrapeStatus: "active",
    priorityRank: 66,
    description: "Audio mastering basics, spectral repair with RX, dynamic EQ, and LUFS loudness normalization.",
    editorialNotes: "The gold standard for spectral audio restoration, RX repair workflows, and mastering limiter curves.",
  },
  {
    id: "plat-splice-blog",
    name: "Splice Blog",
    slug: "splice-blog",
    pillar: "Audio Engineering & Production",
    category: "tutorials",
    tier: "tier2",
    websiteUrl: "https://splice.com/blog",
    rssFeedUrl: "https://splice.com/blog/feed/",
    contentType: "Articles",
    dailyPostFrequency: 3,
    scrapeStatus: "active",
    priorityRank: 67,
    description: "Sample flipping techniques, beatmaker interviews, CoSo AI creation, and sound design tutorials.",
    editorialNotes: "Creative sample manipulation and beat arrangement breakdowns.",
  },
  {
    id: "plat-native-instruments",
    name: "Native Instruments Blog",
    slug: "native-instruments-blog",
    pillar: "Audio Engineering & Production",
    category: "tech-ai",
    tier: "tier2",
    websiteUrl: "https://blog.native-instruments.com",
    rssFeedUrl: "https://blog.native-instruments.com/feed/",
    contentType: "Articles",
    dailyPostFrequency: 2,
    scrapeStatus: "active",
    priorityRank: 68,
    description: "Kontakt scripting, Maschine finger drumming, Traktor DJ routines, and Komplete sound libraries.",
    editorialNotes: "Virtual instrument orchestration and electronic music workflows.",
  },
  {
    id: "plat-bedroom-producers",
    name: "Bedroom Producers Blog (BPB)",
    slug: "bedroom-producers-blog",
    pillar: "Audio Engineering & Production",
    category: "tutorials",
    tier: "tier2",
    websiteUrl: "https://bedroomproducersblog.com",
    rssFeedUrl: "https://bedroomproducersblog.com/feed/",
    contentType: "Articles",
    dailyPostFrequency: 3,
    scrapeStatus: "active",
    priorityRank: 69,
    description: "Freeware audio plugins, free sample packs, synthesizers, and budget home studio guides.",
    editorialNotes: "Best destination on the web for free legitimate VST plugins and developer giveaways.",
  },
  {
    id: "plat-rekkerd",
    name: "Rekkerd.org",
    slug: "rekkerd",
    pillar: "Audio Engineering & Production",
    category: "tutorials",
    tier: "tier3",
    websiteUrl: "https://rekkerd.org",
    rssFeedUrl: "https://rekkerd.org/feed/",
    contentType: "Articles",
    dailyPostFrequency: 4,
    scrapeStatus: "active",
    priorityRank: 70,
    description: "Audio plugin deals, software synthesizer presets, sample library reviews, and production contests.",
    editorialNotes: "Continuous feed of daily plugin discounts and sound pack releases.",
  },
  {
    id: "plat-sonicstate",
    name: "Sonicstate",
    slug: "sonicstate",
    pillar: "Audio Engineering & Production",
    category: "tech-ai",
    tier: "tier2",
    websiteUrl: "https://sonicstate.com",
    rssFeedUrl: "https://sonicstate.com/news/rss.xml",
    youtubeChannelUrl: "https://www.youtube.com/@Sonicstate",
    contentType: "Multi-Format",
    dailyPostFrequency: 4,
    scrapeStatus: "active",
    priorityRank: 71,
    description: "Synthesizer reviews, NAMM / Superbooth gear coverage, and the Sonic TALK weekly podcast.",
    editorialNotes: "Nick Batt's legendary synthesizer teardowns and PWM analysis.",
  },
  {
    id: "plat-musicradar",
    name: "MusicRadar Tech",
    slug: "musicradar-tech",
    pillar: "Audio Engineering & Production",
    category: "tutorials",
    tier: "tier2",
    websiteUrl: "https://www.musicradar.com/tech",
    rssFeedUrl: "https://www.musicradar.com/rss/news/tech",
    contentType: "Articles",
    dailyPostFrequency: 6,
    scrapeStatus: "active",
    priorityRank: 72,
    description: "Future Music & Computer Music magazine online articles, DAW reviews, and sample downloads.",
    editorialNotes: "Producer masterclasses and producer desk tour breakdowns.",
  },
  {
    id: "plat-pensados-place",
    name: "Pensado's Place",
    slug: "pensados-place",
    pillar: "Audio Engineering & Production",
    category: "tutorials",
    tier: "tier1",
    websiteUrl: "https://pensadosplace.tv",
    youtubeChannelUrl: "https://www.youtube.com/@PensadosPlace",
    contentType: "Multi-Format",
    dailyPostFrequency: 2,
    scrapeStatus: "active",
    priorityRank: 73,
    description: "Dave Pensado and Herb Trawick's legendary master mix tutorials and top mixer interviews.",
    editorialNotes: "The ultimate university for multi-track vocal, drum, and low-end mixing.",
  },
  {
    id: "plat-produce-like-a-pro",
    name: "Produce Like A Pro (Warren Huart)",
    slug: "produce-like-a-pro",
    pillar: "Audio Engineering & Production",
    category: "tutorials",
    tier: "tier1",
    websiteUrl: "https://producelikeapro.com",
    youtubeChannelUrl: "https://www.youtube.com/@ProduceLikeAPro",
    contentType: "Multi-Format",
    dailyPostFrequency: 3,
    scrapeStatus: "active",
    priorityRank: 74,
    description: "Warren Huart deconstructs legendary multitracks from Aerosmith, The Ramones, and modern hits.",
    editorialNotes: "Real multitrack studio breakdowns and classic analog gear comparisons.",
  },
  {
    id: "plat-in-the-mix",
    name: "In The Mix (Michael Wynne)",
    slug: "in-the-mix",
    pillar: "Audio Engineering & Production",
    category: "tutorials",
    tier: "tier1",
    websiteUrl: "https://inthemix.io",
    youtubeChannelUrl: "https://www.youtube.com/@inthemix",
    contentType: "Videos",
    dailyPostFrequency: 2,
    scrapeStatus: "active",
    priorityRank: 75,
    description: "Crystal clear audio production, EQ curves, dynamic compression, and FL Studio / studio workflows.",
    editorialNotes: "Highest pedagogical quality mixing and mastering visual guides online.",
  },

  // ============================================================================
  // PILLAR 5: CULTURE, EDITORIAL & MUSIC DISCOVERY (15 Platforms)
  // ============================================================================
  {
    id: "plat-pitchfork",
    name: "Pitchfork",
    slug: "pitchfork",
    pillar: "Culture, Editorial & Discovery",
    category: "marketing",
    tier: "tier1",
    websiteUrl: "https://pitchfork.com",
    rssFeedUrl: "https://pitchfork.com/feed/feed-news/rss",
    contentType: "Articles",
    dailyPostFrequency: 10,
    scrapeStatus: "active",
    priorityRank: 76,
    description: "The essential guide to independent music criticism, Best New Music, and cultural commentary.",
    editorialNotes: "Influential album rating benchmark (BNM) driving indie streaming discovery.",
  },
  {
    id: "plat-stereogum",
    name: "Stereogum",
    slug: "stereogum",
    pillar: "Culture, Editorial & Discovery",
    category: "streaming",
    tier: "tier1",
    websiteUrl: "https://www.stereogum.com",
    rssFeedUrl: "https://www.stereogum.com/feed/",
    contentType: "Articles",
    dailyPostFrequency: 12,
    scrapeStatus: "active",
    priorityRank: 77,
    description: "Daily independent music news, premieres, Album of the Week, and industry opinion.",
    editorialNotes: "Fastest breaking indie single drops, festival lineup reveals, and tour reviews.",
  },
  {
    id: "plat-bandcamp-daily",
    name: "Bandcamp Daily",
    slug: "bandcamp-daily",
    pillar: "Culture, Editorial & Discovery",
    category: "marketing",
    tier: "tier1",
    websiteUrl: "https://daily.bandcamp.com",
    rssFeedUrl: "https://daily.bandcamp.com/feed",
    contentType: "Articles",
    dailyPostFrequency: 4,
    scrapeStatus: "active",
    priorityRank: 78,
    description: "Editorial platform celebrating grassroots music scenes, cassette labels, and global sounds.",
    editorialNotes: "Essential for niche underground genres, Bandcamp Friday features, and physical merch.",
  },
  {
    id: "plat-the-quietus",
    name: "The Quietus",
    slug: "the-quietus",
    pillar: "Culture, Editorial & Discovery",
    category: "social",
    tier: "tier1",
    websiteUrl: "https://thequietus.com",
    rssFeedUrl: "https://thequietus.com/feed/",
    contentType: "Articles",
    dailyPostFrequency: 4,
    scrapeStatus: "active",
    priorityRank: 79,
    description: "Intelligent, uncompromising music criticism covering experimental, avant-garde, and underground culture.",
    editorialNotes: "Thought-provoking long-form cultural essays and avant-garde album reviews.",
  },
  {
    id: "plat-dj-mag",
    name: "DJ Mag",
    slug: "dj-mag",
    pillar: "Culture, Editorial & Discovery",
    category: "marketing",
    tier: "tier1",
    websiteUrl: "https://djmag.com",
    rssFeedUrl: "https://djmag.com/feed.xml",
    contentType: "Articles",
    dailyPostFrequency: 8,
    scrapeStatus: "active",
    priorityRank: 80,
    description: "Global electronic dance music authority, Top 100 DJs, club culture, and festival coverage.",
    editorialNotes: "Benchmark for electronic dance music festivals, club residencies, and DJ tech.",
  },
  {
    id: "plat-resident-advisor",
    name: "Resident Advisor (RA)",
    slug: "resident-advisor",
    pillar: "Culture, Editorial & Discovery",
    category: "social",
    tier: "tier1",
    websiteUrl: "https://ra.co",
    rssFeedUrl: "https://ra.co/xml/news.xml",
    contentType: "Articles",
    dailyPostFrequency: 8,
    scrapeStatus: "active",
    priorityRank: 81,
    description: "The global platform for electronic music, club listings, festival ticketing, and investigative journalism.",
    editorialNotes: "The undisputed epicenter of underground techno, house, club culture, and ticketing.",
  },
  {
    id: "plat-clash-mag",
    name: "Clash Magazine",
    slug: "clash-magazine",
    pillar: "Culture, Editorial & Discovery",
    category: "marketing",
    tier: "tier2",
    websiteUrl: "https://www.clashmusic.com",
    rssFeedUrl: "https://www.clashmusic.com/feed/",
    contentType: "Articles",
    dailyPostFrequency: 8,
    scrapeStatus: "active",
    priorityRank: 82,
    description: "UK fashion, music, and cultural lifestyle magazine featuring emerging indie and hip-hop stars.",
    editorialNotes: "Great tastemaker premieres and high-fashion visual editorial spreads.",
  },
  {
    id: "plat-the-line-of-best-fit",
    name: "The Line of Best Fit",
    slug: "the-line-of-best-fit",
    pillar: "Culture, Editorial & Discovery",
    category: "marketing",
    tier: "tier2",
    websiteUrl: "https://www.thelineofbestfit.com",
    rssFeedUrl: "https://www.thelineofbestfit.com/news/rss",
    contentType: "Articles",
    dailyPostFrequency: 6,
    scrapeStatus: "active",
    priorityRank: 83,
    description: "Independent online music magazine showcasing new music discovery, secret sessions, and festival guides.",
    editorialNotes: "Influential tastemaker publication for UK, European, and Scandinavian indie acts.",
  },
  {
    id: "plat-nme",
    name: "NME (New Musical Express)",
    slug: "nme",
    pillar: "Culture, Editorial & Discovery",
    category: "marketing",
    tier: "tier1",
    websiteUrl: "https://www.nme.com",
    rssFeedUrl: "https://www.nme.com/feed",
    contentType: "Articles",
    dailyPostFrequency: 14,
    scrapeStatus: "active",
    priorityRank: 84,
    description: "Historic British pop culture brand covering music, film, gaming, and emerging live talent.",
    editorialNotes: "Global youth culture news, festival headliner rumors, and NME 100 essential acts.",
  },
  {
    id: "plat-xlr8r",
    name: "XLR8R",
    slug: "xlr8r",
    pillar: "Culture, Editorial & Discovery",
    category: "marketing",
    tier: "tier2",
    websiteUrl: "https://xlr8r.com",
    rssFeedUrl: "https://xlr8r.com/feed/",
    contentType: "Articles",
    dailyPostFrequency: 3,
    scrapeStatus: "active",
    priorityRank: 85,
    description: "Electronic music, downloads, podcasts, and studio features on underground techno and ambient artists.",
    editorialNotes: "Exclusive free music downloads, podcast mixes, and boutique soundscapes.",
  },
  {
    id: "plat-the-fader",
    name: "The FADER",
    slug: "the-fader",
    pillar: "Culture, Editorial & Discovery",
    category: "marketing",
    tier: "tier1",
    websiteUrl: "https://www.thefader.com",
    rssFeedUrl: "https://www.thefader.com/feed",
    contentType: "Articles",
    dailyPostFrequency: 7,
    scrapeStatus: "active",
    priorityRank: 86,
    description: "Definitive voice in modern music culture, breaking emerging hip-hop, R&B, and indie luminaries.",
    editorialNotes: "Legendary cover stories that define emerging youth music icons.",
  },
  {
    id: "plat-fact-mag",
    name: "Fact Magazine",
    slug: "fact-magazine",
    pillar: "Culture, Editorial & Discovery",
    category: "tech-ai",
    tier: "tier2",
    websiteUrl: "https://www.factmag.com",
    rssFeedUrl: "https://www.factmag.com/feed/",
    contentType: "Multi-Format",
    dailyPostFrequency: 3,
    scrapeStatus: "active",
    priorityRank: 87,
    description: "Audiovisual culture, 180 Strand exhibitions, 'Against The Clock' 10-minute beat challenges.",
    editorialNotes: "Stunning audiovisual art and high-pressure producer creative challenges.",
  },
  {
    id: "plat-mixmag",
    name: "Mixmag",
    slug: "mixmag",
    pillar: "Culture, Editorial & Discovery",
    category: "marketing",
    tier: "tier1",
    websiteUrl: "https://mixmag.net",
    rssFeedUrl: "https://mixmag.net/rss.xml",
    contentType: "Articles",
    dailyPostFrequency: 8,
    scrapeStatus: "active",
    priorityRank: 88,
    description: "Dance music and club culture news, live DJ streams from The Lab, and global nightlife safety.",
    editorialNotes: "Pioneer in streaming live DJ sets with global club culture journalism.",
  },
  {
    id: "plat-dummy-mag",
    name: "Dummy Mag",
    slug: "dummy-mag",
    pillar: "Culture, Editorial & Discovery",
    category: "marketing",
    tier: "tier3",
    websiteUrl: "https://dummymag.com",
    rssFeedUrl: "https://dummymag.com/feed/",
    contentType: "Articles",
    dailyPostFrequency: 3,
    scrapeStatus: "active",
    priorityRank: 89,
    description: "Discovery platform for underground future pop, rap, drill, and electronic producers.",
    editorialNotes: "Tastemaker curated playlists and premiere coverage for left-field electronic acts.",
  },
  {
    id: "plat-loud-and-quiet",
    name: "Loud and Quiet",
    slug: "loud-and-quiet",
    pillar: "Culture, Editorial & Discovery",
    category: "social",
    tier: "tier3",
    websiteUrl: "https://www.loudandquiet.com",
    rssFeedUrl: "https://www.loudandquiet.com/feed/",
    contentType: "Articles",
    dailyPostFrequency: 2,
    scrapeStatus: "active",
    priorityRank: 90,
    description: "Independent UK music journalism, print zines, and unfiltered long-form profiles.",
    editorialNotes: "High-integrity independent music criticism free from corporate PR fluff.",
  },

  // ============================================================================
  // PILLAR 6: PODCASTS & VIDEO CHANNELS (10 Platforms)
  // ============================================================================
  {
    id: "plat-trapital-podcast",
    name: "The Trapital Podcast (Dan Runcie)",
    slug: "the-trapital-podcast",
    pillar: "Podcasts & Video Channels",
    category: "podcasts",
    tier: "tier1",
    websiteUrl: "https://trapital.co/podcast",
    rssFeedUrl: "https://feeds.buzzsprout.com/264104.rss",
    youtubeChannelUrl: "https://www.youtube.com/@Trapital",
    contentType: "Podcasts",
    dailyPostFrequency: 1,
    scrapeStatus: "active",
    priorityRank: 91,
    description: "Weekly conversations with top executives, artists, and investors shaping music and entertainment.",
    editorialNotes: "Essential podcast for master rights, D2C ventures, and hip-hop executive strategy.",
  },
  {
    id: "plat-mbw-podcast",
    name: "The Music Business Worldwide Podcast",
    slug: "mbw-podcast",
    pillar: "Podcasts & Video Channels",
    category: "podcasts",
    tier: "tier1",
    websiteUrl: "https://www.musicbusinessworldwide.com/podcast",
    rssFeedUrl: "https://feeds.buzzsprout.com/1317134.rss",
    youtubeChannelUrl: "https://www.youtube.com/@MusicBusinessWorldwide",
    contentType: "Podcasts",
    dailyPostFrequency: 1,
    scrapeStatus: "active",
    priorityRank: 92,
    description: "Tim Ingham interviews the power brokers behind the recorded music and music publishing industries.",
    editorialNotes: "Interviews with CEOs of Sony, UMG, Warner, Believe, and top private equity investors.",
  },
  {
    id: "plat-your-morning-coffee",
    name: "Your Morning Coffee Podcast (Jay Gilbert & Mike Doernberg)",
    slug: "your-morning-coffee-podcast",
    pillar: "Podcasts & Video Channels",
    category: "podcasts",
    tier: "tier1",
    websiteUrl: "https://yourmorningcoffee.buzzsprout.com",
    rssFeedUrl: "https://feeds.buzzsprout.com/1199341.rss",
    contentType: "Podcasts",
    dailyPostFrequency: 1,
    scrapeStatus: "active",
    priorityRank: 93,
    description: "Weekly audio breakdown of the top stories at the intersection of music, data, and digital tech.",
    editorialNotes: "Fast-paced weekly industry recap analyzing streaming telemetry and marketing news.",
  },
  {
    id: "plat-and-the-writer-is",
    name: "And The Writer Is... (Ross Golan)",
    slug: "and-the-writer-is",
    pillar: "Podcasts & Video Channels",
    category: "podcasts",
    tier: "tier1",
    websiteUrl: "https://www.andthewriteris.com",
    rssFeedUrl: "https://feeds.megaphone.fm/andthewriteris",
    contentType: "Podcasts",
    dailyPostFrequency: 1,
    scrapeStatus: "active",
    priorityRank: 94,
    description: "In-depth conversations with the acclaimed songwriters behind the biggest global hits in music history.",
    editorialNotes: "Masterclass on song splits, publisher deals, and songwriting work ethics.",
  },
  {
    id: "plat-rick-beato-video",
    name: "Rick Beato (Everything Music)",
    slug: "rick-beato-everything-music",
    pillar: "Podcasts & Video Channels",
    category: "tutorials",
    tier: "tier1",
    websiteUrl: "https://rickbeato.com",
    youtubeChannelUrl: "https://www.youtube.com/@RickBeato",
    youtubeChannelId: "UCJquYOG5EL82sKTfH9aMA9Q",
    contentType: "Videos",
    dailyPostFrequency: 2,
    scrapeStatus: "active",
    priorityRank: 95,
    description: "Deep harmonic analyses, 'What Makes This Song Great?', music business rants, and rock legend interviews.",
    editorialNotes: "Over 4.3M subscribers; premier music theory, song craft, and industry reality channel.",
  },
  {
    id: "plat-andrew-huang-video",
    name: "Andrew Huang",
    slug: "andrew-huang-channel",
    pillar: "Podcasts & Video Channels",
    category: "tech-ai",
    tier: "tier1",
    websiteUrl: "https://andrewhuang.com",
    youtubeChannelUrl: "https://www.youtube.com/@AndrewHuang",
    youtubeChannelId: "UCdcEMYGoRSmDNF_tZPRnTeA",
    contentType: "Videos",
    dailyPostFrequency: 1,
    scrapeStatus: "active",
    priorityRank: 96,
    description: "Creative music production, synthesizer experimentation, 4-producers 1-sample challenges, and music theory.",
    editorialNotes: "One of the most engaging creative music production educators on YouTube.",
  },
  {
    id: "plat-berklee-online-video",
    name: "Berklee Online Video",
    slug: "berklee-online-video",
    pillar: "Podcasts & Video Channels",
    category: "tutorials",
    tier: "tier1",
    websiteUrl: "https://online.berklee.edu",
    youtubeChannelUrl: "https://www.youtube.com/@BerkleeOnline",
    youtubeChannelId: "UCk1T8h-03Zk6-P51Ld4mUoA",
    contentType: "Videos",
    dailyPostFrequency: 2,
    scrapeStatus: "active",
    priorityRank: 97,
    description: "Official online lessons from Berklee College of Music faculty on mixing, orchestration, and business.",
    editorialNotes: "World-class university grade instruction in harmony, audio mastering, and songwriting.",
  },
  {
    id: "plat-adam-neely-video",
    name: "Adam Neely",
    slug: "adam-neely-video",
    pillar: "Podcasts & Video Channels",
    category: "social",
    tier: "tier1",
    websiteUrl: "https://adamneely.com",
    youtubeChannelUrl: "https://www.youtube.com/@AdamNeely",
    youtubeChannelId: "UCnkp4xDOwqqJD7sSM3xdUiQ",
    contentType: "Videos",
    dailyPostFrequency: 1,
    scrapeStatus: "active",
    priorityRank: 98,
    description: "Video essays on contemporary music theory, copyright lawsuits (Ed Sheeran/Marvin Gaye), and jazz microtonality.",
    editorialNotes: "The undisputed master of forensic music theory and legal copyright analysis.",
  },
  {
    id: "plat-npr-music-video",
    name: "NPR Music (Tiny Desk Concerts)",
    slug: "npr-music-tiny-desk",
    pillar: "Podcasts & Video Channels",
    category: "social",
    tier: "tier1",
    websiteUrl: "https://www.npr.org/music",
    rssFeedUrl: "https://feeds.npr.org/1039/rss.xml",
    youtubeChannelUrl: "https://www.youtube.com/@nprmusic",
    youtubeChannelId: "UC4eYXhJI4-7wSWc8UNRwD4A",
    contentType: "Multi-Format",
    dailyPostFrequency: 3,
    scrapeStatus: "active",
    priorityRank: 99,
    description: "Intimate live performances from behind Bob Boilen's desk, discovering global acoustic and neo-soul acts.",
    editorialNotes: "Top live performance benchmark for viral organic artist momentum.",
  },
  {
    id: "plat-producergrind-podcast",
    name: "Producergrind Podcast",
    slug: "producergrind-podcast",
    pillar: "Podcasts & Video Channels",
    category: "podcasts",
    tier: "tier1",
    websiteUrl: "https://producergrind.com",
    youtubeChannelUrl: "https://www.youtube.com/@Producergrind",
    contentType: "Podcasts",
    dailyPostFrequency: 2,
    scrapeStatus: "active",
    priorityRank: 100,
    description: "Interviews with multi-platinum hip-hop producers on publishing splits, sample clearances, and selling beats.",
    editorialNotes: "Crucial for hip-hop beatmakers navigating co-producer agreements and major label advances.",
  },
];
